### ISSUE TITLE
Crash when invoke method

### ISSUE THREAD

**Issue by Guitronic** [KDAB/GammaRay#1001]
On the latest version, Gammaray crashes when invoking a method, on version 3.0.93 gammaray does not crash but indicates "Invocation failed.."

**Comment by Waqar144** [comment]
Hi, thanks for reporting.

Can you share a minimal app and steps needed to reproduce the crash? I can't reproduce it with our https://github.com/KDAB/GammaRay/blob/3.1/tests/targets/minimalwidgetapplication.cpp

**Comment by Guitronic** [comment]
> Hi, thanks for reporting.
> 
> Can you share a minimal app and steps needed to reproduce the crash? I can't reproduce it with our https://github.com/KDAB/GammaRay/blob/3.1/tests/targets/minimalwidgetapplication.cpp

I will test your application and get back to you.

**Comment by Guitronic** [comment]
I tested well with your application, if I invoke the method "void click()" in "Objects" I get the message "Invocation failed: Invalid object, probably got deleted in the meantime." and gammaray crashes after a few seconds. If I invoke the same method in "Widgets" I get the message "Invocation failed.." and crashes after a few seconds.
I use gammaray version 3.1.1 recompiled this morning with Qt 6.6.3 under GCC 64bits

**Comment by Waqar144** [comment]
Can you try with latest 3.1?

**Comment by Guitronic** [comment]
> Can you try with latest 3.1?

Ok with your correction everything seems to work.
A big thank you to you.
