### ISSUE TITLE
Bad return for ObjectBroker

### ISSUE THREAD

**Issue by Guitronic** [KDAB/GammaRay#1003]
ObjectBroker::hasObject("GammaRay::ObjectInspector") or ObjectBroker::hasObject("com.kdab.GammaRay.ObjectInspectorTree") always return false.
But ObjectBroker::objectInternal("anything") return QObject(0x134bec0, name = "anything"), isn't that weird?

**Comment by Waqar144** [comment]
what are you trying to do? Please post full details with full steps to reproduce the issue, ideally with a minimal reproducible example

**Comment by Guitronic** [comment]
I'm making a test program to replace Appium that doesn't work on Linux.
After a connection with the GammaRay::Launcher and GammaRay::ClientConnectionManager classes, I get the model ObjectBroker::model("com.kdab.GammaRay.ObjectInspectorTree") and it works fine. But if I check the existence of this object with ObjectBroker::hasObject("com.kdab.GammaRay.ObjectInspectorTree"), I always get 'false'.
I feel like the 'hasObject' and 'objectInternal' methods return anything. Is this normal?
