### ISSUE TITLE
Model problem with delegate

### ISSUE THREAD

**Issue by Guitronic** [KDAB/GammaRay#1004]
If we use the ObjectBroker::model("com.kdab.GammaRay.ObjectInspector.properties") model, if we look for the value of a field that uses a delegate to display a checkBox, we receive an invalid QModelIndex.

**Comment by Waqar144** [comment]
what are you trying to do? Please post full details with full steps to reproduce the issue, ideally with a minimal reproducible example

**Comment by Guitronic** [comment]
I found an acceptable solution, you have to use the Qt::EditRole role.
For example with the QPushButton avec 'text 'property:
- role: Qt::DisplayRole QVariant(QString, "Hello World!")
- role: Qt::EditRole QVariant(QString, "Hello World!")
And for 'enabled' property:
- role: Qt::DisplayRole QVariant(Invalid)
- role: Qt::EditRole QVariant(bool, true) <== Good
The Qt::EditRole is an acceptable solution.
Thank you, I am closing the ticket
