### ISSUE TITLE
Multiple linker errors while building (Qt 5.4 MSVC 2013)

### ISSUE THREAD

**Issue by gurmeetkochar** [KDAB/GammaRay#101]
Please help, I'm getting the following errors while building:

    qtmain.lib(qtmain_win.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj

    msvcrt.lib(ti_inst.obj) : error LNK2005: "private: __cdecl type_info::type_info(class type_info const &)" (??0type_info@@AEAA@AEBV0@@Z) already defined in LIBCMT.lib(typinfo.obj)

    msvcrt.lib(ti_inst.obj) : error LNK2005: "private: class type_info & __cdecl type_info::operator=(class type_info const &)" (??4type_info@@AEAAAEAV0@AEBV0@@Z) already defined in LIBCMT.lib(typinfo.obj)

    msvcrt.lib(MSVCR120.dll) : error LNK2005: memmove already defined in LIBCMT.lib(memcpy.obj)

    msvcrt.lib(MSVCR120.dll) : error LNK2005: _hypot already defined in LIBCMT.lib(hypot.obj)

    msvcprt.lib(MSVCP120.dll) : error LNK2005: "void __cdecl std::_Xbad_alloc(void)" (?_Xbad_alloc@std@@YAXXZ) already defined in libcpmt.lib(xthrow.obj)

    msvcprt.lib(MSVCP120.dll) : error LNK2005: "void __cdecl std::_Xlength_error(char const *)" (?_Xlength_error@std@@YAXPEBD@Z) already defined in libcpmt.lib(xthrow.obj)

    msvcprt.lib(MSVCP120.dll) : error LNK2005: "void __cdecl std::_Xout_of_range(char const *)" (?_Xout_of_range@std@@YAXPEBD@Z) already defined in libcpmt.lib(xthrow.obj)

    msvcprt.lib(MSVCP120.dll) : error LNK2005: "char const * __cdecl std::_Syserror_map(int)" (?_Syserror_map@std@@YAPEBDH@Z) already defined in libcpmt.lib(syserror.obj)

    msvcprt.lib(MSVCP120.dll) : error LNK2005: "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPEBDH@Z) already defined in libcpmt.lib(syserror.obj)

    LIBCMT.lib(crt0init.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library

    ..\..\bin\gammaray-launcher.exe : fatal error LNK1169: one or more multiply defined symbols found

    LINK failed. with 1169
    jom: G:\GammaRay-master\launcher\ui\CMakeFiles\gammaray-launcher.dir\build.make [bin\gammaray-launcher.exe] Error 2
    jom: G:\GammaRay-master\CMakeFiles\Makefile2 [launcher\ui\CMakeFiles\gammaray-launcher.dir\all] Error 2
    jom: G:\GammaRay-master\Makefile [all] Error 2
    11:14:24: The process "C:\Qt\Qt5.4.0\Tools\QtCreator\bin\jom.exe" exited with code 2.
    Error while building/deploying project GammaRay (kit: Desktop Qt 5.4.0 MSVC2013 64bit)

**Comment by pnezis** [comment]
I face a similar linking issue while building the latest version. I use Qt 5.5 with VS2013

```
[ 33%] Built target gammaray_launcher_ui_internal_automoc
[ 36%] Built target gammaray_launcher_ui_internal
[ 36%] Automatic moc for target gammaray-launcher
[ 36%] Built target gammaray-launcher_automoc
[ 36%] Linking CXX executable ..\..\bin\gammaray-launcher.exe qtmain.lib(qtmain_win.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
msvcrt.lib(ti_inst.obj) : error LNK2005: "private: __thiscall type_info::type_info(class type_info const &)" (??0type_info@@AAE@ABV0@@Z) already defined in LIBCMT.lib(typinfo.obj)
msvcrt.lib(ti_inst.obj) : error LNK2005: "private: class type_info & __thiscall type_info::operator(class type_info const &)" (??4type_info@@AAEAAV0@ABV0@@Z) already defined in LIBCMT.lib(typinfo.obj)
msvcrt.lib(MSVCR120.dll) : error LNK2005: _memmove already defined in LIBCMT.lib (memmove.obj)
msvcrt.lib(MSVCR120.dll) : error LNK2005: __hypot already defined in LIBCMT.lib(hypot.obj)
msvcprt.lib(MSVCP120.dll) : error LNK2005: "void __cdecl std::_Xbad_alloc(void)" (?_Xbad_alloc@std@@YAXXZ) already defined in libcpmt.lib(xthrow.obj)
msvcprt.lib(MSVCP120.dll) : error LNK2005: "void __cdecl std::_Xlength_error(char const *)" (_Xlength_error@std@@YAXPBD@Z) already defined in libcpmt.lib(xthrow.obj)
msvcprt.lib(MSVCP120.dll) : error LNK2005: "void __cdecl std::_Xout_of_range(char const *)" (_Xout_of_range@std@@YAXPBD@Z) already defined in libcpmt.lib(xthrow.obj)
msvcprt.lib(MSVCP120.dll) : error LNK2005: "char const * __cdecl std::_Syserror_map(int)" (_Syserror_map@std@@YAPBDH@Z) already defined in libcpmt.lib(syserror.obj)
msvcprt.lib(MSVCP120.dll) : error LNK2005: "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z) already defined in libcpmt.lib(syserror.obj)
LIBCMT.lib(crt0init.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
..\..\bin\gammaray-launcher.exe : fatal error LNK1169: one or more multiply defined symbols found
LINK failed. with 1169
NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
```

Strangely enough when I generate VS2013 project files with CMake, there are no compilation errors.

**Comment by winterz** [comment]
We have gammaray master building ok with msvc2013 64 bit with Qt5.5.0

Are you using code from the master branch or from a zipball or?
also, are you using Qt5.5 Enterprise or hand-built Qt5.5 or from the opensource installer or?

ie. we need more info to try and find the combination that doesn't work for you.

**Comment by pnezis** [comment]
The code is from the master branch (`f6ef76fd7fec035111c205cd9c3df90c84b2acd8`). The Qt was installed using the open source installer. 

FYI I switched to the v2.3.0 tag (`921e1d0899ffbd40725a5d725fd7fef3b1817831`) and I managed to build GammaRay without issues

**Comment by rcmadruga** [comment]
I had the same problem with version 2.3.0, downloaded from releases page. Using Qt 5.5.0 from opensource offline installer Windows7 64bits.

I downloaded the master branch and build without issues.

**Comment by krf** [comment]
Assuming this got fixed in the meanwhile
