### ISSUE TITLE
Failed to make probe

### ISSUE THREAD

**Issue by Tianzh3n** [KDAB/GammaRay#1016]
<img width="543" alt="image" src="https://github.com/user-attachments/assets/da2916a9-1086-48a1-b66e-4dce4bd75cc1">

May I ask what causes this?

**Comment by Waqar144** [comment]
Missing libraries.

**Comment by Tianzh3n** [comment]
> Missing libraries.

I realized that Wayland is not supported on macOS. What should I do to address this issue?

**Comment by Waqar144** [comment]
ignore the warning? I guess we can silence it on irrelevant platforms
