### ISSUE TITLE
Can GammaRay be used to create APIs to query Qt GUI objects programmatically?

### ISSUE THREAD

**Issue by J-PREZORS** [KDAB/GammaRay#1018]
We have a Qt application running on a unix-like operating system.

We wish to be able to write test code (google test, pytest, etc.) that can programmatically query the Qt application GUI objects, 
e.g. get text from object, get object dimensions, etc.

It looks like GammaRay has both a GUI client and an "inject-only" mode.    So, not interested in having a GUI debugger window.

Can I use GammaRay to implement a C or C++ API that I can call from gtest code that gets passed in a Qt object name and can return the text characters displayed in the Qt GUI object?   

If so, any architecture suggestions or documentations links appreciated.

  mymodule.GetTextFromQtObject("someQtObjectname", & some-string-or-array)

I can query gdb with commands that can return objects, but I haven't seen any documentation where I can message the GammaRay task or provide command to return data.

**Comment by J-PREZORS** [comment]
Thanks for the response.   Your injector: is it hosted anywhere I can see like GitHub or can this be shared?   (shell)

**Comment by Guitronic** [comment]
I'm sorry but I work for a private company; however I can help you if you need.
I started from this cross Os injector on a public Git: "https://github.com/kubo/injector". You have an example of a library to compile, I added a QLocalServer in a QThread to communicate. As for Gammaray, you then have access to the QApplication of the remote program. You just have to call the "QApplication::allWidgets" function and you can do what you want.
However I see that you use Google test, if you just do unit tests you don't need an injector, the QTest API will be more than enough for you.

**Comment by Waqar144** [comment]
To answer your question, you can surely use the code in gammaray to implement such a thing. There is no out of the box support for it and there will likely never be. But imo it will be overkill. There are existing solutions that handle this for e.g., squish and others.

Gammaray covers a huge amount of qt libs and relies on a lot of qt private stuff and hacks to do what it does so its prone to crashes. Patches to improve the stability are welcome.
