### ISSUE TITLE
Statemachine visualizer doesn't color active state when runtime attaching

### ISSUE THREAD

**Issue by tmcguire** [KDAB/GammaRay#102]
When runtime attaching to a running application, the graph doesn't show the current state in red, even though the state treeview shows the state checked.
See attached screenshot.

![gammaray-bug](https://cloud.githubusercontent.com/assets/1164876/5469682/d4a1206a-85de-11e4-8b5d-fda84178f1d0.png)

**Comment by vkrause** [comment]
Kevin, this is fixed via KDSME nowadays, right?

**Comment by krf** [comment]
Should be, yes. Closing.
