### ISSUE TITLE
Attaching succeed without control panel shown up, but another gammaray instance can connect to the attached and show the panel.

### ISSUE THREAD

**Issue by neko-para** [KDAB/GammaRay#1022]
System: MacOS 14.5 Intel
Qt: 5.15.14 debug

The target program is inside the app bundle, but uses rpath to linking the external qt library that is the same as what used to build gammaray. Gammaray can successfully attach the program built with the same qt without bundle, and show the control panel.

Currently, I have to first attach the program, kill the gammaray, and reopen gammaray to connect to it, which is quite complicated. Is this a known issue about bundled app? Also, is there a way to combine gammaray inside the app that starts the server while program launched?

**Comment by Waqar144** [comment]
> Also, is there a way to combine gammaray inside the app that starts the server while program launched?

yes, see https://docs.kdab.com/gammaray-manual/latest/gammaray-advanced-usage.html

**Comment by neko-para** [comment]
> > Also, is there a way to combine gammaray inside the app that starts the server while program launched?
> 
> yes, see https://docs.kdab.com/gammaray-manual/latest/gammaray-advanced-usage.html

I've successfully connected to my program via dlopen calling `gammaray_probe_attach`, but it seems that some features are not available. I suspect that it is because of missing / failed loading those plugins (aka. those gammaray_xxx.so), but I do put them right beside the gammaray_probe_debug.dylib, according to the document. My program uses neither cmake nor qmake, thus I have to built the probe before.
