### ISSUE TITLE
Compilation fails using Visual Studio 2022 IDE

### ISSUE THREAD

**Issue by MatillaMartin** [KDAB/GammaRay#1024]
**Description**
Building GammaRay 3.1.0 using the Visual Studio 2022 IDE fails with
```
16>MSBuild version 17.8.3+195e7f5a3 for .NET Framework
16>MSBUILD : error MSB1009: Project file does not exist.
16>Switch: install
16>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'C:\Users\matilla\Downloads\gammaray-3.1.0\build\CMakeFiles\a233dcda01107be7f0a67104b8ccb19f\lib_package.rule;C:\Users\matilla\Downloads\gammaray-3.1.0\CMakeLists.txt' exited with code 1.
16>Done building project "lib_package.vcxproj" -- FAILED.
```

**Reproduction steps**
* Download 3.1.0 source
* Run default cmake generation
* Open Visual Studio 2022 IDE (Version 17.8.2), select Release
* Build all

Interestingly, when running the build from the CLI using the cmake commands, the build is successful
`cmake --build . --config Release --target install`

**Comment by Waqar144** [comment]
We dont provide support for building via IDEs.
