### ISSUE TITLE
Overlapping labels in statemachine visualizer

### ISSUE THREAD

**Issue by tmcguire** [KDAB/GammaRay#103]
When there is more than one transition between two states, the labels overlap and are unreadable.
See attached screenshot.

![gammaray-bug](https://cloud.githubusercontent.com/assets/1164876/5469698/09920d34-85df-11e4-988a-11c9897e47cc.png)

**Comment by krf** [comment]
Difficult to reproduce without proper example. Closing.

Also, the state chart layouting code changed completely.
