### ISSUE TITLE
Compiling Release win322 against qt 5.5.0 git fails in modeltest.cpp

### ISSUE THREAD

**Issue by rodion67** [KDAB/GammaRay#119]
Hi,
the problem is code like this:
#if !defined(NDEBUG)
        int state = checkStateVariant.toInt();
#endif
        Q_ASSERT ( state == Qt::Unchecked ||
                   state == Qt::PartiallyChecked ||
                   state == Qt::Checked );

as Q_ASSERT macro has been change so that the code in () is also compiled in release , but not active, will be removed by optimizer.
error message is tests/modeltest.cpp(498) : error C2065: 'state' : undeclared identifier
Solution is to change this like this:
#if !defined(NDEBUG)
        int state = checkStateVariant.toInt();
        Q_ASSERT ( state == Qt::Unchecked ||
                   state == Qt::PartiallyChecked ||
                   state == Qt::Checked );
#endif

Regards,
Gunnar

**Comment by vkrause** [comment]
Fixed in master.

**Comment by rodion67** [comment]
I have no clue how this change should fix the problem, that 
int state = checkStateVariant.toInt();
is only there if NDEBUG is not defined.
So in Release build (when NDEBUG is defined, at least on windows) i still have no variable state defined,
now the assert would assert in Release but it still would not compile as state variable is not defined.

Regards,
Gunnar

**Comment by vkrause** [comment]
2e623ed9964e493c5218c9591eab919bb642815a removes the #ifdef NDEBUG entirely, fixed the release build here. Sounds like you looked at the commit after that, which indeed just enables asserts and doesn't do anything to fix the build.

**Comment by rodion67** [comment]
well i just look at the commit a730d66 you have referenced this issue from, albeit there is no realtion. referencing this issue from 2e623ed would have been better and made it clear to me.
But never mind, i really appreciate your work on this great tool.

Regards,
Gunnar
