### ISSUE TITLE
Add cross-compile instructions

### ISSUE THREAD

**Issue by tmcguire** [KDAB/GammaRay#125]
There are no instructions how to cross-compile Gammaray for an embedded device, neither in the intall.txt, readme or on the wiki.

Cross-compiling for a device is non-trivial, as there needs to be a build for the target and for the host. Also, running Gammaray on the target require some undocumented command line options. So having some basic instructions would be very helpful.

**Comment by vkrause** [comment]
Added to the wiki https://github.com/KDAB/GammaRay/wiki/Cross-compiling-GammaRay , also referenced from install.txt.
