### ISSUE TITLE
Cant build for windows

### ISSUE THREAD

**Issue by grahamlabdon** [KDAB/GammaRay#127]
Hi
I am trying to build gamma ray for windows using the vs 2012 compiler and get the following error

CMake Error at C:\Program Files (x86)/VTK/CTKConfig.cmake:48 Include could not find load file:
C:\Vtk6.0.0/Cmake/vtkmaodeuleApi.cmake

Please could someone explain what I need to do in order to build gamma ray for windows

**Comment by krf** [comment]
You're aware that VTK is only a optional dependency? It's only used for visualizing the QObject tree in a 3D scene (not a super useful feature -- it's just there for the fun).

You could try building without VTK. Just don't pass VTK_DIR, etc.

**Comment by grahamlabdon** [comment]
Hi
Thanks for your reply

I am completely new to cmake
How do I try compiling without VTK

Thanks in advance

**Comment by krf** [comment]
It should be disabled by default. You're passing in VTK_DIR to CMake explicitly, don't you?

**Comment by grahamlabdon** [comment]
The steps taken are

Download gamma ray source
cd c:\gammarray
mkdir build
cmake –G “NMake Makefiles”

This gives me the error stated previously

I just noticed that it produces some log files which I have attached

Thanks again for your help

**Comment by krf** [comment]
Hm. So it is indeed auto-detected. Unfortunately there's no easy way to disable the VTK integration explicitly.

For the time being, patch the root CMakeLists.txt file:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c8fb13d..8cf46e1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -381,7 +381,7 @@ endif()
 find_path(VTK_DIR VTKConfig.cmake
   /usr/lib64/vtk /usr/lib/vtk /usr/local/lib64/vtk /usr/local/lib/vtk
 )
-find_package(VTK)
+#find_package(VTK)
 set_package_properties(VTK PROPERTIES
   TYPE OPTIONAL
   DESCRIPTION "Visualization Toolkit"
```

This should work

**Comment by grahamlabdon** [comment]
Hi
In the Install.txt it says I can disable VTK by building using the following command
cmake -G "NMake Makefiles" .. -DCMAKE_DISABLE_FIND_PACKAGE_VTK=True

when I try this I get

Found unsuitable Qt Version 5.4.1 from C:\Qt\Qt5.4.1\bin\qmake.exe, this code requires Qt 4.x

Yet the install.txt file says it should work with Qt5??

Thanks

**Comment by Sollex-21412** [comment]
Just add to CMakeLists.txt: 

set(Qt5Core_DIR "path-to-your-qt5-dir/cmake/Qt5Core")
set(Qt5_DIR "path-to-your-qt5-dir/cmake/Qt5")
set(QT_QMAKE_EXECUTABLE "path-to-your-qt5-dir/qmake.exe")

**Comment by winterz** [comment]
Graham,
Coincidentally, we have a similar bug report from Mac folks.
We are considering removing VTK dependency altogether since it provides a limited enhanced that's really not worth the effort.

that being said, commenting the 1-line for find_package(VTK) should have worked.  perhaps you need to trash your CMake cache.  or just remove the build directory and start over.

**Comment by krf** [comment]
@grahamlabdon: You don't need to patch the CMake file. Just run:

```
$ cmake -DCMAKE_PREFIX_PATH="path-to-your-qt5-dir/cmake/"
```

Closing this; it's a user setup issue.
