### ISSUE TITLE
GammaRay shows overlay next to widget content instead of overlaid

### ISSUE THREAD

**Issue by tfar** [KDAB/GammaRay#130]
Tested with GammaRay master and Qt 5.5.
![Screenshot showing issue](https://dl.dropboxusercontent.com/u/14672346/tmp/Screenshot%202015-06-01%2019.23.54.png)

**Comment by krf** [comment]
Same issue, probably: https://github.com/KDAB/GammaRay/issues/105

Can you try the attached patch?

Closing this; assuming a duplicate.
