### ISSUE TITLE
Install instructions should mention -developer-build flag requirement

### ISSUE THREAD

**Issue by assumptionsoup** [KDAB/GammaRay#132]
The install instructions mention that "to build against private Qt headers (necessary for painter debugging/profiling) you must have a build version of Qt available."  It was not immediately clear to me that this meant I needed to compile qt with the `-developer-build` flag enabled.  I only figured this out via [this archived mailing list](https://mail.kdab.com/pipermail/gammaray-interest/2013-October/000100.html).  Like the final message in that mailing list suggests, it would be very helpful if this was explicitly spelled out in the install instructions.

**Comment by winterz** [comment]
done. see Install.txt.

**Comment by assumptionsoup** [comment]
Sweet, thanks.
