### ISSUE TITLE
Enum values not displayed correctly in GammaRay

### ISSUE THREAD

**Issue by hcw70** [KDAB/GammaRay#134]
When displaying an enum property of an object with a registered enum type (so value -> text translations are shown), the enum values are created as if the enum was of Q_FLAG kind, althhoug it is not.

So an enum 
> typedef enum { 
>    Zero = 0,
>   One,
>   Two,
>   Three } MyEnumVal;

when set to value "Three" = 3 is displayed in Gammaray as having value "One|Two|Three".

Tested with  git version b61e16cb of gammaray

**Comment by krf** [comment]
@hcw70: Still a problem? Please check.

**Comment by hcw70** [comment]
Is resolved.
