### ISSUE TITLE
GammaRay crashes when trying to debug krita

### ISSUE THREAD

**Issue by Amadiro** [KDAB/GammaRay#138]
Hello,
when attempting to debug krita (a painting application from the calligra suite) with gammaray, gammaray and krita hang indefinitely, using 100% CPU.

Steps to reproduce:
- Install or compile krita 2.9.5 (unknown whether the issue occurs with older versions)
- start gammaray and launch krita from it, with Access mode set to "in-process"
- everything works, widgets can be inspected, et cetera.
- create a new document in krita, 10px by 10px
- gammaray & krita both become unresponsive

When using the "Out-of-process, local only" access mode, only krita hangs, the gammaray UI remains responsive (but will not perform any actual actions anymore, such as quitting). Attempting to detach from the process in this case does not seem to do anything.

The hang is reproducible whether OpenGL is enabled or not in krita.

Unfortunately I don't have the necessary experience with Qt to debug the issue myself, but I'd be happy to provide any further details that might be helpful.

**Comment by milianw** [comment]
Before we have time to investigate, could you attach a debugger and get a backtrace? I.e. reproduce the hang as you explained above, then - from any other terminal - execute the following commands:

    gdb --pid $(pidof krita)
    # wait for it to attach...
    (gdb) thread apply all bt
    # paste the output of the above gdb command somewhere
    (gdb) cont
    # wait for some seconds, then press CTRL + C and repeat
    (gdb) thread apply all bt
    # paste the output, or check whether its equivalent to the above
    (gdb) quit

This would allow us to potentially find a fault without having to the procedure on our own.

Thanks!

**Comment by Smjert** [comment]
Since i have the same issue, here is my backtrace (i'm using gammaray 2.1.0): http://pastie.org/10267779

The backtrace is always the same.

**Comment by akreuzkamp** [comment]
You have a loop in your object tree, that's what is confusing GammaRay.

It's some KoParagraphStyle object, who's parent is a KoStyleManager, who's parent is just that KoParagraphStyle.

We should be able to detect that, so your report is valid and helpful, thanks :)
But you should fix that loop, nevertheless ;)

**Comment by Amadiro** [comment]
@akreuzkamp thanks for the insight! I will file a bug in the krita bugtracker for this issue.

**Comment by krf** [comment]
FTR, fix at https://github.com/KDAB/GammaRay/pull/140 -- please check if that fixes the issue for you.

**Comment by vkrause** [comment]
Fix got integrated into master.

**Comment by Amadiro** [comment]
Everything seems to work great! Thanks a lot for fixing this bug so promptly, and thanks for making such an amazing software!
