### ISSUE TITLE
Cannot install on OSX, Qt5.5

### ISSUE THREAD

**Issue by marco-piccolino** [KDAB/GammaRay#149]
If I try and run cmake I get the following:

    Found unsuitable Qt version "5.5.0" from /Users/marco_piccolino/bin/qmake,
    this code requires Qt 4.x

**Comment by winterz** [comment]
which version of gammaray?

For the master branch you should be able to run
mkdir build; cd build; PATH=/Users/marco_piccolino/bin:$PATH cmake ..

**Comment by marco-piccolino** [comment]
Allen, thanks for the feedback.
It's the latest master, and the path to qmake is correct.
Does anything else come to mind?

**Comment by winterz** [comment]
certainly not the best error message .. but something about your Qt5.5 install is broken so it tries to use Qt4 and can't find that.

I am sure the master branch builds ok with Qt5.5.0 on OSX

**Comment by marco-piccolino** [comment]
OK. I'll check my environment then.
Thank you for the support.
Marco
Il 19/set/2015 04:54 PM, "Allen Winter" <notifications@github.com> ha
scritto:

**Comment by krf** [comment]
Likely a local setup issue, closing
