### ISSUE TITLE
Can't build using buildroot without GUI

### ISSUE THREAD

**Issue by Yellowmat** [KDAB/GammaRay#157]
Hi,

I'm trying to build gammaray for an embedded target using buildroot.

I'm passing the following options to cmake
DCMAKE_DISABLE_FIND_PACKAGE_Graphviz=true
DCMAKE_DISABLE_FIND_PACKAGE_VTK=true
DGAMMARAY_BUILD_UI=false

But I still have the following problem :
Could not find a package configuration file provided by "Qt5Gui" with any of the following names:
    Qt5GuiConfig.cmake
    qt5gui-config.cmake

Add the installation prefix of "Qt5Gui" to CMAKE_PREFIX_PATH or set "Qt5Gui_DIR" to a directory containing one of the above files.  If "Qt5Gui" provides a separate development package or SDK, be sure it has been installed.

**Comment by Yellowmat** [comment]
Still doesn't build for me.

Here are some more informations

(cd /home/me//build/gammaray-2.3.0/ && rm -f CMakeCache.txt && PATH="/home/me/host/bin:/home/me/host/sbin:/home/me/host/usr/bin:/home/me/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"  /home/me/host/usr/bin/cmake /home/me/build/gammaray-2.3.0/ -DCMAKE_TOOLCHAIN_FILE="/home/me/host/usr/share/buildroot/toolchainfile.cmake" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_COLOR_MAKEFILE=OFF -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DUSE_CCACHE=ON -DCMAKE_DISABLE_FIND_PACKAGE_Graphviz=true -DCMAKE_DISABLE_FIND_PACKAGE_VTK=true -DGAMMARAY_BUILD_UI=false )
Re-run cmake no build system arguments
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /home/me/host/usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /home/me/host/usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/me/host/usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /home/me/dos/paco/host/usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building GammaRay 2.3.0 in Debug mode
-- Performing Test HAVE_GXX_UNUSED_BUT_SET
-- Performing Test HAVE_GXX_UNUSED_BUT_SET - Success
-- Performing Test HAVE_GXX_LOGICAL_OP
-- Performing Test HAVE_GXX_LOGICAL_OP - Success
-- Performing Test HAVE_GXX_POINTER_MEMACCESS
-- Performing Test HAVE_GXX_POINTER_MEMACCESS - Success
-- Performing Test HAVE_GXX_REORDER
-- Performing Test HAVE_GXX_REORDER - Success
-- Performing Test HAVE_GXX_FORMAT_SECURITY
-- Performing Test HAVE_GXX_FORMAT_SECURITY - Success
-- Performing Test HAVE_GXX_GNUXX11
-- Performing Test HAVE_GXX_GNUXX11 - Success
-- Performing Test HAVE_GXX_CXX11
-- Performing Test HAVE_GXX_CXX11 - Success
CMake Error at /home/me/host/usr/share/cmake-3.3/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.2.1" from /usr/bin/qmake, this code requires
  Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:295 (find_package)


Hope this can help.

Thanks in advance for your help.

**Comment by vkrause** [comment]
Even in its minimal configuration the GammaRay probe needs Qt5Gui. It does work on targets only using Qt5Core nevertheless, it's only needed for its internal use.

This can be changed, same as we did with removing the widget dependency, but it's a major refactoring job I'm afraid.

**Comment by krf** [comment]
@Yellowmat: This indicates a different issue:
```
CMake Error at /home/me/host/usr/share/cmake-3.3/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.2.1" from /usr/bin/qmake, this code requires
  Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:295 (find_package)
```

I think the original request "build without (Qt5) GUI" as I understood is a WONTFIX -- to much effort for little gain. 

Also see Volker's last comment.
