### ISSUE TITLE
Windows/OSX: Cannot link against GammaRay libs in debug mode

### ISSUE THREAD

**Issue by e4z9** [KDAB/GammaRay#162]
Building an application against the GammaRay Qt module on Windows or OS X is not possible in debug mode, because the .lib and .dll files miss the `d` (on OS X `_debug`) postfix

**Comment by vkrause** [comment]
I'd appreciate feedback/test results if you have an affected setup already, will take me some time to verify the fix on all platforms.

**Comment by e4z9** [comment]
Looks good. Proposed fix builds & runs on OS X in debug mode, and the font browser works as well, so if I understand it correctly the plugins are found and loaded as well.
Looks like it should work on Windows too, but I can only test that on monday if you want.

**Comment by vkrause** [comment]
Excellent, it works with a MSVC2013 debug build here, I didn't get to test OSX yet, I'll integrate it.
