### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by tim2000** [KDAB/GammaRay#164]
Failed on : Linux version 2.6.32-573.8.1.el6.i686 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Nov 10 14:58:44 UTC 2015

See the full build log.
[GammaRayBuildFailed.txt](https://github.com/KDAB/GammaRay/files/74761/GammaRayBuildFailed.txt)

**Comment by vkrause** [comment]
Weird, looks like a mix of Qt4 and Qt5 headers being used. Where is your Qt5 installed? What arguments did you pass to CMake?

**Comment by tim2000** [comment]
cmake .. -DCMAKE_BUILD_TYPE=Debug

Qt5 install : /usr/local/lib
Qr4 install : /usr/lib

**Comment by krf** [comment]
This is an environment setup issue. If you want to build against Qt5, make sure */usr/local/bin* is first in PATH, if you want to build against prepend */usr/bin*.

You might need to pass `-DGAMMARAY_ENFORCE_QT4_BUILD=ON` to cmake if you want a Qt4 build.

**Comment by Birky** [comment]
Hey tim2000, I had the same error and the solution is pretty simple. You need to set the VTK_QT_VERSION from 4 to 5 :)
