### ISSUE TITLE
Please consider signing your release tarballs using a GPG key

### ISSUE THREAD

**Issue by xhaakon** [KDAB/GammaRay#165]
This way, downstream distribution package maintainers can verify if they actually downloaded the same tarball you have released and the source code hasn't been tampered with.

You may follow [a simple how-to](https://wiki.debian.org/Creating%20signed%20GitHub%20releases).

**Comment by krf** [comment]
@winterz Something for you?

**Comment by winterz** [comment]
yes, I do that now and have been for quite a while
for example see https://github.com/KDAB/GammaRay/releases/tag/v2.11.3 and the attached assets have .asc files
