### ISSUE TITLE
Where is the gammaray binary in the Fedora 20 package?

### ISSUE THREAD

**Issue by vickychijwani** [KDAB/GammaRay#167]
Hi, I downloaded all the rpms from http://download.opensuse.org/repositories/isv:/KDAB/Fedora_20/x86_64/ and extracted them with `for file in *.rpm; do rpm2cpio $file | cpio -idv; done`. I got a single `usr/` directory, but there doesn't seem to be any binary called `gammaray` inside it.

```
$ ll ./usr/bin
total 2.1M
-rwxr-xr-x 1 vchijwani infra 1.2M Jan 12 16:22 charmtimetracker
-rwxr-xr-x 1 vchijwani infra 896K Jan 12 16:23 kdwsdl2cpp
```

I'm probably making a stupid mistake somewhere, but is it possible the Fedora 20 packages are incomplete? Could someone help me figure this out?

**Comment by winterz** [comment]
there is no Fedora20 rpm for GammaRay as created by KDAB.
you'll need to look elsewhere.

Fedora21 and above have rpms since they have Qt5.
GammaRay can build with Qt4 but we don't support that.

**Comment by vickychijwani** [comment]
I see. I do have Qt5 on my Fedora 20 machine, installed separately. Looks like I'll need to compile against it myself. Thanks for the info!
