### ISSUE TITLE
GammaRay build with Visual Studio uses cygwin ld.exe

### ISSUE THREAD

**Issue by rlskinner** [KDAB/GammaRay#188]
I'm trying to build GammaRay on Windows with Visual Studio.

I set my path to contain CMake\bin and my Qt bin:
    % set PATH="c:\Program Files (x86)\CMake\bin";%PATH%
    % set PATH=c:\dev\Qt\4.8.2-x64\bin;%PATH%

and build forcing Qt 4:
    % cmake -G "NMake Makefiles"  -DGAMMARAY_ENFORCE_QT4_BUILD=true ..

Then the compiler test fails.  It appears to compile correctly, but then tries to link with cygwin ld.exe, is that correct?

-- The C compiler identification is MSVC 16.0.40219.1
-- The CXX compiler identification is MSVC 16.0.40219.1
-- Check for working C compiler: C:/VisualStudio2010/VC/bin/cl.exe
-- Check for working C compiler: C:/VisualStudio2010/VC/bin/cl.exe -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61
(message):
  The C compiler "C:/VisualStudio2010/VC/bin/cl.exe" is not able to compile a
  simple test program.

  It fails with the following output:

   Change Dir: C:/Dev/Qt/GammaRay-2.1.0/build/CMakeFiles/CMakeTmp

  Run Build Command:"nmake" "/NOLOGO" "cmTC_fe452\fast"

        c:\VisualStudio2010\VC\BIN\nmake.exe -f
  CMakeFiles\cmTC_fe452.dir\build.make /nologo -L
  CMakeFiles\cmTC_fe452.dir\build

  Building C object CMakeFiles/cmTC_fe452.dir/testCCompiler.c.obj

        C:\VisualStudio2010\VC\bin\cl.exe @c:\tmp\nm3F57.tmp

  testCCompiler.c

  Linking C executable cmTC_fe452.exe

        "C:\Program Files (x86)\CMake\bin\cmake.exe" -E vs_link_exe
  --intdir=CMakeFiles\cmTC_fe452.dir --manifests -- C:\cygwin\bin\ld.exe
  /nologo @CMakeFiles\cmTC_fe452.dir\objects1.rsp @c:\tmp\nm4080.tmp

  /usr/bin/ld: cannot find /nologo: No such file or directory

  /usr/bin/ld: cannot find /out:cmTC_fe452.exe: No such file or directory

  /usr/bin/ld: cannot find /implib:cmTC_fe452.lib: No such file or directory

  /usr/bin/ld: cannot find
  /pdb:C:\Dev\Qt\GammaRay-2.1.0\build\CMakeFiles\CMakeTmp\cmTC_fe452.pdb: No
  such file or directory

  /usr/bin/ld: cannot find /version:0.0: No such file or directory

  /usr/bin/ld: cannot find /machine:X86: No such file or directory

  /usr/bin/ld: cannot find /debug: No such file or directory

  /usr/bin/ld: cannot find /INCREMENTAL: No such file or directory

  /usr/bin/ld: cannot find /subsystem:console: No such file or directory

  /usr/bin/ld: cannot find kernel32.lib: No such file or directory

  /usr/bin/ld: cannot find user32.lib: No such file or directory

  /usr/bin/ld: cannot find gdi32.lib: No such file or directory

  /usr/bin/ld: cannot find winspool.lib: No such file or directory

  /usr/bin/ld: cannot find shell32.lib: No such file or directory

  /usr/bin/ld: cannot find ole32.lib: No such file or directory

  /usr/bin/ld: cannot find oleaut32.lib: No such file or directory

  /usr/bin/ld: cannot find uuid.lib: No such file or directory

  /usr/bin/ld: cannot find comdlg32.lib: No such file or directory

  /usr/bin/ld: cannot find advapi32.lib: No such file or directory

  /usr/bin/ld: cannot find /MANIFEST: No such file or directory

  /usr/bin/ld: cannot find
  /MANIFESTFILE:CMakeFiles\cmTC_fe452.dir/intermediate.manifest: No such file
  or directory

  CMakeFiles\cmTC_fe452.dir/manifest.res: file not recognized: File format
  not recognized

  LINK Pass 1 failed.  with 1

  NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake\bin\cmake.exe"' :
  return code '0xffffffff'

  Stop.

  NMAKE : fatal error U1077: 'c:\VisualStudio2010\VC\BIN\nmake.exe' : return
  code '0x2'

  Stop.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:25 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Dev/Qt/GammaRay-2.1.0/build/CMakeFiles/CMakeOutput.log".
See also "C:/Dev/Qt/GammaRay-2.1.0/build/CMakeFiles/CMakeError.log".

Thanks,
Robert

**Comment by krf** [comment]
You need to run CMake from within the VS2010 command prompt. Note that cl.exe is already broken for you, your output contains:
``` 
C:/VisualStudio2010/VC/bin/cl.exe -- broken
```

This appears to be a setup issue.

Also see: https://msdn.microsoft.com/en-us/library/f2ccy3wt.aspx
