### ISSUE TITLE
Binaries no using Qt5

### ISSUE THREAD

**Issue by suy** [KDAB/GammaRay#194]
Hi.

Trying to use the GammaRay binaries provided through the OBS, I've found that those are linking against Qt4, and that there is no Qt5 probe. This doesn't seem the intended.

I have checked the packaging files, and I'm not sure if the Build-Depends lines are right. I don't know much about OBS, but in normal packaging the Build-Depends should be in debian/control.

Thank you.

**Comment by winterz** [comment]
the gammaray package should give you a Qt5 version with a Qt5 probe.
if you want the Qt4 probe, install gammaray-qt4

I verified this is true for Fedora OBS packages at least.

can you tell me how you are getting your packages?

**Comment by suy** [comment]
I'm getting the ones for Ubuntu from OBS, using the provided instructions in the page. I can try on Debian as well, if needed, but I see the same issue (same debian.* source files for the build).

Sorry, I should have said that more clearly. I thought the "debian" mention would be enough. :)

**Comment by winterz** [comment]
https://build.opensuse.org/package/live_build_log/isv:KDAB/GammaRay/xUbuntu_14.10/x86_64 shows the build log for GammaRay for Ubuntu 14.10.  you can see it is building against the Qt5 libs.
I'm at a loss to explain the problem.

**Comment by winterz** [comment]
I'll force a rebuild and see if that helps

**Comment by winterz** [comment]
https://build.opensuse.org/package/binaries/isv:KDAB/GammaRay?repository=xUbuntu_14.10 has the debs

**Comment by winterz** [comment]
how old Ubuntu are you using?  we no longer support any versoin less than 14.10

**Comment by suy** [comment]
The exact opposite: I'm in the newest one, which oddly is using Qt4 instead: http://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_15.10/gammaray_2.4.1.dsc

I've picked up that because [in the overview page](https://software.opensuse.org/download.html?project=isv:KDAB&package=gammaray) that's available, and it's the exact version I'm using. I'll try the old version in a (hopefully short) while.

**Comment by suy** [comment]
Well, the OBS is certainly confusing me. [Their page lists Qt5 as requirements](https://build.opensuse.org/package/binary/isv:KDAB/GammaRay?arch=x86_64&filename=gammaray_2.4.1_amd64.deb&repository=xUbuntu_14.10), but I've downloaded that .deb file, extracted it, and run ldd and objdump, and the libraries are Qt4 for sure. That is coherent with what I saw in the package manager, since [the metadata for the binaries](http://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_14.10/Packages) also has Qt4 dependencies.

I would try moving the `Build-Depends` line to debian.control. In normal debian packaging that's where it should be, so I'd assume is the same for the OBS.

**Comment by krf** [comment]
@winterz: What's the status herE?

**Comment by krf** [comment]
Just checked myself: Installed the OBS version on my Ubuntu 15.10 box. It indeed depends and links against Qt4. So this bug report is indeed valid.

http://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_15.10/Packages appears out of date (says gammaray needs libqt4). Needs to be fixed at OBS-level I think.

**Comment by suy** [comment]
Sorry, I would have liked to submit a patch (mostly, because to try it, I assume that I would need to setup some OBS account, check their docs, and I currently don't have time for it), but I *think* that the only fix needed is put the Build-Depends line in `debian.control`. Right now is in `gammaray.dsc`. If I remember correctly, In normal Debian packaging, that's the file where you put the package metadata, and the `dsc` file is generated.

**Comment by winterz** [comment]
I added a Build-Depends: debhelper (>= 4.1.16), cdbs, cmake, qt5-default, qtbase5-private-dev, qtdeclarative5-dev, qtdeclarative5-private-dev, qtscript5-dev, qttools5-dev, libqt5svg5-dev, libqt5webkit5-dev, graphviz-dev, kdstatemachineeditor

to debian.control.

does it help at all?
you might need to wait a few hours for the new packages to show up.

**Comment by suy** [comment]
I've looked at the corresponding Packages files ([15.10](http://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_15.10/Packages), [15.04](http://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_15.04/Packages), [14.10](http://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_14.10/Packages), [14.04](http://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_14.04/Packages)). All are using Qt4 except 14.04, which is GammaRay 2.3.0 and it's compiled against Qt5. Thanks for the try. I'll see if I can find more information later.

**Comment by winterz** [comment]
think I found it.
can you try now?

**Comment by winterz** [comment]
@krf reports it works for him.

**Comment by suy** [comment]
I don't have the Ubuntu PC to test, but all Packages files look correct now. Thanks!

**Comment by suy** [comment]
Well, it definitely worked for me as well. :heart: @winterz!! :) What was the problem? I saw 681d28294d70bddb1dbc48f084a02a838ae81f94. Has any relation?

**Comment by winterz** [comment]
yes.  the gammaray-qt4 debian.control file was also using the Package name of "gammaray".  so I had two projects generating the same package.
