### ISSUE TITLE
Build on Mac OS fails because it's looking for Qt4

### ISSUE THREAD

**Issue by dberickson** [KDAB/GammaRay#197]
I have followed the instructions for building on Unix found in the install.txt file and have gotten the latest code from GIT. CMake fails because it says it can't find Qt4:

_"CMake Error at /Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x"_

I am not specifying the option for Qt4 (-DGAMMARAY_ENFORCE_QT4_BUILD=true) and do not have Qt4 installed. I have only one environment variable related to Qt (QTDIR) and it's set to point to my Qt5.6 installation.

Any ideas on why it's still looking for Qt4?

**Comment by winterz** [comment]
yeah, this is a bad error message.
I think it looks for Qt5 first. if it can't find Qt5 it looks for Qt4.
if it can't find Qt4 it prints that message.

If you want to build with Qt5, then please make sure the qmake for Qt5 is in your $PATH.
make sure `which qmake` points to the Qt versio you want.

**Comment by dberickson** [comment]
That did it. My PATH was pointing to an old version of Qt. I forget that Macs (and maybe Unix) have two ways to set paths, one for application and one for command line. I had only changed the application path.
