### ISSUE TITLE
qmlcontextpropertyadaptor won't build against Qt 5.5.0

### ISSUE THREAD

**Issue by wttw** [KDAB/GammaRay#200]
Build fails with:

.../GammaRay/plugins/qmlsupport/qmlcontextpropertyadaptor.cpp:96:29: error: type 'QV4::IdentifierHash<int>' does not provide a call operator
    const auto &propNames = contextData->propertyNames();
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~

doSetObject() is conditionally compiled only against Qt versions >= 5.5.0.

In 5.5.0 QQmlContextData::propertyNames is a class member, while in 5.5.1 and higher it's a getter function.

The simple fix is to change the version check to #if QT_VERSION >= QT_VERSION_CHECK(5, 5, 1), but it might be possible to conditionally use the member or the getter function so as to support 5.5.0.

**Comment by krf** [comment]
Uhm, are you sure?

```
% git show v5.5.0:src/qml/qml/qqmlcontext_p.h | grep propertyNames
    QV4::IdentifierHash<int> &propertyNames() const;
% git show v5.5.1:src/qml/qml/qqmlcontext_p.h | grep propertyNames
    QV4::IdentifierHash<int> &propertyNames() const;
```

**Comment by wttw** [comment]
You're right. Apparently this Qt installation that identifies as 5.5.0 isn't *quite* 5.5.0.

Sorry about that.
