### ISSUE TITLE
Does GammaRay work with Qt 5.6?

### ISSUE THREAD

**Issue by akontsevich** [KDAB/GammaRay#202]
Worked for me with Qt 5.5.1, now fails with Qt 5.6. GammaRay and my app was built with same Qt and compiler versions: 

```
Starting D:\Salford\GitHub\GammaRay\build\bin\gammaray.exe...
Detected ABI qt5_6-MSVC-x86_64d, using ABI qt5_6-MSVC-x86_64d.
Target not responding - timeout.
See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting
D:\Salford\GitHub\GammaRay\build\bin\gammaray.exe exited with code 1

Starting D:\Salford\GitHub\GammaRay\build\bin\gammaray-launcher.exe...
QObject::connect: Connecting from COMPAT signal (QProcess::error(QProcess::ProcessError))
D:\Salford\GitHub\GammaRay\build\bin\gammaray-launcher.exe exited with code 0
```

**Comment by akontsevich** [comment]
Just tried with Qt 5.5.1 - same thing: Target not responding - timeout. So problem not in Qt version - same bug as mentioned here: https://github.com/KDAB/GammaRay/issues/166 Strange it worked before. Any way to resolve? Will try 32 bit as well.

**Comment by akontsevich** [comment]
Rebuild with today's changes: works with Qt 5.6 with "in-process" option with simple application, still fails on big complex - worked previously. Application started, but no gammaray GUI.

**Comment by krf** [comment]
Please continue discussion in #166 then. Thanks.
