### ISSUE TITLE
How to pass a different Qt installation path to cmake?

### ISSUE THREAD

**Issue by sinadogru** [KDAB/GammaRay#213]
Cmake uses default system Qt installation path which is in my case /usr/include/qt5, but I have also have a recent version on my home directory. So I would like to pass this, and tried `-DCMAKE_PREFIX_PATH=/home/cavit/Qt/5.6` but it didn't helped, build still uses /usr/include/qt5. So this lack of private headers, so compilation also fails.

Since those headers for 5.5.1 and I would like to have 5.6 build and also because of this compilation failures, can you please helped me to specify the qmake?

Thank you,
Sina

**Comment by akontsevich** [comment]
Put following lines into CMakeLists.txt:

```
set(Qt5Core_DIR "C:/Qt/5.6/msvc2013_64/lib/cmake/Qt5Core")
set(Qt5_DIR "C:/Qt/5.6/msvc2013_64/lib/cmake/Qt5")
set(QT_QMAKE_EXECUTABLE "C:/Qt/5.6/msvc2013_64/bin/qmake.exe")
```

**Comment by krf** [comment]
@sinadogru:

Two things:
* Make sure to clear the build directory before changing `CMAKE_PREFIX_PATH`
* Are you sure there's a *lib/cmake* folder inside */home/cavit/Qt/5.6*? (That's where CMake finds the Qt5 config files)

**Comment by krf** [comment]
@akontsevich: You don't need to modify CMakeLists.txt, passing (the correct) `CMAKE_PREFIX_PATH` is sufficient

**Comment by sinadogru** [comment]
@krf 

I was giving the root of the Qt installation as a `CMAKE_PREFIX_PATH`.

Thank you for pointing out it needs to be cmake folder.

**Comment by Cashews54** [comment]
For reference, I fixed this same issue by instead changing my `~/.profile` file to include: `export PATH="$HOME/Qt5.6.1/5.6/gcc_64/lib/cmake:$PATH"`.  

Then I ran `source ~/.profile` and did a clean build.  I didn't have to change my `CMAKE_PREFIX_PATH` or edit any cmake files.

**Comment by ryancheung** [comment]
For ubuntu: `cmake -DCMAKE_PREFIX_PATH=$HOME/Qt/5.11.2/gcc_64 ..`

**Comment by krf** [comment]
@Cashews54 This works because CMake uses lots of heuristics to detect packages (cf. "installation prefixes" in https://cmake.org/cmake/help/v3.8/command/find_package.html); but the canonical way to tell CMake where to look for package is to set `CMAKE_PREFIX_PATH`.

Also documented here: http://doc.qt.io/qt-5/cmake-manual.html

**Comment by ninovanhooff** [comment]
This should really be documented IMHO

https://github.com/KDAB/GammaRay/pull/577
