### ISSUE TITLE
Geometry preview not always displaying something

### ISSUE THREAD

**Issue by tmcguire** [KDAB/GammaRay#225]
Quick Scenes->Scene Graph->Geometry->Preview is sometimes empty and doesn't show any triangles.

To reproduce, start "gammaray qmlscene test.qml" with the following QML file:

```
import QtQuick 2.0

Text {
  text: "Hello World"
}
```

Then click: Quick Scenes->QQuick/Text->Scene Graph->Geometry Node->Geometry
The preview will be empty.
After clicking on another node and back on the geometry node, the preview appears.

Having this working reliable would be nice, I use this feature to demonstrate that QtQuick uses triangles for rendering in trainings.

Version: Gammaray master (v2.4.1-587-g6f26f6e), Qt 5.5

**Comment by vkrause** [comment]
Yep, seen the same here, the very first selection of a geometry node will not show the geometry.

**Comment by krf** [comment]
@akreuzkamp Fixed by #234?

**Comment by vkrause** [comment]
Yep, #234 fixed this.
