### ISSUE TITLE
GammaRay Is stuck at this window

### ISSUE THREAD

**Issue by rekane88** [KDAB/GammaRay#227]
Hey guys! I'm trying to use GammaRay on this application, however when I target it with the GammaRay Client, Its just stuck on this screen. I built gammaray with the exact same build config as the application. 

![266ce8e0c12a4c8298ee0566838b3bed](https://cloud.githubusercontent.com/assets/13768027/16028978/d14ce9fe-31b2-11e6-9ddf-e0e02f20ce77.png)

**Comment by rekane88** [comment]
The application I'm trying to inspect is here. 

https://s3.amazonaws.com/setup.roblox.com/RobloxStudioLauncherBeta.exe

**Comment by krf** [comment]
Is this solved? The other issue report #228 indicates you got it working?

**Comment by rekane88** [comment]
Yep!

**Comment by rekane88** [comment]
But now it crashes.

**Comment by krf** [comment]
Okay, follow-up issue is in #228. Let's close this.
