### ISSUE TITLE
Gammaray causes application to crash

### ISSUE THREAD

**Issue by rekane88** [KDAB/GammaRay#228]
Hi, when I GammaRay inject it's DLL into the application it causes to the program to crash
![5d033ea26e3841f79173ee7ca2d70006](https://cloud.githubusercontent.com/assets/13768027/16063500/b35d53b0-3267-11e6-9bb5-ee948a690025.png)
.

**Comment by milianw** [comment]
We need either a way to reproduce this, or we need a full backtrace, e.g. from within the Visual Studio debugger. Without this information, the report here is useless, I'm afraid to say.

**Comment by rekane88** [comment]
I can upload the windows binaries if you'd like?

**Comment by rekane88** [comment]
The binaries for the application is here 
https://s3.amazonaws.com/setup.roblox.com/RobloxStudioLauncherBeta.exe

**Comment by krf** [comment]
@rekane88: This needs way more information. How did you build GammaRay? Have the executable & GammaRay been build with the same Qt version? Etc.

Please check.

**Comment by rekane88** [comment]
Yes they have, I built it using the VS command line. 

I'm using windows. The qt version was 4.8

**Comment by krf** [comment]
We need a backtrace for this, we can't reproduce with the binaries only. Please try to get one (using the VC debugger, or userdump.exe).
