### ISSUE TITLE
attachtest-lldb: fails on macOS

### ISSUE THREAD

**Issue by ilovezfs** [KDAB/GammaRay#241]
The `attachtest-lldb` run during `make check` fails on macOS (Homebrew tests on 10.9, 10.10, and 10.11, and all 3 failed):

```
 3/27 Test  #3: connectiontest-lldb ..............   Passed   12.13 sec
      Start  4: attachtest-gdb
 4/27 Test  #4: attachtest-gdb ...................   Passed    0.18 sec
      Start  5: attachtest-lldb
 5/27 Test  #5: attachtest-lldb ..................***Exception: Other 61.73 sec
      Start  6: multisignalmappertest
 6/27 Test  #6: multisignalmappertest ............   Passed    0.17 sec
      Start  7: sourcelocationtest
```

This is a regression that comes from https://github.com/KDAB/GammaRay/commit/fdf0da8010620574b8c18cc582a51656180a4fcb, where the lldb test was introduced. As a workaround, we're skipping the test during CI for Homebrew so that we can still run `make check`.

**Comment by krf** [comment]
Needs more information:
- Qt version?
- GammaRay version?

Please run `ctest --output-on-failure` instead of `make check` so we get more debugging output.

**Comment by ilovezfs** [comment]
Qt5, 2.5.1. I'll try to get you ctest output too.

**Comment by krf** [comment]
Bump?

**Comment by krf** [comment]
Closing due to lack of feedback

**Comment by ilovezfs** [comment]
Are you unable to test this yourself?

**Comment by krf** [comment]
@ilovezfs We build lots of configurations of GammaRay on CI, also targeting OS X. The unit test works fine for us.

Thus we need to the verbose `ctest` output from you in order to figure out what's wrong on your machine.

**Comment by ilovezfs** [comment]
do you run your tests in a sandbox ...
