### ISSUE TITLE
Please use HTTPS URL in description

### ISSUE THREAD

**Issue by paulmenzel** [KDAB/GammaRay#247]
The current description shown at https://github.com/KDAB/GammaRay is

> GammaRay is a tool to poke around in a Qt-application and also to manipulate the application to some extent. http://www.kdab.com/gammaray

PS: You should fix the mixed-content loading error first though with the Web site.

**Comment by winterz** [comment]
I fixed the description to say "... https://www.kdab.com/gammaray"

I don't understand what you mean in the PS.  can you provide more details?

**Comment by paulmenzel** [comment]
Accessing the KDAP Web site using HTTPS, an exclamation mark is added to the “HTTPS lock” in the URL bar. The developer tools show, that some URLs still use HTTP instead of HTTPS (mixed-content loading).

![20160902 gammaray https issues](https://cloud.githubusercontent.com/assets/9318792/18189442/3c555136-70bb-11e6-86ed-8f5a0029f02e.png)

(The other errors should probably also be fixed, but are unrelated to HTTPS.)

**Comment by winterz** [comment]
forwarded to our web dev team

**Comment by winterz** [comment]
the webmaster says "the issues will be fixed on the new website that is coming online shortly. thanks for reporting."

**Comment by krf** [comment]
This is fixed.
