### ISSUE TITLE
QT5 fails to compile if kde not installed

### ISSUE THREAD

**Issue by HenryMiller1** [KDAB/GammaRay#249]
I'm trying to cross compile 2.5.1 for an embedded system where we do not have/use KDE libraries.  We have QT5 only in this environment. The build fails with:

```
common/CMakeFiles/gammaray_common.dir/objectbroker.cpp.o: In function `GammaRay::ObjectBroker::selectionModel(QAbstractItemModel*)':
/home/.../gammaray/src/common/objectbroker.cpp:198: undefined reference to `KLinkItemSelectionModel::KLinkItemSelectionModel(QAbstractItemModel*, QItemSelectionModel*, QObject*)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Build gammaray FAILED
```

This library is linked elsewhere so I cannot treat it like a plugin and disable building this directory.

Since we do not use KDE, we would like gammaray to function without kde libraries.

**Comment by krf** [comment]
Heya,

You don't need KDE libraries installed; we have the necessary sources included in the GammaRay repository. They are included in the build.

Can you post more context? I'm interested in the ld command-line arguments (this line should be right above that error message you posted).

**Comment by HenryMiller1** [comment]
[72/581] Linking CXX shared library li...bgammaray_common-qt5_6-x86_64.so.2.5.1
FAILED: : && /opt/jdx/tools//usr/local/share/icecc/bin//x86_64-wrs-linux-g++  -fPIC --sysroot=/home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox -std=c++14 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wextra -Woverloaded-virtual -Winit-self -Wmissing-include-dirs -Wunused -Wno-div-by-zero -Wundef -Wpointer-arith -Wmissing-noreturn -Werror=return-type -Wswitch -std=gnu++0x -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wreorder -Wformat -Wformat-security -O2 -g -DNDEBUG  -Wl,--fatal-warnings -Wl,--no-undefined -lc -shared -Wl,-soname,libgammaray_common-qt5_6-x86_64.so.2.5.1 -o lib/libgammaray_common-qt5_6-x86_64.so.2.5.1 common/CMakeFiles/gammaray_common.dir/__/3rdparty/lz4/lz4.c.o common/CMakeFiles/gammaray_common.dir/methodargument.cpp.o common/CMakeFiles/gammaray_common.dir/objectbroker.cpp.o common/CMakeFiles/gammaray_common.dir/protocol.cpp.o common/CMakeFiles/gammaray_common.dir/message.cpp.o common/CMakeFiles/gammaray_common.dir/endpoint.cpp.o common/CMakeFiles/gammaray_common.dir/paths.cpp.o common/CMakeFiles/gammaray_common.dir/propertysyncer.cpp.o common/CMakeFiles/gammaray_common.dir/modelevent.cpp.o common/CMakeFiles/gammaray_common.dir/modelutils.cpp.o common/CMakeFiles/gammaray_common.dir/paintanalyzerinterface.cpp.o common/CMakeFiles/gammaray_common.dir/sourcelocation.cpp.o common/CMakeFiles/gammaray_common.dir/translator.cpp.o common/CMakeFiles/gammaray_common.dir/remoteviewinterface.cpp.o common/CMakeFiles/gammaray_common.dir/remoteviewframe.cpp.o common/CMakeFiles/gammaray_common.dir/transferimage.cpp.o common/CMakeFiles/gammaray_common.dir/gammaray_common_automoc.cpp.o  /home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox/usr/local/Trolltech/Qt-5/lib/libQt5Network.so.5.6.0 /home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox/usr/local/Trolltech/Qt-5/lib/libQt5Gui.so.5.6.0 -lgammaray_kitemmodels /home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox/usr/local/Trolltech/Qt-5/lib/libQt5Core.so.5.6.0 -Wl,-rpath,/home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox/usr/local/Trolltech/Qt-5/lib: && :
/opt/jdx/tools/sysroots/x86_64-wrlinuxsdk-linux/usr/libexec/x86_64-wrs-linux/gcc/x86_64-wrs-linux/5.2.0/real-ld: cannot find -lgammaray_kitemmodels
collect2: error: ld returned 1 exit status

**Comment by HenryMiller1** [comment]
Note that I'm doing an out of source build, and compiling against a sysroot not the host OS.

**Comment by HenryMiller1** [comment]
[80/589] Linking CXX shared library li...bgammaray_common-qt5_6-x86_64.so.2.5.1
FAILED: : && /opt/jdx/tools//usr/local/share/icecc/bin//x86_64-wrs-linux-g++  -fPIC --sysroot=/home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox -std=c++14 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wextra -Woverloaded-virtual -Winit-self -Wmissing-include-dirs -Wunused -Wno-div-by-zero -Wundef -Wpointer-arith -Wmissing-noreturn -Werror=return-type -Wswitch -std=gnu++0x -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wreorder -Wformat -Wformat-security -O2 -g -DNDEBUG  -Wl,--fatal-warnings -Wl,--no-undefined -lc -shared -Wl,-soname,libgammaray_common-qt5_6-x86_64.so.2.5.1 -o lib/libgammaray_common-qt5_6-x86_64.so.2.5.1 common/CMakeFiles/gammaray_common.dir/__/3rdparty/lz4/lz4.c.o common/CMakeFiles/gammaray_common.dir/methodargument.cpp.o common/CMakeFiles/gammaray_common.dir/objectbroker.cpp.o common/CMakeFiles/gammaray_common.dir/protocol.cpp.o common/CMakeFiles/gammaray_common.dir/message.cpp.o common/CMakeFiles/gammaray_common.dir/endpoint.cpp.o common/CMakeFiles/gammaray_common.dir/paths.cpp.o common/CMakeFiles/gammaray_common.dir/propertysyncer.cpp.o common/CMakeFiles/gammaray_common.dir/modelevent.cpp.o common/CMakeFiles/gammaray_common.dir/modelutils.cpp.o common/CMakeFiles/gammaray_common.dir/paintanalyzerinterface.cpp.o common/CMakeFiles/gammaray_common.dir/sourcelocation.cpp.o common/CMakeFiles/gammaray_common.dir/translator.cpp.o common/CMakeFiles/gammaray_common.dir/remoteviewinterface.cpp.o common/CMakeFiles/gammaray_common.dir/remoteviewframe.cpp.o common/CMakeFiles/gammaray_common.dir/transferimage.cpp.o common/CMakeFiles/gammaray_common.dir/gammaray_common_automoc.cpp.o  /home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox/usr/local/Trolltech/Qt-5/lib/libQt5Network.so.5.6.0 /home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox/usr/local/Trolltech/Qt-5/lib/libQt5Gui.so.5.6.0 lib/libgammaray_kitemmodels-qt5_6-x86_64.so.2.5.1 /home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox/usr/local/Trolltech/Qt-5/lib/libQt5Core.so.5.6.0 -Wl,-rpath,/home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/buildbox/usr/local/Trolltech/Qt-5/lib:/home/hm68841/workspace/gammaray/jdx/wr8-baytrail_64/build/lib: && :
common/CMakeFiles/gammaray_common.dir/objectbroker.cpp.o: In function `GammaRay::ObjectBroker::selectionModel(QAbstractItemModel*)':
/home/hm68841/workspace/gammaray/src/common/objectbroker.cpp:198: undefined reference to `KLinkItemSelectionModel::KLinkItemSelectionModel(QAbstractItemModel*, QItemSelectionModel*, QObject*)'
collect2: error: ld returned 1 exit status

**Comment by HenryMiller1** [comment]
Note that I have QT installed in a weird path - I had to edit the top CMakeLists.txt to add the path to the Qt5Config.cmake - but this is a change I expected to have to make, and it doesn't seem like it should be related.  

Also note that Qt4 does not exist on this system. Again I don't know what this might have to do with anything, but I don't want to withhold information.

**Comment by winterz** [comment]
Hi Henry,

are you using a toolchain file?
if so could you show me?
also show me your cmake command line.
you shouldn't need to mess around in the CMakeLists.txt file; instead you should put the directory containing the qmake you want to use first in %PATH%.

like:
> set PATH=c:\my\Qt\bin;%PATH%
> cmake -DCMAKE_TOOLCHAIN_FILE=gammaray\cmake\Toolchain-whatever.cmake etc. etc

more info about cross-compiling GammaRay can be found at https://github.com/KDAB/GammaRay/wiki/Cross-compiling-GammaRay

-Allen

**Comment by HenryMiller1** [comment]
Toolchain file is pretty simple.

SET (CMAKE_SYSTEM_NAME Linux)

if(NOT DEFINED CMAKE_FIND_ROOT_PATH)
    SET (CMAKE_FIND_ROOT_PATH "$ENV{SYSROOT}" CACHE STRING "Find root path" FORCE)
endif()

EXECUTE_PROCESS(COMMAND "which" "$ENV{CC}" OUTPUT_VARIABLE CC_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)
EXECUTE_PROCESS(COMMAND "which" "$ENV{CXX}" OUTPUT_VARIABLE CXX_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)

SET (CMAKE_C_COMPILER "${CC_PATH}" CACHE STRING "C compiler" FORCE)
SET (CMAKE_CXX_COMPILER "${CXX_PATH}" CACHE STRING "Cxx compiler" FORCE)

set (CMAKE_C_FLAGS "$ENV{CFLAGS}" CACHE STRING "C Compiler flags" FORCE)
set (CMAKE_CXX_FLAGS "$ENV{CXXFLAGS}" CACHE STRING "Cxx Compiler flags" FORCE)

SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

**Comment by HenryMiller1** [comment]
Opps, I missed at line from the above

SET (CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "$ENV{SYSROOT}/usr/lib64" "$ENV{SYSROOT}/lib64")

**Comment by HenryMiller1** [comment]
There is only one version of qmake in the environment I'm compiling against.

I think you are confusing the way cmake finds qt4 with the way it finds qt5.  For qt4 qmake is used, for qt5 cmake uses a Qt5Config.cmake file - I have this installed in a non-standard location so I need to tell cmake where to find it.

**Comment by winterz** [comment]
did you try passing -DGAMMARAY_BUILD_UI=OFF to cmake?

**Comment by HenryMiller1** [comment]
-DGAMMARAY_BUILD_UI=OFF makes no difference.  Nor does -DGAMMARAY_PROBE_ONLY_BUILD=ON.  

I tried commenting out 3rdparty/kde from the top level cmake file, but common links to this library so the build fails there.

**Comment by HenryMiller1** [comment]
We have discovered that if we copy the link command above and add 3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/krecursivefilterproxymodel.cpp.o to the command line that it will link correctly.  It isn't clear why this isn't done automatically though.

**Comment by HenryMiller1** [comment]
Switching to make (from ninja) and building kitmodels as a static library seems to have fixed this.  We are not clear on why the latter makes a difference.

**Comment by shrkamat** [comment]
Facing exact same issue, but static kitmodel is not an option for me
https://gist.github.com/shrkamat/4951ca5193bbaf123e346613cc8ac334
