### ISSUE TITLE
pre-built Windows executables?

### ISSUE THREAD

**Issue by Trass3r** [KDAB/GammaRay#253]
Maybe via AppVeyor or something similar.
https://github.com/apitrace/apitrace/blob/master/appveyor.yml
https://www.appveyor.com/docs/installed-software/#qt

**Comment by krf** [comment]
@TheOneRing is working on this

**Comment by TheOneRing** [comment]
Go to a successful build on https://ci.appveyor.com/project/winterz/gammaray/history
Select a compiler target -> Artifacts and download the 7z file.
For an example see https://ci.appveyor.com/project/winterz/gammaray/build/58/job/w7qb70xske5ov3t6/artifacts

The 7z can then be extracted into your Qt installation.
This setup isn't the most convenient yet but ist better than no binaries at all.

**Comment by talebi** [comment]
AppVeyor seems to have removed the artifacts. Can anyone help put/update those please. 
Thanks !

**Comment by TheOneRing** [comment]
Current builds can be found here https://ci.appveyor.com/project/KDAB/gammaray

**Comment by Bluscream** [comment]
Any news on this? I really need gammaray to debug some stuff :/

**Comment by Bluscream** [comment]
Okay so after a friend mentioned this to me i ran `S:\Qt\5.6\msvc2015_64\bin\windeployqt.exe "S:\Program Files\GammaRay\bin"` but now i get something like

![grafik](https://user-images.githubusercontent.com/3318223/44624310-1b59b180-a8da-11e8-84cd-5d2b9e3573cb.png)

**Comment by TheOneRing** [comment]
The missing artifacts where a bug.
The installer is part of the x64 build.

**Comment by Bluscream** [comment]
https://ci.appveyor.com/project/KDAB/gammaray/builds/29233899/job/xwsp7cyvl3pp606u/artifacts

The latest successful build contains no artifacts anymore?

**Comment by winterz** [comment]
The KDAB GammaRay project for AppVeyor has been removed as we haven't supported that for a long time. You can try the Qt MarketPlace for pre-built binaries. Or, if you know conan, you can find a conan recipe under the conan folder in the GammaRay source code.  Or build from source using the CMake buildsystem.

**Comment by Bluscream** [comment]
what the fuck? https://marketplace.qt.io/products/gammaray-1?_pos=1&_sid=90e60863c&_ss=r

1000 bucks for a free tool? :thinking:

**Comment by tilladam** [comment]
(Disclaimer: I work at KDAB and I'm responsible for the decision not to provide Window binaries for GammaRay for free)

GammaRay is freely available in source format and from many Linux distributions also in binary format. It is provided under Open Source licenses and at no charge and you can build and use it yourself with no restrictions other than those imposed by the Open Source license, also commercially. 

Alternatively, when you buy the commercially licensed version from the Qt Marketplace, you get pre-built and constantly maintained and updated binaries for Windows and the other platforms as well as professional support from the authors of the tool for a year. You also support the continued development of the tool and allow us to keep providing it for free to everyone. I find it interesting that you apparently feel that a super useful and powerful tool like GammaRay is not worth the asking price, which is much lower than comparable tools in other areas and in addition is only charged to those who'd rather pay than spend the time to build themselves and who'd like some help on how to use it effectively. We think that is actually a very fair and generous offering. 

If you need GammaRay urgently for work on a Free Software project, I'm sure the community will be happy to help you get it going in the appropriate channels for that. If you need it for commercial work, you have commercial options or you can invest the time to figure it out yourself. Which is more economical for you is your decision.

**Comment by Bluscream** [comment]
For me as a hobbyist stundent it's definitly not a fair price. I don't even earn that much money in a year. I also dont need constant updates or 1 to 1 tech support as i am just reverse engineering stuff and use it as aid for making modifications to other apps.

**Comment by Trass3r** [comment]
You don't need QtCreator to build it. Just CMake and the build system of your choice.

**Comment by Bluscream** [comment]
Does VS 2019 community work too?

**Comment by krf** [comment]
That should work as well, yes.

**Comment by ferdnyc** [comment]
> (Disclaimer: I work at KDAB and I'm responsible for the decision not to provide Window binaries for GammaRay for free)

That was one of the most impressive acts of flinging oneself under the bus I've seen since the HD-DVD team said, "Yeah, just use Blu-Ray." So, kudos for that. :laughing:

**Comment by tilladam** [comment]
@ferdnyc I'm not sure I understand what you are trying to say. Do you think we are throwing ourselves under the bus by not providing windows binaries for free or by stating our reasons for it and pointing out the alternatives?

**Comment by ferdnyc** [comment]
@tilladam Oh, no, not at all. No, I was _genuinely_ impressed with your individual willingness to stand up and declare yourself as the one all of the pitchfork-wielding villagers are here to see. :grin: 

KDAB's decision, I find perfectly understandable, and more to the point it's _your_ (collectively) decision to make. As we **keep** trying to drill into people: "It's free as in speech, not free as in beer."

**Comment by tilladam** [comment]
@ferdnyc Thanks. It's what my boss would do, KDAB culture. :)

**Comment by francoamato** [comment]
I used GammaRay andI don't see it as being useful enough to justify such a high expense
