### ISSUE TITLE
Assert in object model filtering

### ISSUE THREAD

**Issue by z-s-e** [KDAB/GammaRay#259]
In the Objects tab, when having very many objects and using the filtering feature, I easily get the following assert:
`Fatal (default): :0 (in ): ASSERT: "source_index.isValid()" in file /home/zeno/src/GammaRay/3rdparty/kde/krecursivefilterproxymodel.cpp, line 309`

**Comment by krf** [comment]
Needs backtrace.

**Comment by z-s-e** [comment]
Sorry, can't reproduce exactly anymore (still some misbehavior, but hard to give a deterministic description). Closing for now
