### ISSUE TITLE
contextmenuextension.cpp compile Error

### ISSUE THREAD

**Issue by oberluz** [KDAB/GammaRay#272]
master: 785afb0c435870d5cd9a628595118aae75cd57f9
ubuntu 14.04 / gcc 4.7.3 / cmake 2.8.12.2

```
% mkdir build
% cd build
% cmake ..
% make

Scanning dependencies of target gammaray_kitemmodels_automoc
[  0%] Automoc for target gammaray_kitemmodels
Generating moc_klinkitemselectionmodel.cpp
Generating moc_krecursivefilterproxymodel.cpp
Generating moc_kmodelindexproxymapper.cpp
[  0%] Built target gammaray_kitemmodels_automoc
Scanning dependencies of target gammaray_kitemmodels
[  0%] Building CXX object 3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/klinkitemselectionmodel.cpp.o

...

Scanning dependencies of target gammaray_ui
[ 22%] Building CXX object ui/CMakeFiles/gammaray_ui.dir/aboutdata.cpp.o
[ 22%] Building CXX object ui/CMakeFiles/gammaray_ui.dir/clienttoolmanager.cpp.o
[ 22%] Building CXX object ui/CMakeFiles/gammaray_ui.dir/clienttoolmodel.cpp.o
[ 22%] Building CXX object ui/CMakeFiles/gammaray_ui.dir/contextmenuextension.cpp.o
/home/pnader/Development/GammaRay/ui/contextmenuextension.cpp: In lambda function:
/home/pnader/Development/GammaRay/ui/contextmenuextension.cpp:129:67: error: ‘this’ was not captured for this lambda function
/home/pnader/Development/GammaRay/ui/contextmenuextension.cpp:129:89: error: unable to deduce ‘auto’ from ‘<expression error>’
/home/pnader/Development/GammaRay/ui/contextmenuextension.cpp:130:22: error: ‘this’ was not captured for this lambda function
make[2]: *** [ui/CMakeFiles/gammaray_ui.dir/contextmenuextension.cpp.o] Error 1
make[1]: *** [ui/CMakeFiles/gammaray_ui.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by oberluz** [comment]
Patch to fix:

diff --git a/ui/contextmenuextension.cpp b/ui/contextmenuextension.cpp
index d85ef34..c7bcd39 100644
--- a/ui/contextmenuextension.cpp
+++ b/ui/contextmenuextension.cpp
@@ -124,7 +124,7 @@ void ContextMenuExtension::populateMenu(QMenu *menu)
 
     // delay adding actions until we know the supported tools
     connect(ClientToolManager::instance(), &ClientToolManager::toolsForObjectResponse,
-            menu, [menu](const ObjectId &id, const QVector<ToolInfo> &toolInfos) {
+            menu, [this, menu](const ObjectId &id, const QVector<ToolInfo> &toolInfos) {
         foreach (const auto &toolInfo, toolInfos) {
             auto action = menu->addAction(tr("Show in \"%1\" tool").arg(toolInfo.name()));
             QObject::connect(action, &QAction::triggered, [id, toolInfo]() {

**Comment by akreuzkamp** [comment]
This is due to a bug in GCC 4.6 and 4.7, see: http://stackoverflow.com/questions/4940259/lambdas-require-capturing-this-to-call-static-member-function#4941046

We should work around it anyway, so thanks for the catch :)

**Comment by akreuzkamp** [comment]
Fix merged. :)
