### ISSUE TITLE
Can not even install

### ISSUE THREAD

**Issue by EddieDhakal** [KDAB/GammaRay#300]
```
$ sudo apt-get update
$ sudo apt-get install gammaray
```

Gives the following error.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) gammaray [ amd64 ] < none -> 2.3.0-3build1 > ( universe/devel )
Broken gammaray:amd64 Depends on libcgraph6 [ amd64 ] < none -> 2.38.0-12ubuntu2 > ( libs )
  Considering libcgraph6:amd64 1 as a solution to gammaray:amd64 9999
  Re-Instated libcdt5:amd64
  Re-Instated libcgraph6:amd64
Broken gammaray:amd64 Depends on libgvc6 [ amd64 ] < none -> 2.38.0-12ubuntu2 > ( libs )
  Considering libgvc6:amd64 1 as a solution to gammaray:amd64 9999
  Re-Instated libpathplan4:amd64
  Re-Instated libgvc6:amd64
Broken gammaray:amd64 Depends on libqt5scripttools5 [ amd64 ] < none -> 5.7.0+dfsg-0neon+16.04+build9 > ( libs ) (>= 5.0.2)
  Considering libqt5scripttools5:amd64 0 as a solution to gammaray:amd64 9999
  Re-Instated libqt5scripttools5:amd64
Broken gammaray:amd64 Depends on qtbase-abi-5-5-1 [ amd64 ] < none ->  > ( none )
  Considering libqt5core5a:amd64 2862 as a solution to gammaray:amd64 9999
  Considering libqt5core5a:amd64 2862 as a solution to gammaray:amd64 9999
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gammaray : Depends: qtbase-abi-5-5-1
            Recommends: gammaray-probe-qt4 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

It is not available as a QtCreator plugin, is it?

Would be really awesome if you are planning to have some sort of easy peasy to use (download click and run sort of self contained binary) like an AppImage app (http://appimage.org/) or SnapCraft (http://snapcraft.io/) image will do.

**Comment by krf** [comment]
@EddieDhakal Please report that issue upstream, e.g. here: https://bugs.launchpad.net/ubuntu/+source/gammaray

We have no control over the packages provided by Ubuntu

**Comment by winterz** [comment]
for the record, we do provide packages for Ubuntu via the OpenSUSE Build Service.
the url is http://software.opensuse.org/download.html?project=isv%3AKDAB&package=gammaray

except, as luck would have it, that link is broken at the moment.

**Comment by probonopd** [comment]
Generated an experimental [AppImage](http://appimage.org/) based on the binaries on OpenSUSE Build Service. It should run on most 2014-ish and later distributions. It bundles its own copy of Qt 4. Just download the AppImage, set the executable bit, and run.

https://bintray.com/probono/AppImages/GammaRay/_latestVersion#files

This is the yml file that was used for the deb to AppImage conversion:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/GammaRay.yml
It is expected that some fine tuning (by someone who knows the application) may be required.

Here is the log of the conversion:
https://api.travis-ci.org/jobs/191024125/log.txt?deansi=true

Please report any issues with it in https://github.com/probonopd/AppImages/issues and let me know if the project would like to provide an official AppImage.
