### ISSUE TITLE
Hangs when attached to a process on OSX 10.11.6

### ISSUE THREAD

**Issue by krasi-georgiev** [KDAB/GammaRay#305]
as a follow up from the original issue #292

DYLB_LIBRARY_PATH=/Applications/GammaRay.app/Contents/Frameworks /Applications/GammaRay.app/Contents/MacOS/gammaray -- /Users/krasimir/projects/vipconsult/Qt/build-PortalChat-Desktop_Qt_5_8_0_clang_64bit-Debug/PortalChat.app/Contents/MacOS/PortalChat

and this is the result
Detected ABI qt5_8-x86_64, using ABI qt5_8-x86_64.
dyld: Library not loaded: @rpath/libgammaray_core-qt5_8-x86_64.2.7.0.dylib
Referenced from: /Applications/GammaRay.app/Contents/PlugIns/gammaray/2.7/qt5_8-x86_64/gammaray_probe.dylib
Reason: image not found
Injector error: Process crashed

**Comment by pasnox** [comment]
Looking at that right now as it impact me too

**Comment by pasnox** [comment]
Hm, I can no longer reproduce with latest update from Qt SDK / Qt 5.8.0-1.
Can you still reproduce it after the update ?

**Comment by pasnox** [comment]
Fixed, please confirm it fix your issue.

**Comment by krasi-georgiev** [comment]
updating now and will let you know

Kind Regards Krasi

**Comment by krasi-georgiev** [comment]
git pull and new compile fixed the issue

thanks

**Comment by pasnox** [comment]
Great!
