### ISSUE TITLE
Tool idea: QML binding loop investigator

### ISSUE THREAD

**Issue by AndreSomers** [KDAB/GammaRay#308]
With QML, you sometimes run into non-trivial binding loops. It would be nice if gammaray could help to resolve these, by somehow visualizing the loop. http://stackoverflow.com/questions/38196644/how-to-analyse-a-binding-loop describes a way to attack these with a debugger, but perhaps gammaray could pull off something simular and even resolve the items and properties involved?

**Comment by vkrause** [comment]
Implemented in master for Qt >= 5.10.
