### ISSUE TITLE
Warning about weak GPG APT repo key at OBS

### ISSUE THREAD

**Issue by estan** [KDAB/GammaRay#319]
```
estan@newton:~$ sudo apt-get update
...
W: http://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_16.04/Release.gpg: Signature by key 61250C0BB81EE7DBB251FA664662F0D966A0BB9B uses weak digest algorithm (SHA1)
...
estan@newton:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
estan@newton:~$
```

Here's an upstream report: https://github.com/openSUSE/obs-sign/issues/5

I think what you need to do is switch to an RSA key instead of a DSA key, otherwise SHA256 can't be used:

```
estan@newton:~$ gpg Release.key 
pub  1024D/66A0BB9B 2012-01-17 isv:KDAB OBS Project <isv:KDAB@build.opensuse.org>
estan@newton:~$
```

**Comment by estan** [comment]
Any progress on this, who should I bug about it? I'd help out if I could, but it must be done by the proper authorities so to speak :)

**Comment by krf** [comment]
@winterz Any idea? For the record, Allen maintains the OBS repository, so he's the right person to speak to.

**Comment by winterz** [comment]
I haven't a clue if there's anything I can do about it.  seems to be under OBS control. they generate they keys.  I spent already too much time investigating and got absolutely nowhere on it.

**Comment by estan** [comment]
@winterz: Ah yes, I did some digging and I understand your pain now. See the upstream report https://github.com/openSUSE/obs-sign/issues/5 . Apparently, RSA keys are default now, and more secure hashing is used. But for existing projects I can't find a way to trigger the generation of a new key (to get RSA). Someone else asked for this on that bug report, and I chimed in. So let's just see what they say.

**Comment by estan** [comment]
@winterz I recently had to fuzz about with the key for a project of my own, and I think I came across what you need to do.

You can see the current key (`1024D`, 1024-bit DSA) with `osc signkey isv:KDAB | gpg`:

```
estan@newton:~$ osc signkey isv:KDAB | gpg
pub  1024D/66A0BB9B 2012-01-17 isv:KDAB OBS Project <isv:KDAB@build.opensuse.org>
estan@newton:~$
```

Now, to replace it with a new RSA key:

1. Create a new key for the `isv:KDAB` project:
```
    osc signkey --create isv:KDAB
```
This should remove the old DSA key and create a new RSA key. After this, `osc signkey isv:KDAB | gpg` should list the new RSA key (`pub  2048R/...`).

2. Re-build all packages. This is needed to trigger a republishing, with the new key:
```
    osc rebuild --all isv:KDAB
```
After the builds are finished, there's often a little waiting before the OBS "publisher" and "signer" comes around.

**Comment by estan** [comment]
If (1) doesn't work, you may have to `osc signkey --delete` first, to manually delete the DSA key. But if I interpret the docs correctly, `--create` should replace the existing key with the new one.

**Comment by estan** [comment]
And if you haven't used the `osc` tool before (I hadn't), it'll prompt you for your `build.opensuse.org` credentials.

**Comment by estan** [comment]
And finally: You can of course skip step 2, and let the new key be phased in for the different packages when new releases are published.

**Comment by winterz** [comment]
Thanks!
I followed your instructions and just now started 'osc rebuild --all isv:KDAB'.  
let me know if this helps.  probably need to wait a few hours for the rebuilds.

**Comment by estan** [comment]
Yay. No more warnings from apt :) Many thanks!

Perhaps it's a good idea to put out a message somewhere that users will have to add the new key, to avoid getting bug reports from users that had previously added the repo and the old key. They'll get an error on their next `apt update`, since they haven't `apt-key add`ed the new key.
