### ISSUE TITLE
"Unable to receive probe settings" when using distro package against newer Qt version

### ISSUE THREAD

**Issue by mitchcurtis** [KDAB/GammaRay#323]
I was trying to build from sources, but I suck at cmake and so couldn't get it to work. I tried using the prebuilt binary (sudo apt-get install gammaray), but when I run it using the instructions [here](http://doc.qt.io/GammaRay/gammaray-getting-started.html#on-the-command-line), I get the following errors, and the GammaRay window never shows up:

```
mitch@mitch-ubuntu:~/dev/qt5-dev-debug/qtquickcontrols2/tests/manual/icons$ gammaray ./icons
Detected ABI qt5.9-x86_64, using ABI qt5.5-x86_64.
Found relocatable symbol in "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5" : "qt_startup_hook"
QML debugging is enabled. Only use this in a safe environment.
Unable to receive probe settings, cannot attach to shared memory region "gammaray-28602" "/tmp/qipc_sharedmemory_gammaray418ba87017f1f90b3834c46abdfef8772a8cb52d" , error is: "QSharedMemory::attach (shmget): doesn't exist"
Continueing anyway, with default settings.
Unable to receive probe settings, cannot attach to shared memory region "gammaray-28602" "/tmp/qipc_sharedmemory_gammaray418ba87017f1f90b3834c46abdfef8772a8cb52d" , error is: "QSharedMemory::attach (shmget): doesn't exist"
Continueing anyway, with default settings.
```

**Comment by krf** [comment]
@mitchcurtis Which version of GammaRay is this? I presume it's v2.6.0?

Please try again compiling from Git -- there have been a couple of changes in GammaRay since then, which might fix your issue.

**Comment by mitchcurtis** [comment]
Building from Git works, so this can be closed. I did run into another issue while trying to attach to a running application though:

Potential errors:
  Error: gdb: Yama security extension is blocking runtime attaching, see /proc/sys/kernel/yama/ptrace_scope
  Error: lldb: The debugger executable 'lldb' could not be found

**Comment by krf** [comment]
Yep, you'll have to relax your kernel security settings, see the notes about `ptrace_scope` in https://github.com/KDAB/GammaRay/wiki/Known-Issues

**Comment by krf** [comment]
Closing then, thanks for your feedback!
