### ISSUE TITLE
fail when make , Ubuntu 16.04 x64, Qt 5.8

### ISSUE THREAD

**Issue by linbin823** [KDAB/GammaRay#328]
complie GammaRay with command:

cmake ..
make

cmake finished, but make failed

it says:

```
[ 80%] Built target gammaray_actioninspector_ui_plugin
[ 80%] Automatic moc for target gammaray_actioninspector_plugin
[ 80%] Built target gammaray_actioninspector_plugin_automoc
[ 80%] Built target gammaray_actioninspector_plugin
[ 80%] Automatic moc for target gammaray_widget_export_actions
[ 80%] Built target gammaray_widget_export_actions_automoc
[ 80%] Built target gammaray_widget_export_actions
[ 81%] Automatic moc for target gammaray_widgetinspector_plugin
[ 81%] Built target gammaray_widgetinspector_plugin_automoc
Scanning dependencies of target gammaray_widgetinspector_plugin
[ 81%] Building CXX object plugins/widgetinspector/CMakeFiles/gammaray_widgetinspector_plugin.dir/gammaray_widgetinspector_plugin_automoc.cpp.o
[ 81%] Linking CXX shared module ../../lib/gammaray/2.8/qt5_8-x86_64/gammaray_widgetinspector_plugin.so
[ 82%] Built target gammaray_widgetinspector_plugin
[ 82%] Automatic moc for target gammaray_widgetinspector_ui_plugin
[ 82%] Built target gammaray_widgetinspector_ui_plugin_automoc
[ 83%] Built target gammaray_widgetinspector_ui_plugin
[ 83%] Generating WidgetDelegate.qml.qmllint
qmllint: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmllint': No such file or directory
plugins/widgetinspector/assets/qml/CMakeFiles/WidgetDelegate.qml_qmllint.dir/build.make:60: recipe for target 'plugins/widgetinspector/assets/qml/WidgetDelegate.qml.qmllint' failed
make[2]: *** [plugins/widgetinspector/assets/qml/WidgetDelegate.qml.qmllint] Error 1
CMakeFiles/Makefile2:8277: recipe for target 'plugins/widgetinspector/assets/qml/CMakeFiles/WidgetDelegate.qml_qmllint.dir/all' failed
make[1]: *** [plugins/widgetinspector/assets/qml/CMakeFiles/WidgetDelegate.qml_qmllint.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by krf** [comment]
@linbin823 Why did you close this?

**Comment by modjo756** [comment]
@krf i have exactly the same problem with the same config ? @linbin823, how did you solve this issue please (if you close it ?)

**Comment by winterz** [comment]
looks like the buildsystem found a qmllint somewhere in the default search path (however CMake does that), but what it found is bogus some how.  not to mention that it found qmllint in a qt4 subdir

I'm no ubuntu expert, but maybe you need to install a package that provides a qt5 version of qmllint?

**Comment by modjo756** [comment]
before i launch cmake i added to the path the location of my qt5.8 install. Perhaps i need to install qt5-default on my pc ...

**Comment by winterz** [comment]
debian packages I use are:
qt5-default, qtbase5-private-dev, qtdeclarative5-dev, qtdeclarative5-private-dev, qtdeclarative5-dev-tools, qtscript5-dev, qttools5-dev, qttools5-dev-tools, libqt5svg5-dev, libqt5webkit5-dev

**Comment by modjo756** [comment]
Hi i have installed all this packet but i have this error now : 

`[ 98%] Generating Slider.qml.qmllint
/usr/lib/x86_64-linux-gnu/qt5/bin/qmllint: error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory
examples/quick-batching/CMakeFiles/Slider.qml_qmllint.dir/build.make:60 : la recette pour la cible « examples/quick-batching/Slider.qml.qmllint » a échouée
make[2]: *** [examples/quick-batching/Slider.qml.qmllint] Erreur 127
CMakeFiles/Makefile2:10101 : la recette pour la cible « examples/quick-batching/CMakeFiles/Slider.qml_qmllint.dir/all » a échouée
make[1]: *** [examples/quick-batching/CMakeFiles/Slider.qml_qmllint.dir/all] Erreur 2
Makefile:160 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
`
