### ISSUE TITLE
Qt packages have not been found (using Toolchain-Linux-GCC-armv7.cmake)

### ISSUE THREAD

**Issue by bobShiang** [KDAB/GammaRay#332]
When i cmake the source of GammarRay by belowing options.
`cmake -DCMAKE_INSTALL_PREFIX=/home/xiangxibo/workspace/gammaray_install -DGAMMARAY_ENFORCE_QT4_BUILD=true -DGAMMARAY_BUILD_UI=OFF -DCMAKE_PREFIX_PATH=/home/xiangxibo/workspace/qtsrc`

and got the following results, you can see Qt4 have been found, but why yet got the prompt "The following REQUIRED packages have not been found"?
my CMake version is 3.0.2, Qt Version is 4.8.6.

and ideas? thanks. 

```
-- Building GammaRay 2.7.0 in Release mode
-- Found Qt4: /home/share/qt/4.8.6/Board/arm-none-linux-gnueabi-4.9.1-armv7/bin/qmake (found suitable version "4.8.6", minimum required is "4.8.0") 
-- Found Qt4: /home/share/qt/4.8.6/Board/arm-none-linux-gnueabi-4.9.1-armv7/bin/qmake (found suitable version "4.8.6", minimum required is "4.8.0") 
Qt QTDESIGNER library not found.
Qt QTSVG library not found.
Qt QTWEBKIT library not found.
-- Building probe for ABI: qt4_8-i686 (Release)
-- 
-- The following features have been enabled:

 * Option GAMMARAY_ENFORCE_QT4_BUILD , Enforce a build with Qt4 (by default GammaRay looks out for Qt5 first)
 * Option GAMMARAY_MULTI_BUILD , Build multiple applicable probe configurations.
 * Option GAMMARAY_BUILD_DOCS , Build GammaRay documentation.
 * QtScript debugger , Requires QtScript and QtScriptTools.
 * ELF ABI detection , Automatic probe ABI detection on ELF-based systems. Requires elf.h.

-- The following RECOMMENDED packages have been found:

 * rt , High resolution clock, part of glibc
   Needed for the timer profiler plugin.

-- The following features have been disabled:

 * Option GAMMARAY_BUILD_UI , Build the GammaRay client and in-process UI.
 * Option GAMMARAY_PROBE_ONLY_BUILD , Build only an additional probe configuration for an already existing launcher.
 * Option GAMMARAY_ENABLE_GPL_ONLY_FEATURES , Enable features only available under GPL license.
 * Option GAMMARAY_INSTALL_QT_LAYOUT , Install into Qt directory layout.
 * Option GAMMARAY_STATIC_PROBE , Build the probe as static library for compile-time injection (requires Qt 5.4 or newer).
 * QPainter analyzer , You must have a build version of Qt available. Make sure the qmake found first in your execute comes from this build version.
 * Option GAMMARAY_CORE_ONLY_LAUNCHER , Only use QtCore in the CLI launcher (breaks style injector, but is needed for Boot2Qt compatibility)
 * Web inspector , Requires QtWebKit.
 * Widget .ui file export , Requires QtDesigner library.
 * 3D Widget Inspector , Requires Qt5 >= 5.7, Qt3D and QtQuick Controls

-- The following OPTIONAL packages have not been found:

 * Glslang , <https://github.com/KhronosGroup/glslang>
   Validate GL shader code.
 * QmlLint , <https://qt.io>
   Validate QML code.

**-- The following REQUIRED packages have not been found:

 * Qt4 (required version >= 4.8.0) , <https://qt.io/>**

CMake Error at /usr/share/cmake-3.0/Modules/FeatureSummary.cmake:513 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:834 (feature_summary)
```

**Comment by bobShiang** [comment]
I found that there are no files such as "*.cmake" in my qt4/lib installation directory.
that means i will rebuild QT4 with related configurations?i have no idea.
In addtion, i cmake gammaray with QT5 successfully.but then make and meet some error.

**Comment by winterz** [comment]
Qt4 never provided cmake files.
But I don't think you should need them.  Don't set -DCMAKE_PREFIX_PATH=/home/xiangxibo/workspace/qtsrc

For building Qt4 version first make sure that 'which qmake' points to the Qt4 version of qmake.  you may need to adapt your $PATH first.
then:
cmake -DCMAKE_INSTALL_PREFIX=/home/xiangxibo/workspace/gammaray_install -DGAMMARAY_ENFORCE_QT4_BUILD=true -DGAMMARAY_BUILD_UI=OFF

The Install.txt file mentions this.

**Comment by bobShiang** [comment]
hi winterz,
exactly, i make sure i have set QT environment and can point QT4 version of qmake correctly.
then i remove the option "-DCMAKE_PREFIX_PATH", and run 
**cmake -DCMAKE_TOOLCHAIN_FILE=/home/xxx/workspace/gammaray/GammaRay-2.7.0/cmake/Toolchain-Linux-GCC-armv7.cmake -DCMAKE_INSTALL_PREFIX=/home/xxx/workspace/gammaray_install -DGAMMARAY_BUILD_UI=OFF**

i am cross-compile gammaray, but still display errors:
**-- The following REQUIRED packages have not been found:

 * Qt4 (required version >= 4.8.0) , <https://qt.io/>

CMake Error at /usr/share/cmake-3.0/Modules/FeatureSummary.cmake:513 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:834 (feature_summary)**

Can you help me out?
thanks.

**Comment by krf** [comment]
This works totally fine here, for a normal build. I suspect the problem is caused by your Toolchain file?

Could you share the file `Toolchain-Linux-GCC-armv7.cmake`? It's not part of the GammaRay sources.

**Comment by winterz** [comment]
closing. old. no response.
