### ISSUE TITLE
Add demo mode to GammaRay

### ISSUE THREAD

**Issue by krf** [KDAB/GammaRay#339]
We're usually demoing GammaRay at trade shows, so a demo mode for it would be great to have. 

Features I'm considering:
Have a demo mode where:
* GammaRay cycles through its tool views
* GammaRay displays a On-Screen-Display banner which says it's currently in demo mode and shows tool X, doing Y
* GammaRay would abort the demo mode as soon there's user interaction
* Continue with the demo as soon as there's an inactivity for, say, around 5 minutes of time

**Comment by krf** [comment]
For cross-platform idle detection we have: https://github.com/KDAB/Charm/tree/master/Charm/Idle

**Comment by dantti** [comment]
Closing as we use a video nowadays
