### ISSUE TITLE
Can't build with Qt 5.8 MinGW

### ISSUE THREAD

**Issue by MCoder42** [KDAB/GammaRay#343]
1. Cmake 3.8.0-rc4
2. Qt 5.8 MinGW installed in C:\Qt directory
3. Windows 10

My console:

`git clone https://github.com/KDAB/GammaRay.git`
`set PATH=%PATH%;C:\Qt\Tools\mingw530_32\bin`
`set PATH=C:\Qt\5.8\mingw53_32\bin;C:/Qt/Tools/mingw530_32\bin;%PATH%`
`set PATH=%PATH%;C:\Program Files\CMake\bin\`
`mkdir build`
`cd build`
`cmake -G "MinGW Makefiles" ..`
`mingw32-make`

Produce this output: [https://pastebin.com/xvQfTbCp](https://pastebin.com/xvQfTbCp)

With error:
`mingw32-make[2]: *** No rule to make target 'C:/Qt/5.8/mingw53_32/lib/libGLESv2.lib', needed by 'plugins/gammaray/2.8/qt5_8-GNU-i686/gammaray_quickinspector.dll'.  Stop.`
`CMakeFiles\Makefile2:6139: recipe for target 'plugins/quickinspector/CMakeFiles/gammaray_quickinspector.dir/all' failed`
`mingw32-make[1]: *** [plugins/quickinspector/CMakeFiles/gammaray_quickinspector.dir/all] Error 2`
`Makefile:161: recipe for target 'all' failed`
`mingw32-make: *** [all] Error 2`

Please advice what is going wrong?

**Comment by vkrause** [comment]
It's caused by a bug in the Qt 5.8 Mingw cmake configuration files (proposed fixed here: https://codereview.qt-project.org/#/c/190498/), we are also looking into adding a workaround to GammaRay for this.

If you need a quick local fix, comment out the entire if(TARGET Qt5::Gui_GLESv2) block in plugins/quickinspector/CMakeLists.txt.

**Comment by MCoder42** [comment]
Thank you. All built and run without problems.

But when I click on "Widgets" menu GammaRay crashed...

**Comment by vkrause** [comment]
Workaround for the GLESv2 issue has been integrated into master.
