### ISSUE TITLE
GammaRay generates probe names that it cannot load

### ISSUE THREAD

**Issue by danvratil** [KDAB/GammaRay#356]
I'm building a GammaRay probe for a Yocto image using `cmake -DGAMMARAY_BUILD_UI=OFF -DGAMMARAY_INSTALL_QT_LAYOUT=ON ..` and GammaRay generates probe binaries called `libgammaray_probe-qt5_7-cortexa9hf-neon-poky.so `

Looking into `ProbeABI::fromString()`, GammaRay will refuse the name on l.213:
  
    // idParts = { "qt5_7", "cortexa9hf", "neon", "poky" }
    if (idParts.size() != index + 1)
        return ProbeABI();

Index is 1 here (0 = Qt, 1 = ABI), so this condition prevents the probe from loading.

We should either fix cmake build to only produce probe names that we can load, or adjust ProbeABI and ProbeFinder to be able to deal with custom probe suffixes.

**Comment by vkrause** [comment]
Should be fixed in latest master.
