### ISSUE TITLE
Cannot Use GammaRay

### ISSUE THREAD

**Issue by Sochocguy** [KDAB/GammaRay#363]
Using Qt 5.7, MinGW 5.3, and CMake 3.8.1

I downloaded GammaRay using these commands 

set "PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%"
set "PATH=C:\Program Files\CMake\bin;%PATH%"
set "PATH=C:\Qt\Tools\QtCreator\bin;%PATH%"
set "PATH=C:\Qt\5.7\mingw53_32\bin;%PATH%"
mkdir build
cd build
cmake -G "MinGW Makefiles" ..
mingw32-make
mingw32-make install

It appears to have installed successfully, but when I go to the directory where gammaray.exe is located (C:\Program Files (x86)\GammaRay\bin) and run gammaray.exe it shows a list of additional arguments that I should add in order to make it run. To my knowledge, You should be able to type in gammaray.exe and then the GammaRay launcher should open. To get around this problem, I have been using gammaray-launcher in order to open the launcher. I have looked at the forms and it appears that this is not the correct way of doing it, but this is the only way that it works for me. 

I also cannot attach to any Qt Application. When I am in the GammaRay Launcher, I try to attach to something and it splashes a terminal window and closes out of the launcher.

I have also tried doing the command gammaray --pid <PID FOR QT APPLICATION>. It hangs on the loading screen and it says that the connection is being refused. Any help would be greatly appreciated.

**Comment by krf** [comment]
Heya. Why did you close this? Please share the solution if you found one.

**Comment by Sochocguy** [comment]
Hey. Sorry for the late response. When i was setting paths, i didn't set a path to my minGW library directory and that seemed to fix the issue.


________________________________

**Comment by Sochocguy** [comment]
Do you mind if I directly ask you questions through this email? or would you like me to go through the github page.


________________________________

**Comment by krf** [comment]
@Sochocguy When replying to the mail, the mail body is still added to the Github ticket. See above.
