### ISSUE TITLE
Quick Scenes Inspector does not colorize objects when application is using software renderer

### ISSUE THREAD

**Issue by LittleWhite-tb** [KDAB/GammaRay#452]
Usually, if you select objects from the Quick Scenes inspector, the view will colourize this object in red.
If the user application is using the software renderer `qputenv("QT_QUICK_BACKEND","software");`, the colourization will not work at all.

**Comment by chsterz** [comment]
Hi LittleWhite-tb, 
Thanks for that info!

Yes, you are absolutely right. We need to add this.
Currently heres the early-return.
https://github.com/KDAB/GammaRay/blob/master/plugins/quickinspector/quickoverlay.cpp#L562

I added a Ticket.

Christoph

**Comment by Waqar144** [comment]
Not reproducible anymore
