### ISSUE TITLE
CMake Default build type

### ISSUE THREAD

**Issue by jgueytat** [KDAB/GammaRay#457]
MSVC2015 32bit / QtCreator / Qt 5.9.1 / Tag 2.8.1
Here is the [screenshot](https://imgur.com/a/jRyTp) on how ends the compilation.
I did not set any particular parameter. I just opened the CMakeLists.txt with QtCreator and selected the kit MSVC2015 32bit. So I'm in "Default" mode.
The compilation ends on wlcompositorinspector which should not be enabled under Windows may be.

**Comment by jgueytat** [comment]
Trying the compilation of the same 2.8.1 source tag with Qt 5.9.2 and still MSVC2015 32bit.

**Comment by jgueytat** [comment]
Can't reproduce it with Qt 5.9.2.

**Comment by krf** [comment]
Note: Please just paste the compiler output instead of pasting screenshots. That helps search engines find this issue.

**Comment by vkrause** [comment]
The compilation error is of course a bug, but not the fact that the Wayland inspector UI is built on Windows. That is Qt-only code with no Wayland dependencies, and is needed e.g. for debugging embedded Linux devices from a Windows host.

**Comment by jgueytat** [comment]
```
C:\Users\jgueytat\Projects\build-GammaRay-2.8.1-Desktop_Qt_5_9_2_MSVC2015_32bit-Default\multibuild\GammaRay-Release\plugins\wlcompositorinspector\gammaray_wlcompositorinspector_ui_autogen\mocs_compilation.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
17:30:55: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project GammaRay (kit: Desktop Qt 5.9.2 MSVC2015 32bit)
When executing step "CMake Build"
17:30:55: Elapsed time: 41:41.
```

I was able to reproduce it with : 

- os: windows
- ide: qtcreator
- tag: 2.8.1
- qt: 5.9.2
- kit: MSVC2015 23bit
- build type: Default

**Comment by krf** [comment]
> jgueytat changed the title from wlcompositorinspector enabled during Windows compilation to CMake Default build type on Oct 20, 2017

Why did you change the title like this? Now I'm confused.

**Comment by jgueytat** [comment]
Default is a build type thats seems to exist in CMake or in QtCreator by "default". And GammaRay seems to not handle that build type. The point is to handle -DDefault or to remove the build type. Opening the CMakeLists.txt in a QtCreator should be enough.

**Comment by krf** [comment]
I honestly do not understand what this bug is about anymore. It got more and more confusing. Please open an issue dedicated to one particular issue or reopen this one with more details.
