### ISSUE TITLE
Disable user feedback support when Qt<5.3

### ISSUE THREAD

**Issue by joshdoe** [KDAB/GammaRay#468]
Discovered GammaRay today and excited about trying it, but while building for Win7x64/Qt5.2.1x64 I found out that the included version of kuserfeedback uses `QOpenGLFunctions::glGetString` which was introduced in Qt 5.3. Thankfully the CMake option `GAMMARAY_DISABLE_FEEDBACK` was provided, so it wasn't hard to fix, but it might be nice to automatically disable this if the Qt version is less than 5.3

**Comment by joshdoe** [comment]
I should also add that the quickinspector plugin requires 5.3 at least, through the use of `QQuickWindow::afterSynchronizing` and `QOpenGLFunctions::glReadPixels`. I disabled this plugin by commenting out the `add_subdirectory` line in the plugins folder. I feel like perhaps I'm missing something...

**Comment by vkrause** [comment]
The minimum required Qt5 version is 5.3, so CMake should be bailing out way before you even get to those errors...

**Comment by krf** [comment]
@joshdoe Are you sure you built against Qt 5.2?

**Comment by joshdoe** [comment]
@krf Yes I just double checked, I'm building against Qt 5.2.1.

@vkrause Just saw this now. I built 2.8.1, which in CMakeLists.txt requires Qt 5.1, I see it's been changed to 5.3 in master.
