### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by Bluscream** [KDAB/GammaRay#478]
How do i get the gammaray.exe ?

**Comment by krf** [comment]
That's not the right place for asking questions. You'd be better off doing that on our mailing list.

Regarding Windows builds for GammaRay: We're currently investigating how to provide binaries for Windows, stay tuned.

**Comment by Bluscream** [comment]
Whats the mail of the mailing list tho?

**Comment by krf** [comment]
You can find it on the project page: https://github.com/KDAB/GammaRay

**Comment by Bluscream** [comment]
Are windows build's still not a thing yet? And if so, can i use the ubuntu version through WSL to debug a windows Qt app?`+
