### ISSUE TITLE
Crash when probing In-process (on master: 787ada0, MSVC 2015 x64, Qt 5.9.3, custom-built)

### ISSUE THREAD

**Issue by sthlm58** [KDAB/GammaRay#481]
Repro:
> Start application under test (i.e. debug version of Qt Widgets exe)
> Start gammaray.exe
> Select Access mode: In-process
> Click "Attach"
> Crash!

This causes:
```
Unhandled exception thrown: read access violation.

this->m_serverDevice was nullptr.
```

In `GammaRay\core\remote\server.cpp:95`: 
``` c++
Q_ASSERT(!m_serverDevice->isListening());
```

Call Stack:
```
 	gammaray_core-qt5_9-MSVC-140-x86_64d.dll!GammaRay::Server::listen() Line 95	C++
	gammaray_core-qt5_9-MSVC-140-x86_64d.dll!GammaRay::Probe::delayedInit() Line 415	C++
 	gammaray_core-qt5_9-MSVC-140-x86_64d.dll!GammaRay::Probe::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 117	C++
```
---
Pointer was not set to anything meaningful, because of returning early from `Server::Server()`:
``` c++
if (!ProbeSettings::value(QStringLiteral("RemoteAccessEnabled"), true).toBool())
        return;
```

And that was set by UI launcher to:
``` c++
opt.setProbeSetting(QStringLiteral("RemoteAccessEnabled"), false);
```

So finally when `delayedInit()` was called (probably invoked from `void Probe::createProbe(bool findExisting)`), the pointer was `nullptr`, hence the crash.

**Comment by Markus43** [comment]
Exactly the same problem here (Qt 5.9.4, MSVC2015 32bit, self-built gammaray 2.9.0 from github release source package).

Did you find any workaround for this?
