### ISSUE TITLE
Question about the state machine debugger

### ISSUE THREAD

**Issue by Petross404** [KDAB/GammaRay#485]
Is the state machine debugger a runtime or buildtime dependency? I am writing an [ebuild](https://github.com/Petross404/testing/blob/master/dev-util/gammaray/gammaray-9999.ebuild) that I will give to gentoo devs and I must declare it correctly. Thank you.

**Comment by krf** [comment]
@Petross404 a runtime dependency. Considering that KDSME (that's what you're referring to, right?) was configured to produce dynamic libraries.

Note: Please ask questions like this on the mailing list instead. This is a bug tracker.
