### ISSUE TITLE
GammaRay with Qt Script ?

### ISSUE THREAD

**Issue by kingd123** [KDAB/GammaRay#487]
Hi there,

May I ask if GammaRay would be right for us, with our situation:

We're using Qt Script only, not fullblown Qt, because our vendor tool, a Windows exe application, launches our .js file. Which then in turn, via vendor command, launches our .ui file.

So that's it for us, just those two files. At least for this first foray, into Qt.
The vendor tool, includes in its Program Files folder, 16 Qt5*.dll
So I'm kind of thinking, the vendor tool itself, is perhaps written in fullblown Qt
Anyway, that's the setup
And I wondered if GammaRay could be usefully made use of, in the situation described ?

Many thanks,

David

**Comment by krf** [comment]
Does this mean the Window exe application doesn't run a QCoreApplication event loop? In that case GammaRay won't be useful for you.

I'm not sure I understand the question, though, to be honest...

Note: Please ask questions on the mailing list instead, this is a bug tracker only.
