### ISSUE TITLE
In-Process Launch crashes

### ISSUE THREAD

**Issue by feinstaub** [KDAB/GammaRay#488]
I am new to GammaRay and I noticed the following:

When I choose the Access Mode "In-Process"

![grafik](https://user-images.githubusercontent.com/368412/36060994-fcec8b08-0e53-11e8-9117-774bf4fb8c2e.png)

then the application crashes after having hit the Launch button:

```
Startup: gammaray-launcher
Detaching: /usr/bin/gammaray --inprocess --probe qt5_10-x86_64 --no-listen /usr/bin/kcalc
Working Directory: /home/gregor
user@tumbleweed:~> Detected ABI qt5_10-x86_64, using ABI qt5_10-x86_64.
Injector error: Process crashed
```

"Out-of-process (local only)" works fine.

**Comment by vkrause** [comment]
Fixed in 2.9 and master.
