### ISSUE TITLE
GammaRay became very, very slow

### ISSUE THREAD

**Issue by AndreSomers** [KDAB/GammaRay#490]
In the latest version, GammaRay became extremely slow, especially when navigating Quick Scenes. Often, windows even decorates the titlebar(s) with 

> (Not responding)

It can take minutes to populate the tree view you get when you ctrl+shift+lmb something in the QML scene with the object picker. The scene mirror in GammaRay also became very sluggish, and lags behind several seconds to the real application.

**Comment by akreuzkamp** [comment]
Can you please try to reproduce the issue with current master? We have fixed (and reintroduced and fixed) some performance-issues related to backtrace-generation. It would be helpful to know, if there are more performance issues to handle or if it was it.

**Comment by AndreSomers** [comment]
Seems to be ok now, on the current projects I am working on anyway.
