### ISSUE TITLE
GammaRay crash on default Qt Application

### ISSUE THREAD

**Issue by conradjones** [KDAB/GammaRay#494]
I was trying to track  down why GammaRay was crashing on my application, and built a default Qt Widgets application with Qt creator and GammaRay crashes on it too. 

I built gammaray from source (github clone) (i was previously using the repository version) to ensure it matched the instaled Qt5 version and with the same result.

I've uploaded an example project here:
https://github.com/conradjones/GammaRayGeometryTest.git

Just inspecting the form in objects or widgets crashes the application and GammaRay loses it's connection to the application.

OS: Arch (patched to latest)

I'm going to do a VM install of ubuntu and try it there and will update the isssue

**Comment by vkrause** [comment]
Thanks for the test case, https://github.com/KDAB/GammaRay/commit/3b701f3ce0ffb23762271cba9c531775bae941df seems to fix that crash for me.

**Comment by conradjones** [comment]
Ah excellent thanks. I'll try that commit.

**Comment by conradjones** [comment]
Looks fixed to me 

Thanks again
