### ISSUE TITLE
Crash on accessing scene objects (Qt 5.10.1 & gammaray 2.9.0)

### ISSUE THREAD

**Issue by ElderOrb** [KDAB/GammaRay#495]
![image](https://user-images.githubusercontent.com/23638/38606684-6c4aa8fe-3d7f-11e8-8cf6-455055d35221.png)

**Comment by ElderOrb** [comment]
... and another crash in 'idle' state: 

![image](https://user-images.githubusercontent.com/23638/38608823-1ec34cac-3d85-11e8-96cd-84a17c6a3227.png)

**Comment by krf** [comment]
Please copy-paste the backtrace(s) into the ticket (instead of adding screenshots of VS). That'd help!
