### ISSUE TITLE
Build error and no probe!

### ISSUE THREAD

**Issue by ysx1993** [KDAB/GammaRay#499]
![tim 20180719122938](https://user-images.githubusercontent.com/12573603/42921620-6e193132-8b4f-11e8-8be0-9d1c8de2e263.png)
![tim 20180719123114](https://user-images.githubusercontent.com/12573603/42921673-a2f9cb14-8b4f-11e8-8197-95644e8f603a.png)
Build env:
GammaRay 2.8.1
cmake 3.1.0
MSVC 2013
Qt 5.4.2

**Comment by krf** [comment]
Please post the compile/link error in text form, ideally the full output of the build.
