### ISSUE TITLE
gammaray-client.exe always crashes within start in Windows

### ISSUE THREAD

**Issue by imaki-broadsoft** [KDAB/GammaRay#510]
gammaray-client.exe always crashes almost instantly when I start it. I have tried starting it from command line with gammaray.exe (with the program to be investigated as a parameter), from the graphical UI gammaray-launcher.exe (by selecting the program to be investigated from the list) and even directly from command line by gammaray-client.exe (just to test if it's an eligible application in the first place) and the result is always the same: it crashes right after the framework of its UI window is displayed on the screen.

Gammaray git revision: f9cb19adc34684bbca56fd6eb3903e041764e742
Qt version: Slightly customized 5.9.4
Operating system: Windows 10 Enterprise 64-bit
Compiler: Microsoft Visual Studio Professional 2015, Version 14.0.25431.01 Update 3

I have a Visual Studio dump file of the crash but I could not attach it here because its size as zipped is 114 MB and the limit here appears to be 10 MB. Let me know how I can provide it.

**Comment by imaki-broadsoft** [comment]
Any update on this? I built Gammaray also in my other laptop running Windows 8.1 Pro but the exact same behavior appeared also there.

**Comment by Waqar144** [comment]
Please try with latest.
