### ISSUE TITLE
`gammaray --self-test` failed

### ISSUE THREAD

**Issue by zhang-ray** [KDAB/GammaRay#512]
I use self-build(Qt 5.11.1, msvc2015)  GammaRay 2.9.50 (revision:f9cb19ad) 

When I execute `gammaray --self-test` on Windows 10, I got these:

Error: No probes found - GammaRay not functional.
Injector windll successfully passed its self-test.
Error: Injector style failed to pass its self-test: Injector style plugin is not found in the Qt style plug-in search path or cannot be loaded.

What's more, the "Attach" and "Launch" button of GammaRay Launcher is Always disabled.
And the "Self Test" tab of Launcher is like this:
![image](https://user-images.githubusercontent.com/41682958/48046610-fe8e0400-e1cf-11e8-88fe-0ad1c81e5f5a.png)

**Comment by bjaraujo** [comment]
Same here:

![image](https://user-images.githubusercontent.com/5067963/48672965-78a97b80-eb34-11e8-908a-155ce38d7386.png)

**Comment by akreuzkamp** [comment]
Hi, thanks for reporting the issue.

All I can tell from this, is that this seems to be related to library-paths and environment variables.
Did you compile GammaRay with `-DGAMMARAY_INSTALL_QT_LAYOUT=true` or without? Did you install GammaRay and to where? You can use the cmake gui to tell. Also, what is set as `GAMMARAY_PLUGIN_INSTALL_DIR`, as `GAMMARAY_PLUGIN_VERSION` and as `GAMMARAY_PROBE_INSTALL_DIR`? You'll find these macros defined in a file `config-gammaray.h` in your build directory. Where is GammaRay installed and what is the content of the directory at `$PATH_TO_YOUR_GAMMARAY_BINARY\$GAMMARAY_INVERSE_LIB_DIR\$GAMMARAY_PLUGIN_INSTALL_DIR\GAMMARAY_PLUGIN_VERSION\` where $PATH_TO_YOUR_GAMMARAY_BINARY, well, is the path to your gammaray binary and the other variables are to be filled with the values from `config-gammaray.h`.

I'm not a windows-developer, but I think that should be the information we need to track down the issue.

**Comment by bjaraujo** [comment]
In my case:
GAMMARAY_INSTALL_QT_LAYOUT = false,
#define GAMMARAY_PLUGIN_INSTALL_DIR "plugins/gammaray"
#define GAMMARAY_LIBEXEC_INSTALL_DIR "bin"
#define GAMMARAY_BUNDLE_INSTALL_DIR ""
#define GAMMARAY_BIN_INSTALL_DIR "bin"
#define GAMMARAY_PROBE_INSTALL_DIR "plugins/gammaray/2.10/qt5_7-MSVC-140-i686"
#define GAMMARAY_TRANSLATION_INSTALL_DIR "translations"
#define GAMMARAY_QCH_INSTALL_DIR "share/doc/GammaRay"
#define GAMMARAY_TARGET_PLUGIN_INSTALL_DIR "plugins/gammaray/2.10/qt5_7-MSVC-140-i686/target"

I copied contents of GAMMARAY_PROBE_INSTALL_DIR to bin but still says no probes installed.

**Comment by Hunanmaxiang** [comment]
How to resolve?


> Ok. I ran INSTALL with administrator rights in VS and it now works. Thanks.

**Comment by jeffjiang0613** [comment]
> Ok. I ran INSTALL with administrator rights in VS and it now works. Thanks.

how to resolve?
