### ISSUE TITLE
Detecting wrong Qt ABI

### ISSUE THREAD

**Issue by aquiles2k** [KDAB/GammaRay#513]
I build current gammaray version 2.9.50 (f9cb19ad) with Qt 5.11.2 installed by their installer.

When starting gammaray and looking through the processlist my own running app is shown with ABI Qt 4.8 even though its directly build from within creator with the only configured Qt 5.11 Kit. So i cant attach to it because i only got a probe for 5.11. Launching my app directly from within gammaray ends shortly after with a injector error: process crashed. The app itself runs fine without gammaray.

Im running it inside a Kubuntu VM.

Any hints on whats wrong or what i can try to figure it out?

**Comment by akreuzkamp** [comment]
gammaray includes the two unittests `probeabitest` and `probeabidetectortest`. Could you please run them and tell us, if they work fine?
Then, the output of `ldd path/To/Your/Applications/Executable` (ideally cropped to qt-related lines) would be helpful as well as the content of `/proc/<PID of your running app>/maps` (also cropped to qt-related lines).

Finally, launching your app directly from within gammaray is another story. If that crashes, it's either a gammaray bug or (in most cases) some corner-case bug in your application that is only triggered by GammaRay (gammaray calls application-code in ways that are legal according to Qt but not necessarily the way your own code usually calls it). You can start GammaRay with `GAMMARAY_GDB=1 gammaray /path/to/your/applications/executable` to start the attached application in gdb. You can then use gdb to find the crash (use `bt` to print a backtrace, which you then can post here)

**Comment by akreuzkamp** [comment]
Ah, and then there is a `--probe <abi>` commandline option you can use to override the automatic ABI detection. Use `gammaray --list-probes` to get a list of all ABIs you installation of gammaray can attach to.

**Comment by aquiles2k** [comment]
Ok, thx for the detailed answer. Give me some time to check all the mentioned stuff :)
