### ISSUE TITLE
GammaRay for python application

### ISSUE THREAD

**Issue by weguf** [KDAB/GammaRay#515]
Hi, it's possible to use GammaRay on an application created with PyQt (or Qt for Python)?
If it is not possible, there are plans to support Qt for Python or another project that aims to poke around in a Qt-application written to python?

**Comment by akreuzkamp** [comment]
You should be able to use GammaRay for qt-based python applications as well, yes. You will, though, not have any code navigation available. Just as with C++ you will only be able to see objects in GammaRay that derive from QObject. I have no experience with PyQt or PySide, so I can't tell, how many that will be in python (it will cover at least most Qt-provided classes, though).

If you have any concrete issues with it, please post a backtrace (in case of a crash) or a detailed description including the code of a minimal test case that is able to reproduce the issue.

**Comment by anton-matosov** [comment]
I have tried it today with PyQt5 on macOS and confirm it works well with it.

**Comment by Sakthiumat** [comment]
> I have tried it today with PyQt5 on macOS and confirm it works well with it.

Hello. Can you please tell me how to use GammaRay with pyside6 QML application?
