### ISSUE TITLE
Building GammaRay 2.10.50 on Windows/MSVC 2017 "unsuitable Qt version 5.11.1" error?

### ISSUE THREAD

**Issue by loopless** [KDAB/GammaRay#522]
-- Found unsuitable Qt version "5.11.1" from D:/Qt/5.11.1/msvc2017_64/bin/qmake.exe
Qt QTDESIGNER library not found.
Qt QTSCRIPT library not found.
Qt QTSVG library not found.
Qt QTWEBKIT library not found.
Qt QTSCRIPTTOOLS library not found.
Qt QTTEST library not found.
-- Building probe for ABI: qt_-MSVC-140-x86_64 (Debug)
-- The following features have been enabled:

**Comment by loopless** [comment]
This issue can be closed ( I think). The windows PATH variable has to include the directory to qmake. Pretty confusing really that this is required.

**Comment by krf** [comment]
Note that the canonical way to find the correct Qt installation is to set the `CMAKE_PREFIX_PATH` to the Qt installation prefix. See also http://doc.qt.io/qt-5/cmake-manual.html
