### ISSUE TITLE
Issue finding QT configuraion while building for QNX 7

### ISSUE THREAD

**Issue by riahut-dot-com** [KDAB/GammaRay#530]
I discovered that there is an issue in toolchain file for QNX
That configuration step cannot find QT, with help of set(CMAKE_FIND_DEBUG_MODE 1)
I discovered that QNX_TARGET URI and anything I provide in CMAKE_PREFIX_PATH is mashing together when executing find_package command, here is the example. And obviously failing to find Qt5Core and rest of the Qt stuff.

```
-- Building GammaRay 2.10.50 (revision: 5747133) in Release mode
Checking prefix [/home/user/qnx700/target/qnx7/home/user/Qt5.7.1/5.7/gcc_64/lib/cmake/]
.... <cut> ...
CMake Error at CMakeLists.txt:361 (find_package):
  Could not find a package configuration file provided by "Qt5Core"
  (requested version 5.5) with any of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
```

After tracing all over the place I noticed this instruction in **Toolchain-QNX-common.cmake** :
LIST(APPEND CMAKE_FIND_ROOT_PATH ${QNX_TARGET})
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
This is the culprit !!!!
I suggest to you guys to remove it, I don't event know why it is there at first place

**Comment by krf** [comment]
How do you invoke CMake in the first place?

**Comment by riahut-dot-com** [comment]
Like this
`cmake -DGAMMARAY_BUILD_UI=OFF -DCMAKE_PREFIX_PATH="/opt/qt/Qt_562-700_x86-64/lib/cmake" -DCMAKE_TOOLCHAIN_FILE=/home/misha/workspace/GammaRay/cmake/Toolchain-QNX700-x86_64.cmake `

**Comment by krf** [comment]
In your case you want to to pass `-DCMAKE_FIND_ROOT_PATH=/opt/qt/Qt_562-700_x86-64`, since Qt is not inside the QNX SDK. 

Using the sysroot (in this case the QNX target install prefix) is common in toolchain files. Either install Qt *in* that directory OR prepopulate `CMAKE_FIND_ROOT_PATH` as I said before.
