### ISSUE TITLE
Crash on app launch

### ISSUE THREAD

**Issue by nicolasfella** [KDAB/GammaRay#533]
When I try to launch my app with Gammaray both crash at start. 

Qt version is 5.12.1, 5.12.0 seems fine

To reproduce:
Build https://invent.kde.org/kde/kdeconnect-kde with -DEXPERIMENTALAPP_ENABLED=True
Run 'gammaray kcapp'

It crashes with Gammaray from master, 2.10 branch works fine.

While bisecting I noticed that the backtrace changed
547bb6e3 is the last commit that works fine
Beginning with d80e7bf3 I get the following backtrace: https://phabricator.kde.org/P320
With 2d4fa14f the BT changes to https://phabricator.kde.org/P321

**Comment by Waqar144** [comment]
A new gammaray version has been released, please try again with latest.
