### ISSUE TITLE
mingw32-make on Windows: no 'void KLinkItemSelectionModel::select(const QModelIndex&, QFlags<QItemSelectionModel::SelectionFlag>)'  member function declared

### ISSUE THREAD

**Issue by p4vv37** [KDAB/GammaRay#535]
Hi,
I'm trying to build on Windows 10 with mingw-32

I'm using flag:
`-DGAMMARAY_ENFORCE_QT4_BUILD=true `

`> C:\MinGW\bin\mingw32-make.exe                                                              Scanning dependencies of target gammaray_kitemmodels_autogen                                                            [  0%] Automatic MOC and UIC for target gammaray_kitemmodels                                                            [  0%] Built target gammaray_kitemmodels_autogen                                                                        Scanning dependencies of target gammaray_kitemmodels                                                                    [  0%] Building CXX object 3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/klinkitemselectionmodel.cpp.obj             In file included from D:\gammaray-2.10.0\3rdparty\kde\klinkitemselectionmodel.cpp:22:                                   D:\gammaray-2.10.0\3rdparty\kde\/klinkitemselectionmodel.h:104: error: expected ';' before 'override'                   D:\gammaray-2.10.0\3rdparty\kde\/klinkitemselectionmodel.h:105: error: expected ';' before 'override'                   D:\gammaray-2.10.0\3rdparty\kde\/klinkitemselectionmodel.h:102: error: 'nullptr' was not declared in this scope         In file included from D:\gammaray-2.10.0\3rdparty\kde\klinkitemselectionmodel.cpp:24:                                   D:\gammaray-2.10.0\3rdparty\kde\/kmodelindexproxymapper.h:88: error: 'nullptr' was not declared in this scope           D:\gammaray-2.10.0\3rdparty\kde\klinkitemselectionmodel.cpp:80: error: no 'void KLinkItemSelectionModel::select(const QModelIndex&, QFlags<QItemSelectionModel::SelectionFlag>)' member function declared in class 'KLinkItemSelectionModel'    D:\gammaray-2.10.0\3rdparty\kde\klinkitemselectionmodel.cpp:132: error: no 'void KLinkItemSelectionModel::select(const QItemSelection&, QFlags<QItemSelectionModel::SelectionFlag>)' member function declared in class 'KLinkItemSelectionModel'3rdparty\kde\CMakeFiles\gammaray_kitemmodels.dir\build.make:62: recipe for target '3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/klinkitemselectionmodel.cpp.obj' failed                                                                     mingw32-make[2]: *** [3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/klinkitemselectionmodel.cpp.obj] Error 1         CMakeFiles\Makefile2:1004: recipe for target '3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/all' failed              mingw32-make[1]: *** [3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/all] Error 2                                     Makefile:161: recipe for target 'all' failed                                                                            mingw32-make: *** [all] Error 2   `

Issue is simmilar to:
https://github.com/KDAB/GammaRay/issues/249
But I cannot use this solution.

btw. Building with nmake had simmilar result.

**Comment by p4vv37** [comment]
I should mention: I'm using GammaRay 2.10.0 release

**Comment by shrkamat** [comment]
@p4vv37  I see this problem too with 2.10 & Qt5.4 combination

Complete build log is available here
https://gist.github.com/shrkamat/4951ca5193bbaf123e346613cc8ac334

**Comment by MarcoCallari** [comment]
Same here. Gammaray 2.10.0 + Qt 5.4.
