### ISSUE TITLE
VTK 8 is unsupported

### ISSUE THREAD

**Issue by krop** [KDAB/GammaRay#545]
VTK 8.xx is out but it can't be used to build Gammaray. the VTK build system says version 8 is not compatible with older major versions (confirmed locally):

> 
> [  270s] CMake Warning at plugins/objectvisualizer/CMakeLists.txt:26 (find_package):
> [  270s]   Could not find a configuration file for package "VTK" that is compatible
> [  270s]   with requested version "7.1".
> [  270s] 
> [  270s]   The following configuration files were considered but not accepted:
> [  270s] 
> [  270s]     /usr/lib/cmake/vtk/VTKConfig.cmake, version: 8.2.0

**Comment by krf** [comment]
That does /not/ break the build, does it? It'll just disable the objectvisualizer plugin build, right?

**Comment by krop** [comment]
Correct.

**Comment by krf** [comment]
As of b126a584b5de211dfef20462cb84d809e24b943e (part of the upcoming release 3.0.0) the VTK-based objectvisualizer plugin has been removed => VTK is no longer used.
