### ISSUE TITLE
Keep the launcher open when inspecting an application

### ISSUE THREAD

**Issue by oKcerG** [KDAB/GammaRay#557]
Hello,

When debugging my application I'd like to keep the launcher open to ease my workflow.

The current workflow is:

1. Open GammaRay Launcher
2. Wait for the list of Qt processes
3. Select App
4. Inspect App

If I then modify & rebuild my app and want to reinspect it, I have to do all the steps again (step 2 is quite time consuming : ~15 s)

I'd like to not have to do steps 1 & 2 each time, those are a pain for quick iterating.
In a second time not having to do step 3 would be a nice bonus too, automatically inspecting an app when it's restarted.

**Comment by Waqar144** [comment]
You can do `./gammaray /path/to/your_app_name` for quicker iterations.
