### ISSUE TITLE
Yama security extension is blocking runtime attaching, see /proc/sys/kernel/yama/ptrace_scope

### ISSUE THREAD

**Issue by lucaszanella** [KDAB/GammaRay#559]
Since I couldn't find anything on google, here are the errors I'm having:

```
Startup: gammaray-launcher
Detaching: /usr/local/bin/gammaray --no-inprocess --probe qt5_11-x86_64 --listen tcp://127.0.0.1 --pid 10965
Working Directory: /home/lz/GammaRay/build
Detected ABI qt5_11-x86_64, using ABI qt5_11-x86_64.
Potential errors:
  Error: gdb: Yama security extension is blocking runtime attaching, see /proc/sys/kernel/yama/ptrace_scope
  Error: lldb: The debugger executable 'lldb' could not be found

Uh-oh, there is no default attach injector on this platform.
See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting
```

**Comment by krf** [comment]
This is a security feature of the Kernel unrelated to GammaRay. It occurs when GDB (which GammaRay is internally using for grabbing a hold of other processes) attaches to non-child processes by non-root users.

https://askubuntu.com/questions/41629/after-upgrade-gdb-wont-attach-to-process gives a hint how to resolve this issue. 

It's very common to permanently allow ptracing when you're a developer (=> edit sysctl.d config files as indicated in the SO answer).

**Comment by krf** [comment]
Actually we have an entry in the Known Issues page for that, see:
https://github.com/KDAB/GammaRay/wiki/Known-Issues#gdb-method-fails-to-attach-to-running-process

**Comment by junwoo091400** [comment]
Copying solution for future references:



In Maverick Meerkat (10.10) Ubuntu introduced a patch to disallow ptracing of non-child processes by non-root users - ie. only a process which is a parent of another process can ptrace it for normal users - whilst root can still ptrace every process. Hence why you can use gdb to attach via sudo still.

You can temporarily disable this restriction (and revert to the old behaviour allowing your user to ptrace (gdb) any of their other processes) by doing:

`echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`

To permanently allow it edit `/etc/sysctl.d/10-ptrace.conf` and change the line:

`kernel.yama.ptrace_scope = 1`

To read:

`kernel.yama.ptrace_scope = 0`

**Comment by ratijas** [comment]
Mine was closed as duplicate of this one, so I'd like to ask to reopen this one instead.

Regardless of the underlying technical challenges, currently GammaRay app will just exit without any warnings or error message dialogs if it fails to attach. This is not nice for UX.

**Comment by Ashark** [comment]
Yeah, the password dialog would be nice, or at least an error window dialog linking to that Known Issue.
