### ISSUE TITLE
GammaRay not working Target not responding - timeout.

### ISSUE THREAD

**Issue by Mosa-** [KDAB/GammaRay#566]
Hello,

I have Qt 5.13 and build the master-branch by source on Windows 10.

I can't attach on a running application even with commandline, launcher or integrated in QtCreator. This error message displays:

Detected ABI qt5_13-GNU-x86_64d, using ABI qt5_13-GNU-x86_64d.
Target not responding - timeout. Try setting the env variable GAMMARAY_LAUNCHER_TIMEOUT to a bigger value (in seconds).
See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting
14:17:52: D:/Program Files (x86)/GammaRay/bin/gammaray.exe wurde mit dem Rückgabewert 1 beendet

Do you have a solution to my problem. Thanks!

**Comment by amazingmo** [comment]
Hi,
I have a similar issue.  I am on Windows, I have a locally built Qt 5.12.8 and a locally built Gammaray 2.11.

``C:\Dev\product\build\demo\src\Debug>"C:\Program Files\GammaRay\bin\gammaray.exe" -i windll --inprocess prog.exe
Detected ABI qt5_12-MSVC-140-x86_64d, using ABI qt5_12-MSVC-140-x86_64d.
Target no responding - timeout.  Try setting the env variable GAMMARAY_LAUNCHER_TIMEOUT to a bigger value (in seconds).
See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting``

I get the same response if I drop the arguments ``-i windll --inprocess`` and just use
``C:\Program Files\GammRay\bin\gammaray prog.exe``

If I start the launcher and try and start the program using out-of-process, local, then the program starts (just as in the other cases) and after a long delay (same as in the other cases) terminates.

I ran the self-tests in the launcher and all passed.
``Found valid probe for ABI qt5_12-MSVC-140-x86_64 at C:/Program Files/GammaRay/plugins/gammaray/2.11/qt5_12_MSVC-140-x86_64/gammaray_probe.dll.
Found valid probe for ABI qt5_12-MSVC-140-x86_64d at C:/Program Files/GammaRay/plugins/gammaray/2.11/qt5_12_MSVC-140-x86_64/gammaray_probed.dll.
Injector windll successfully passed its self-test.
Injector style successfully passed its self-test.``

I'm not sure how to trouble-shoot this. The faq wasn't particularly helpful.

**Comment by amazingmo** [comment]
Following on from the previous, post, using `-i style` results in a slightly different outcome:

`C:\Dev\product\build\demo\src\Debug>"C:\Program Files\GammaRay\bin\gammaray.exe" -i style prog.exe`
`Detected ABI qt5_12-MSVC-140-x86_64d, using ABI qt5_12-MSVC-140-x86_64d.`
`Target not responding - timeout. Try setting the env variable GAMMARAY_LAUNCHER_TIMEOUT to a bigger value (in seconds).`
`See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting`
`QT: QApplication: invalid style override passed, ignoring it.`
`    Available styles: windowsvista, Windows, FusionQT: libpng warning: iCCP: known incorrect sRGB profileQT: libpng warning: iCCP: known incorrect sRGB profileQT: libpng warning: iCCP: known incorrect sRGB profileQT: libpng warning: iCCP: known incorrect sRGB profileQT: libpng warning: iCCP: known incorrect sRGB profileQT: QObject::disconnect: Unexpected null parameterQT: QLayout: Attempting to add QLayout "" to MonitorParametersPanel "MONITOR_PARAMETES_PANEL_ID", which already has a layoutQT: QWidget::setLayout: Attempting to set QLayout "" on MonitorParametersPanel "MONITOR_PARAMETES_PANEL_ID", which already has a layoutQT: QLayout: Attempting to add QLayout "" to MonitorParametersPanel "MONITOR_PARAMETES_PANEL_ID", which already has a layoutQT: QWidget::setLayout: Attempting to set QLayout "" on MonitorParametersPanel "MONITOR_PARAMETES_PANEL_ID", which already has a layoutQT: QLayout: Attempting to add QLayout "" to MonitorParametersPanel "MONITOR_PARAMETES_PANEL_ID", which already has a layoutQT: QWidget::setLayout: Attempting to set QLayout "" on MonitorParametersPanel "MONITOR_PARAMETES_PANEL_ID", which already has a layout
`

Hopefully this helps.

**Comment by amazingmo** [comment]
Following up on this issue, I can see in the target application that there are four DLLs that are loaded:
* gammaray_common-qt5_12-MSVC-140-x86_64d.dll
* gammaray_core-qt5_12-MSVC-140-x86_64d.dll
* gammaray_kitemmodels-qt5_12-MSVC-140-x86_64d.dll
* gammaray_probed.dll

I also saw that there are 8 named pipes, all called "\Devices\NamedPipe\gammaray-<pid>" where the PID corresponded to Gammaray's process.  The handles were open in the target process, and also in antiVirus "avast emergency update" (AVEmUpdate.exe).
I couldn't get security details on the named pipes.

I tries to DebugBreak the target application but it just crashed.  I could attach to the target application (how I saw the loaded dlls), but by that time I had missed the interesting parts of the code.

**Comment by amazingmo** [comment]
I convinced the IT guys to turn off Avast, and the change that I see is that Gammaray is the only process that holds the named pipes open.  I'm starting to wonder if I was mistaken in my previous post.  It doesn't look like there are any TCP ports being opened.
