### ISSUE TITLE
Plugin "widget inspector" could not be loaded under Windows 10

### ISSUE THREAD

**Issue by Necr1s** [KDAB/GammaRay#568]
Hi,
I have successfully built a debug version of GammaRay 2.11.50 (rev. 085a5c7b), with Qt5.12.3 and VS2019 64bit, but when I start it with an application with existing widgets, the "Widgets" tab shows "_Plugin "< gammaray folder >/plugins/gammaray/2.12/qt5_12-MSVC-140-x86_64/gammaray_widgetinspector_ui_plugind.dll" could not be loaded_". The detected and used ABI is _ABI qt5_12-MSVC-140-x86_64d_, but the application looks in the folder without the "d" suffix. The folder exists and the plugin is available, I even tried to copy the debug plugin into this folder, without any luck. What could be the problem? I have tried it with the calculator Qt Example in the Examples/widgets/widgets as well, but it showed the same behaviour as my application. My Windows version is Windows 10 Version 1803( Build 17134.950).

**Comment by jeffjiang0613** [comment]
> Hi,
> I have successfully built a debug version of GammaRay 2.11.50 (rev. [085a5c7](https://github.com/KDAB/GammaRay/commit/085a5c7b7726e5a7638741152e60105c926976ce)), with Qt5.12.3 and VS2019 64bit, but when I start it with an application with existing widgets, the "Widgets" tab shows "_Plugin "< gammaray folder >/plugins/gammaray/2.12/qt5_12-MSVC-140-x86_64/gammaray_widgetinspector_ui_plugind.dll" could not be loaded_". The detected and used ABI is _ABI qt5_12-MSVC-140-x86_64d_, but the application looks in the folder without the "d" suffix. The folder exists and the plugin is available, I even tried to copy the debug plugin into this folder, without any luck. What could be the problem? I have tried it with the calculator Qt Example in the Examples/widgets/widgets as well, but it showed the same behaviour as my application. My Windows version is Windows 10 Version 1803( Build 17134.950).

have it been resolved?

**Comment by Necr1s** [comment]
> have it been resolved?

No. I have just built it again with the current version of GammaRay and a new Windows 10 Version 1903 (18362.778) and I get the same error.

**Comment by lorteddie** [comment]
I have the same problem: qt 5.15.2, vs2019 16.10.0 gammaray 2.11.2
for me disabling cmake option GAMMARAY_MULTI_BUILD fixed the problem

command line output:
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_signalmonitord.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_signalmonitord.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_signalmonitord.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_signalmonitord.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_signalmonitord.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_timertop_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_timertop_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_timertop_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_timertop_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_timertop_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_mimetypesd.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_mimetypesd.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_mimetypesd.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_mimetypesd.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_mimetypesd.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_localeinspector_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_localeinspector_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_localeinspector_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_localeinspector_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_localeinspector_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_eventmonitor_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_eventmonitor_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_eventmonitor_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_eventmonitor_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_eventmonitor_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_sysinfo_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_sysinfo_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_sysinfo_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_sysinfo_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_sysinfo_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_guisupportd.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_guisupportd.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_guisupportd.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_guisupportd.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_guisupportd.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_objectvisualizer_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_objectvisualizer_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_objectvisualizer_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_objectvisualizer_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_objectvisualizer_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_codecbrowser_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_codecbrowser_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_codecbrowser_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_codecbrowser_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_codecbrowser_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_networkd.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_networkd.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_networkd.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_networkd.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_networkd.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_fontbrowser_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_fontbrowser_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_fontbrowser_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_fontbrowser_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_fontbrowser_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_widgetinspector_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_widgetinspector_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_widgetinspector_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_widgetinspector_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_widgetinspector_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_translatorinspectord.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_translatorinspectord.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_translatorinspectord.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_translatorinspectord.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_translatorinspectord.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_styleinspector_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_styleinspector_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_styleinspector_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_styleinspector_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_styleinspector_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_actioninspector_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_actioninspector_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_actioninspector_plugind.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_actioninspector_plugind.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_actioninspector_plugind.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_textdocumentinspectord.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_textdocumentinspectord.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_textdocumentinspectord.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_textdocumentinspectord.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_textdocumentinspectord.dll to com.kdab.GammaRay.ToolFactory/1.0
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_modelinspectord.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_modelinspectord.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
error loading plugin V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_modelinspectord.dll: The plugin 'V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_modelinspectord.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)
Failed to cast object from V:/GammaRay-2-11-2/plugins/gammaray/2.11/qt5_15-MSVC-140-x86_64d/gammaray_modelinspectord.dll to com.kdab.GammaRay.ToolFactory/1.0

release probe is selected, application is build in release

**Comment by Necr1s** [comment]
Thanks for the advice with the GAMMARAY_MULTI_BUILD switch. The DLL still could not be loaded, but I used the "Dependency Walker" on it and I finally found the cause of this problem. It simply was missing some Qt DLLs, namely Qt53DCore, Qt53DRenderer, Qt5Quick and Qt5QML ( additional to the already provided Qt5Core and Qt5Widgets ). My guess is, that this is the same reason why it originally could not be loaded and had nothing to do with the usage of the wrong folder.

I will close this issue, since it is resolved for me and I hope that this will at least help some others to resolve their plugin issues as well.

**Comment by FMeinicke** [comment]
I recently had the same issue and just wanted to share how I resolved it. 

In my case, I had both the `C:\Qt\Tools\mingw1120_64\bin` and the `C:\Qt\5.15.2\mingw81_64\bin` folders in `PATH`. Because both folders contain some DLLs with the same name (I suspect it was `libstdc++-6.dll` in my case) the one that is found in `PATH` first is taken. And there was the problem: `libstdc++-6.dll` from `C:\Qt\Tools\mingw1120_64\bin` was not compatible with the Qt DLLs and so some symbols could not be correctly loaded leading to the Gammaray plugin not being able to be loaded.

So to solve this problem I had to put `C:\Qt\5.15.2\mingw81_64\bin` **before** `C:\Qt\Tools\mingw1120_64\bin` in `PATH`. Then the plugin could be loaded as expected.
