### ISSUE TITLE
Expired key on opensuse.org repository, need new key but where/how?

### ISSUE THREAD

**Issue by ThomasG77** [KDAB/GammaRay#572]
Using Ubuntu 18.04 64 bits, I've followed some months ago the recipe from https://github.com/KDAB/GammaRay/wiki/Getting-GammaRay#download-pre-compiled-packages
I get now the following key issue when doing `sudo apt update`

```
...
Err:29 https://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_18.04  InRelease                                                
  The following signatures were invalid: EXPKEYSIG 9E814315CDA6F441 isv:KDAB OBS Project <isv:KDAB@build.opensuse.org>
Fetched 2 699 B in 7s (361 B/s)                                                                                                     
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_18.04  InRelease: The following signatures were invalid: EXPKEYSIG 9E814315CDA6F441 isv:KDAB OBS Project <isv:KDAB@build.opensuse.org>
W: Failed to fetch https://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_18.04/InRelease  The following signatures were invalid: EXPKEYSIG 9E814315CDA6F441 isv:KDAB OBS Project <isv:KDAB@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
...
```

Thanks for your feedback

**Comment by winterz** [comment]
You can get the new key by visiting https://build.opensuse.org/project/show/isv:KDAB and pressing the "GPG Key / SSL Certificate" button. download the key  and load it into by running apt-key add.

I'm not sure how to automate that in a script yet.

**Comment by ThomasG77** [comment]
Hi,

Thanks for the pointer. I've tried with below solutions that both works:

* `wget -qO - https://build.opensuse.org/projects/isv:KDAB/public_key | sudo apt-key add -`
* `curl https://build.opensuse.org/projects/isv:KDAB/public_key | sudo apt-key add -`

If fine on your side, we may edit the content mentioned in the wiki

**Comment by winterz** [comment]
I modified the wiki to say this.  Please let me know if it works for you.

```
repo=https://download.opensuse.org/repositories/isv:/KDAB
echo "deb $repo//xUbuntu_18.04 /" | sudo tee -a /etc/apt/sources.list.d/obs.list
wget -O - $repo/public_key | sudo apt-key add -
sudo apt update
sudo apt install gammaray
```

**Comment by ThomasG77** [comment]
It does not work for below line and it's normal:

    wget -O - $repo/public_key | sudo apt-key add -

You are using `https://download.opensuse.org/repositories/isv:/KDAB/` whereas the url should be `https://build.opensuse.org/projects/isv:KDAB/`. With your code, wget try to get `https://download.opensuse.org/repositories/isv:/KDAB/public_key` and it's a 404.
From my understanding, you simply should avoid using a variable as we nearly can't reuse it. I would simply do:

```
echo "deb https://download.opensuse.org/repositories/isv:/KDAB/xUbuntu_18.04 /" | sudo tee -a /etc/apt/sources.list.d/obs.list
wget -O - https://build.opensuse.org/projects/isv:KDAB/public_key | sudo apt-key add -
sudo apt update
sudo apt install gammaray
```

**Comment by winterz** [comment]
got it. done.
thank you for pointing this out.
