### ISSUE TITLE
Memory leak in the Qt Quick 2 inspector

### ISSUE THREAD

**Issue by dangelog** [KDAB/GammaRay#590]
When using the Qt Quick 2 inspector on an application which is constantly redrawing itself (60fps) there is a memory leak somewhere that causes a memory increase in the traced application at an alarming rate (~1GB/minute on this machine). After a few minutes one risks OOM killing.

Heaptrack points to QImages being allocated in OpenGLScreenGrabber::windowAfterRendering. The code constantly allocates new images and sends copies out as a signal. I'm guessing that if the receiver of that signal is somehow throtthled, the code will keep allocating a new image per frame?

![Untitled](https://user-images.githubusercontent.com/4455745/72533305-40efae00-3875-11ea-9af5-65cb60cee667.png)

**Comment by vkrause** [comment]
Caused by the event monitor recording meta call arguments, fixed meanwhile.
