### ISSUE TITLE
Link errors while building ObjectVisualizer plugin

### ISSUE THREAD

**Issue by iquadtree** [KDAB/GammaRay#592]
Hi.

I've tried to build GammaRay today on my Ubuntu 19.04 Disco Dingo box (against Qt 5.12.2) from the most recent Git source tree. I've also installed VTK 7 to build visualizer plugin as well. However I've ran into some linker errors:

> /usr/bin/ld: CMakeFiles/gammaray_objectvisualizer_ui_plugin.dir/objectvisualizerwidget.cpp.o: in 
> function `vtkRenderingCore_AutoInit::~vtkRenderingCore_AutoInit()':
> objectvisualizerwidget.cpp:(.text._ZN25vtkRenderingCore_AutoInitD2Ev[_ZN25vtkRenderingCore_AutoInitD5Ev]+0xa): undefined reference to `vtkRenderingFreeType_AutoInit_Destruct()'
> /usr/bin/ld: CMakeFiles/gammaray_objectvisualizer_ui_plugin.dir/objectvisualizerwidget.cpp.o: in function `_GLOBAL__sub_I_objectvisualizerwidget.cpp':
> objectvisualizerwidget.cpp:(.text.startup+0x56): undefined reference to `vtkRenderingFreeType_AutoInit_Construct()'
> /usr/bin/ld: CMakeFiles/gammaray_objectvisualizer_ui_plugin.dir/vtkcontainer.cpp.o: in function `_GLOBAL__sub_I_vtkcontainer.cpp':
> vtkcontainer.cpp:(.text.startup+0x56): undefined reference to `vtkRenderingFreeType_AutoInit_Construct()'
> /usr/bin/ld: CMakeFiles/gammaray_objectvisualizer_ui_plugin.dir/vtkpanel.cpp.o: in function `GammaRay::VtkPanel::layoutChanged(int)':
> vtkpanel.cpp:(.text+0xceb): undefined reference to `vtkSpanTreeLayoutStrategy::New()'
> /usr/bin/ld: vtkpanel.cpp:(.text+0xd91): undefined reference to `vtkTreeLayoutStrategy::New()'
> /usr/bin/ld: vtkpanel.cpp:(.text+0xe5e): undefined reference to `vtkSimple2DLayoutStrategy::New()'
> /usr/bin/ld: vtkpanel.cpp:(.text+0xe71): undefined reference to `vtkForceDirectedLayoutStrategy::New()'
> /usr/bin/ld: vtkpanel.cpp:(.text+0xe91): undefined reference to `vtkForceDirectedLayoutStrategy::New()'
> /usr/bin/ld: CMakeFiles/gammaray_objectvisualizer_ui_plugin.dir/vtkpanel.cpp.o: in function `_GLOBAL__sub_I_vtkpanel.cpp':
> vtkpanel.cpp:(.text.startup+0x56): undefined reference to `vtkRenderingFreeType_AutoInit_Construct()'
> /usr/bin/ld: CMakeFiles/gammaray_objectvisualizer_ui_plugin.dir/vtkwidget.cpp.o: in function `_GLOBAL__sub_I_vtkwidget.cpp':
> vtkwidget.cpp:(.text.startup+0x56): undefined reference to `vtkRenderingFreeType_AutoInit_Construct()'
> /usr/bin/ld: CMakeFiles/gammaray_objectvisualizer_ui_plugin.dir/gammaray_objectvisualizer_ui_plugin_autogen/mocs_compilation.cpp.o: in function `_GLOBAL__sub_I_mocs_compilation.cpp':
> mocs_compilation.cpp:(.text.startup+0x56): undefined reference to `vtkRenderingFreeType_AutoInit_Construct()'
> collect2: error: ld returned 1 exit status

As I figured out some extra VTK libraries were required to fix the build: vtkRenderingFreeType and vtkInfovisLayout. The complete patch is here:

```diff
diff --git a/plugins/objectvisualizer/CMakeLists.txt b/plugins/objectvisualizer/CMakeLists.txt
index 9ab9619d..392d1685 100644
--- a/plugins/objectvisualizer/CMakeLists.txt
+++ b/plugins/objectvisualizer/CMakeLists.txt
@@ -21,6 +21,8 @@ find_path(VTK_DIR VTKConfig.cmake
   /usr/lib64/vtk /usr/lib/vtk /usr/local/lib64/vtk /usr/local/lib/vtk
 )
 set(VTK_LIBS vtkGUISupportQt
+  vtkRenderingFreeType
+  vtkInfovisLayout
   vtkViewsInfovis # vtkGraphLayoutView & friends
 )
 find_package(VTK 7.1 COMPONENTS ${VTK_LIBS} CONFIG)
```
This issue possibly related to pull request #26.

Thanks,
Dmitry

**Comment by winterz** [comment]
please see sha 1ec0790e1f6b640d436b09262309f01c0864e250 which I just committed into master and the 2.11 branches.  It includes your patch but also modifies the cmake code so we can use VTK8.

let me know if it works for you.

**Comment by iquadtree** [comment]
Yes, it compiles without link errors now. Thank you!
