### ISSUE TITLE
CMake errors. Can't build for Windows.

### ISSUE THREAD

**Issue by MCoder42** [KDAB/GammaRay#595]
Cmake: 3.16.4
Windows 10 64bit
Qt: 5.12.7

I run CMake with this command line:

`C:\000\0\GammaRay\build>cmake -DCMAKE_INSTALL_PREFIX="C:/Program Files/GammaRay12" -G "MinGW Makefiles" ..`

And Cmake produce this output with errors:

-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: C:/Qt/Tools/mingw730_64/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw730_64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/Qt/Tools/mingw730_64/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw730_64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
-- Could NOT find libbfd (missing: LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
-- BACKWARD_HAS_UNWIND=1
-- BACKWARD_HAS_BACKTRACE=0
-- BACKWARD_HAS_BACKTRACE_SYMBOL=1
-- BACKWARD_HAS_DW=0
-- BACKWARD_HAS_BFD=0
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.23.0.windows.1")
-- Building GammaRay 2.11.50 (revision: c6f32a7) in Release mode
-- Performing Test C_SUPPORTS_UNUSED_BUT_SET
-- Performing Test C_SUPPORTS_UNUSED_BUT_SET - Success
-- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET
-- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET - Success
-- Performing Test C_SUPPORTS_LOGICAL_OP
-- Performing Test C_SUPPORTS_LOGICAL_OP - Success
-- Performing Test CXX_SUPPORTS_LOGICAL_OP
-- Performing Test CXX_SUPPORTS_LOGICAL_OP - Success
-- Performing Test C_SUPPORTS_POINTER_MEMACCESS
-- Performing Test C_SUPPORTS_POINTER_MEMACCESS - Success
-- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS
-- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS - Success
-- Performing Test C_SUPPORTS_REORDER
-- Performing Test C_SUPPORTS_REORDER - Failed
-- Performing Test CXX_SUPPORTS_REORDER
-- Performing Test CXX_SUPPORTS_REORDER - Success
-- Performing Test C_SUPPORTS_FORMAT_SECURITY
-- Performing Test C_SUPPORTS_FORMAT_SECURITY - Failed
-- Performing Test CXX_SUPPORTS_FORMAT_SECURITY
-- Performing Test CXX_SUPPORTS_FORMAT_SECURITY - Failed
-- Performing Test HAVE_GXX_GNUXX11
-- Performing Test HAVE_GXX_GNUXX11 - Success
-- Performing Test HAVE_GXX_CXX11
-- Performing Test HAVE_GXX_CXX11 - Success
-- Performing Test C_SUPPORTS_ZERO_AS_NULL_POINTER_CONSTANT
-- Performing Test C_SUPPORTS_ZERO_AS_NULL_POINTER_CONSTANT - Failed
-- Performing Test CXX_SUPPORTS_ZERO_AS_NULL_POINTER_CONSTANT
-- Performing Test CXX_SUPPORTS_ZERO_AS_NULL_POINTER_CONSTANT - Success
-- Checking whether private include directories for module Core exist
-- Checking whether private include directories for module Gui exist
-- Checking whether private include directories for module Widgets exist
-- Checking whether private include directories for module Qml exist
-- Checking whether private include directories for module Quick exist
-- Checking whether private include directories for module Scxml exist
-- Looking for QT_NO_OPENGL
-- Looking for QT_NO_OPENGL - not found
-- Looking for QT_NO_PRINTER
-- Looking for QT_NO_PRINTER - not found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for backtrace
-- Looking for backtrace - not found
-- Looking for abi::__cxa_demangle
-- Looking for abi::__cxa_demangle - found
-- Building probe for ABI: qt5_12-GNU-x86_64 (Release)
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Performing Test HAVE_NO_CXX_ZERO_AS_NULL_POINTER_CON
-- Performing Test HAVE_NO_CXX_ZERO_AS_NULL_POINTER_CON - Success
-- Performing Test HAVE_NO_CXX_UNNEEDED_INTERNAL_DEC
-- Performing Test HAVE_NO_CXX_UNNEEDED_INTERNAL_DEC - Success
-- Performing Test HAVE_NO_CXX_NULL_CONVERSION
-- Performing Test HAVE_NO_CXX_NULL_CONVERSION - Success
CMake Warning (dev) at plugins/quickinspector/CMakeLists.txt:44 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "gammaray_quickinspector" has a relative
  path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test CAN_LINK_GUI_GLESV2
-- Performing Test CAN_LINK_GUI_GLESV2 - Failed
CMake Warning at plugins/objectvisualizer/CMakeLists.txt:19 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find Wayland_Server (missing: Wayland_Server_LIBRARY Wayland_Server_INCLUDE_DIR) (found version "")
-- Could NOT find Wayland (missing: Wayland_LIBRARIES Server) (Required is at least version "1.12")
CMake Warning (dev) at plugins/qmlsupport/CMakeLists.txt:21 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "gammaray_qmlsupport" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Unable to provide inheritance diagrams for the API documentation. To fix, install the graphviz project from https://www.graphviz.org
-- The following features have been enabled:

 * Option GAMMARAY_BUILD_UI, Build the GammaRay client and in-process UI.
 * Option GAMMARAY_MULTI_BUILD, Build multiple applicable probe configurations.
 * Option GAMMARAY_BUILD_CLI_INJECTOR, Build command line injector on Windows.
 * Option GAMMARAY_BUILD_DOCS, Build GammaRay documentation.
 * Widget .ui file export, Requires QtDesigner library.
 * 3D Widget Inspector, Requires Qt5 >= 5.7, Qt3D and QtQuick Controls
 * User Manual creation in qch format, Requires qdoc, qhelpgenerator, qtattributionsscanner, the qdoc templates and index files

-- The following OPTIONAL packages have been found:

 * Git
   Determine exact build version.
 * Qt53DCore (required version >= 5.12.7)
 * Qt53DAnimation
 * Qt5Gamepad (required version >= 5.12.7)
 * Qt53DExtras
 * Qt53DInput
 * Qt53DLogic
 * Qt53DRender
 * Qt53DQuick
 * Qt5Bluetooth
 * Qt5UiPlugin (required version >= 5.12.7)
 * Qt5Xml (required version >= 5.12.7)
 * Qt5Designer
 * Qt5PositioningQuick (required version >= 5.12.7)
 * Qt5Location
 * Qt5Positioning
 * Qt5PrintSupport
   Required for widget PDF export.
 * Qt5Qml
 * Qt5Quick
 * Qt5QuickWidgets
 * Qt5Svg
   Required for widget SVG export.
 * Qt5Test
 * Qt5Scxml (required version >= 5.8)
 * Qt5Sql (required version >= 5.12.7)
 * Qt5Help
 * Qt5LinguistTools
 * QmlLint, <https://qt.io>
   Validate QML code.

-- The following RECOMMENDED packages have been found:

 * Qt5Concurrent
   Required for the GammaRay launcher process list.

-- The following REQUIRED packages have been found:

 * Qt5Core (required version >= 5.5)
 * Qt5Gui
 * Qt5Network
 * Qt5Widgets
 * Qt5, <https://qt.io/>

-- The following features have been disabled:

 * Option GAMMARAY_PROBE_ONLY_BUILD, Build only an additional probe configuration for an already existing launcher.
 * Option GAMMARAY_CLIENT_ONLY_BUILD, Build the client part only.
 * Option GAMMARAY_ENABLE_GPL_ONLY_FEATURES, Enable features only available under GPL license.
 * Option GAMMARAY_INSTALL_QT_LAYOUT, Install into Qt directory layout.
 * Option GAMMARAY_STATIC_PROBE, Build the probe as static library for compile-time injection.
 * Option GAMMARAY_ENFORCE_QT_ASSERTS, Force QT_ASSERT in all builds.
 * Option GAMMARAY_DISABLE_FEEDBACK, Disable user feedback support.
 * Option GAMMARAY_CORE_ONLY_LAUNCHER, Only use QtCore in the CLI launcher (breaks style injector, but is needed for Boot2Qt compatibility)
 * QtScript debugger, Requires QtScript and QtScriptTools.
 * ELF ABI detection, Automatic probe ABI detection on ELF-based systems. Requires elf.h.

-- The following OPTIONAL packages have not been found:

 * Qt5AndroidExtras
 * Qt5Script
 * Qt5ScriptTools
 * Qt5WebEngineWidgets
 * Qt5WaylandCompositor
 * Qt5IviCore (required version >= 1.1)
 * Qt5IviVehicleFunctions (required version >= 1.1)
 * Qt5IviMedia (required version >= 1.1)
 * Glslang, <https://github.com/KhronosGroup/glslang>
   Validate GL shader code.
 * KF5CoreAddons, KDE KCoreAddons Framework, <https://www.kde.org/>
   Required for the KJob tracker plug-in.
 * VTK, Visualization Toolkit, <https://www.vtk.org>
   Needed for the object visualizer plugin (required Qt5). Just for toying around, highly experimental plugin.
 * PkgConfig
 * Wayland (required version >= 1.12), C library implementation of the Wayland protocol: a protocol for a compositor to talk to its clients, <http://wayland.freedesktop.org>
   Needed for the QtWayland compositor inspector plug-in.
 * Doxygen, API Documentation system, <http://www.doxygen.org>
   Needed to build the API documentation.

-- The following RECOMMENDED packages have not been found:

 * KF5SyntaxHighlighting (required version >= 5.28), <https://www.kde.org/>
   Syntax highlighting for code editor.
 * KDSME (required version >= 1.2), KDAB State Machine Editor framework, <https://github.com/KDAB/KDStateMachineEditor>
   Graphical state machine debugging.

-- Configuring done
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/codecbrowser/moc_C:/000/0/GammaRay/build/plugins/codecbrowser/codecbrowser.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/codecbrowser/moc_C:/000/0/GammaRay/build/plugins/codecbrowser/codecbrowserwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/eventmonitor/moc_C:/000/0/GammaRay/build/plugins/eventmonitor/eventmonitor.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/eventmonitor/moc_C:/000/0/GammaRay/build/plugins/eventmonitor/eventmonitorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/fontbrowser/moc_C:/000/0/GammaRay/build/plugins/fontbrowser/fontbrowser.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/fontbrowser/moc_C:/000/0/GammaRay/build/plugins/fontbrowser/fontbrowserwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/kjobtracker/moc_C:/000/0/GammaRay/build/plugins/kjobtracker/kjobtrackerwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/localeinspector/moc_C:/000/0/GammaRay/build/plugins/localeinspector/localeinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/localeinspector/moc_C:/000/0/GammaRay/build/plugins/localeinspector/localeinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/modelinspector/moc_C:/000/0/GammaRay/build/plugins/modelinspector/modelinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/modelinspector/moc_C:/000/0/GammaRay/build/plugins/modelinspector/modelinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/quickinspector/moc_C:/000/0/GammaRay/build/plugins/quickinspector/quickinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/quickinspector/moc_C:/000/0/GammaRay/build/plugins/quickinspector/quickinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/signalmonitor/moc_C:/000/0/GammaRay/build/plugins/signalmonitor/signalmonitor.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/signalmonitor/moc_C:/000/0/GammaRay/build/plugins/signalmonitor/signalmonitorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/statemachineviewer/moc_C:/000/0/GammaRay/build/plugins/statemachineviewer/statemachineviewerserver.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/timertop/moc_C:/000/0/GammaRay/build/plugins/timertop/timertop.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/timertop/moc_C:/000/0/GammaRay/build/plugins/timertop/timertopwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/mimetypes/moc_C:/000/0/GammaRay/build/plugins/mimetypes/mimetypes.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/mimetypes/moc_C:/000/0/GammaRay/build/plugins/mimetypes/mimetypeswidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/network/moc_C:/000/0/GammaRay/build/plugins/network/networksupport.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/network/moc_C:/000/0/GammaRay/build/plugins/network/networkwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/objectvisualizer/moc_C:/000/0/GammaRay/build/plugins/objectvisualizer/objectvisualizer.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/qtivi/moc_C:/000/0/GammaRay/build/plugins/qtivi/qtivisupportwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/sysinfo/moc_C:/000/0/GammaRay/build/plugins/sysinfo/sysinfo.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/sysinfo/moc_C:/000/0/GammaRay/build/plugins/sysinfo/sysinfowidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/translatorinspector/moc_C:/000/0/GammaRay/build/plugins/translatorinspector/translatorinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/translatorinspector/moc_C:/000/0/GammaRay/build/plugins/translatorinspector/translatorinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/webinspector/moc_C:/000/0/GammaRay/build/plugins/webinspector/webinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/wlcompositorinspector/moc_C:/000/0/GammaRay/build/plugins/wlcompositorinspector/inspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/guisupport/moc_C:/000/0/GammaRay/build/plugins/guisupport/guisupport.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/guisupport/moc_C:/000/0/GammaRay/build/plugins/guisupport/guisupportuifactory.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/textdocumentinspector/moc_C:/000/0/GammaRay/build/plugins/textdocumentinspector/textdocumentinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/textdocumentinspector/moc_C:/000/0/GammaRay/build/plugins/textdocumentinspector/textdocumentinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/actioninspector/moc_C:/000/0/GammaRay/build/plugins/actioninspector/actioninspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/actioninspector/moc_C:/000/0/GammaRay/build/plugins/actioninspector/actioninspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/widgetinspector/moc_C:/000/0/GammaRay/build/plugins/widgetinspector/widgetinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/widgetinspector/moc_C:/000/0/GammaRay/build/plugins/widgetinspector/widgetinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/sceneinspector/moc_C:/000/0/GammaRay/build/plugins/sceneinspector/sceneinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/sceneinspector/moc_C:/000/0/GammaRay/build/plugins/sceneinspector/sceneinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/styleinspector/moc_C:/000/0/GammaRay/build/plugins/styleinspector/styleinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/styleinspector/moc_C:/000/0/GammaRay/build/plugins/styleinspector/styleinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/qmlsupport/moc_C:/000/0/GammaRay/build/plugins/qmlsupport/qmlsupport.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/qmlsupport/moc_C:/000/0/GammaRay/build/plugins/qmlsupport/qmlsupportuifactory.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/quickwidgetsupport/moc_C:/000/0/GammaRay/build/plugins/quickwidgetsupport/quickwidgetsupport.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/bluetooth/moc_C:/000/0/GammaRay/build/plugins/bluetooth/bluetooth.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/positioning/moc_C:/000/0/GammaRay/build/plugins/positioning/positioning.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/positioning/moc_C:/000/0/GammaRay/build/plugins/positioning/positioningwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/qt3dinspector/moc_C:/000/0/GammaRay/build/plugins/qt3dinspector/3dinspector.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
CMake Error: Cannot open file for write: C:/000/0/GammaRay/build/plugins/qt3dinspector/moc_C:/000/0/GammaRay/build/plugins/qt3dinspector/qt3dinspectorwidget.cpp_parameters_Release.tmp
CMake Error: : System Error: Invalid argument
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by vkrause** [comment]
That's a regression in Qt 5.12.7 (qtbase:89bd5a7e733a64b694abf16b8d227dbbdd2d3ef7), that broke CMake builds in general. The fix is already in what will become Qt 5.12.8 (qtbase:8a3fde00bf53d99e9e4853e8ab97b0e1bcf74915). Nothing we can do about this in GammaRay unfortunately.

**Comment by MCoder42** [comment]
Ok. Thank you! I'will wait new version of Qt.
