### ISSUE TITLE
Cannot build on Windows 10 due to cmake errors

### ISSUE THREAD

**Issue by dbaudiotechnik** [KDAB/GammaRay#597]
When trying to build GammaRay on Windows 10, using NMake Makefiles, the configuration succeeds, but the generation step fails. Following setup:

* Windows 10
* Qt 5.12.7
* MSVC 2017 x86
* CMake 3.17.0-rc3

It seems as the automoc generates moc files with the full absolute path in the name of the file.
Please see the build log attached:  [GammaRay_build.txt](https://github.com/KDAB/GammaRay/files/4349366/GammaRay_build.txt)

**Comment by krf** [comment]
Did you try a released CMake version? This is very likely an issue in CMake.

**Comment by dbaudiotechnik** [comment]
Thank you for the fast support. I am now using CMake 3.16.5 and I also removed the previous GammaRay folder and did a fresh clone. Unfortunately, I still receive the same errors: 
[GammaRay_build_CMake_Release.txt](https://github.com/KDAB/GammaRay/files/4353156/GammaRay_build_CMake_Release.txt)

**Comment by krf** [comment]
I just tried to reproduce, with almost the same setup (just that I'm using Qt 5.14.0): Works fine for me.

Are you using some special setup where things like hard links or junctions are involved, by any chance?

**Comment by dbaudiotechnik** [comment]
The setup is quite ordinary and straigth forward, but I can remember that it still worked with Qt 5.12.1 a few months ago. Maybe this is indeed related to Qt 5.12.7.

**Comment by krf** [comment]
Ah, indeed, I assumed it cannot be related to the Qt version, since GammaRay is using CMake's AUTOMOC exclusively. But this isn't true, we're also using Qt5's `qt5_wrap_cpp` CMake macro; thus the Qt version matters.

It's a bug in Qt 5.12.7:
  https://bugreports.qt.io/browse/QTBUG-82014

Please try downgrading or upgrading the Qt version.

**Comment by krf** [comment]
Same issue reported here, by the way: #595

**Comment by dbaudiotechnik** [comment]
Ok, thanks. We found a couple other bugs and might move on to the next Qt version early now.

**Comment by krf** [comment]
Feel free to contact us if you need further help with GammaRay.

Thanks.
