### ISSUE TITLE
Linker issues when buiding in Ubuntu 20.04.1 

### ISSUE THREAD

**Issue by freaf87** [KDAB/GammaRay#609]
Hi guys,
I am having some strange issues when building GammaRay on Ubuntu  20.04.1 . Almost at the end I get some linker errors which I really do not understand. I build it on the console and also in Qt 5.15.0 64 bits. Same issue. My Qt Cmake version is 3.17.1. Please find attached my build Log
[buildLog.txt](https://github.com/KDAB/GammaRay/files/5160911/buildLog.txt)
Can someone please tell me what is missing ?
Thanks in advance

**Comment by vkrause** [comment]
This seems to be a bug in the official Qt binaries: https://bugreports.qt.io/browse/QTBUG-80964

The only thing you can do on the GammaRay side to work around this is to disable building the QtWebEngine support by commenting out the corresponding line in plugins/CMakeLists.txt (`add_subdirectory(webinspector)`).
