### ISSUE TITLE
Unable to see the Event monitor 

### ISSUE THREAD

**Issue by thawfeekyahya** [KDAB/GammaRay#625]
Hi,

Where is the event monitor and how can I view it . I read this page https://doc.qt.io/GammaRay/gammaray-event-monitor.html . But I am unable to see it in Gammaray.

Gammray version 2.11
Qt version 5.12

**Comment by chsterz** [comment]
Hi. 
Normally, it should show up as a plugin on the left side of your Gammaray main Window.
![Screenshot from 2021-03-15 09-28-20](https://user-images.githubusercontent.com/315665/111124719-1c728d00-8571-11eb-8238-fd349afeca93.png)

Screenshotted inspecting QtCreator with Gammaray 2.11.50, probably Qt 5.15
The 2.11.0 release should have the Events Plugin.

You can check if the plugin exists in your installation by searching for the names like
`gammaray_eventmonitor_plugin.so`
or 
`gammaray_eventmonitor_ui_plugin.so`

in your Gammaray Installation. 
(was in `/usr/local/lib/gammaray/<version>/<qtversion>/` for me)

Then try it on a regular QtApplication, such as `gammaray qtcreator` and watch the debug output.

**Comment by thawfeekyahya** [comment]
Hi @chsterz ,

Thanks for the reply . Looks like my git branch was not checked out properly now I can see the events tab. But the application crashes now ,

qt/qtbase/src/corelib/kernel/qmetatype.cpp:1166 (default) QMetaType::registerType: Binary compatibility break. 
Type flags for type 'const QObject*' [39] don't match. Previously registered TypeFlags(0xc), now registering TypeFlags(0x104). 
cannot call method fatalMessageReceived on unknown object of name com.kdab.GammaRay.MessageHandler with address 78 - did you forget to register it?
Cannot dispatch message 31 - no handler registered. Receiver: com.kdab.GammaRay.MessageHandler, address 78

I am using Qt 5.12.9 . My project and Gammray are compiled using the same Qt .   Any suggestions ?

Thanks ,
