### ISSUE TITLE
Cannot nmake or mingw32-make on Windows 10

### ISSUE THREAD

**Issue by osjason** [KDAB/GammaRay#626]
I'm trying to build GammaRay on Windows 10, using NMake Makefiles too.But I can't run "nmake" or "mingw32-make" successful.
Following setup:
- Windows 10
- Qt 5.15.2
- MSVC 2019 x64
- Mingw W64-builds-4.3.5
- CMake 3.20.0-rc3

Please see the build log attached:
[my_GammaRay_build..txt](https://github.com/KDAB/GammaRay/files/6149077/my_GammaRay_build.txt)

**Comment by frazzyfin** [comment]
I'm also having this same issue

**Comment by Waqar144** [comment]
Please try with latest master
