### ISSUE TITLE
GammaRay installs into deprecated metadata path /usr/share/appdata

### ISSUE THREAD

**Issue by telans** [KDAB/GammaRay#633]
`/usr/share/appdata/` is a legacy location and should be updated to `/usr/share/metainfo/`

See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location

Thanks

**Comment by winterz** [comment]
while I'm at.. do you know if it would be safe/recommended to rename GammaRay.appdata.xml to com.kdab.GammaRay.metainfo.xml?

**Comment by telans** [comment]
Yes, see here: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic

" The ID must follow a reverse-DNS scheme, consisting of {tld}.{vendor}.{product}, for example org.kde.gwenview or com.hugski.colorhug2. Ownership of {vendor}.{tld} in the domain name system guarantees uniqueness of IDs.

To increase the uniqueness and to distinguish between different pieces of a software suite, it is suggested to append the type name to the component-id in these cases. For example, one can use com.hugski.colorhug2 for the client tools to control hardware, and com.hugski.colorhug2.firmware for the runtime firmware files. "

**Comment by telans** [comment]
I'm not sure about any consequences from renaming, but the docs do say a different naming sceme is required:

"The ID must follow a reverse-DNS scheme, consisting of {tld}.{vendor}.{product}, for example org.kde.gwenview or com.hugski.colorhug2"

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic

**Comment by telans** [comment]
I'm not sure about any consequences of renaming but I imagine it wouldn't hurt anything.

**Comment by winterz** [comment]
done in d098d9d6282ef1b84cde26ae256a24b4bb293189
