### ISSUE TITLE
Offer to persist logging categories

### ISSUE THREAD

**Issue by jesperkdab** [KDAB/GammaRay#651]
The syntax for the logging categories can be challenging, and Gammaray shows it so nicely for me with checkboxes.
So it would be cool, if it could write the correct lines to the qtlogging.ini file or offer me a env var export.

Something like this: I've made some changes, and then press a "give me an env var for this" and it would copy the correct incarnation on my clipboard. Or save changes to qtlogging.ini pushbutton which would do so

**Comment by dantti** [comment]
feature was merged
