### ISSUE TITLE
Unable to attach to a running application

### ISSUE THREAD

**Issue by thawfeekyahya** [KDAB/GammaRay#655]
Hi ,

I am trying to attach gammray to running qt application, but gammaray fails to attach and the application crashes.

Gammaray and the application both are compiled with same Qt version.

This is the error from Gammaray 
`cannot call method fatalMessageReceived on unknown object of name com.kdab.GammaRay.MessageHandler with address 71 - did you forget to register it?
Cannot dispatch message 31 - no handler registered. Receiver: com.kdab.GammaRay.MessageHandler, address 71
`

and this back trace log from application after the crash,

`QFatal in Qt Application Manager (/home/osboxes/qt_path/bin/appman)
START BACKTRACE:
1	QMessageLogger::fatal(char const*, ...) const ()
2	/home/osboxes/qt_path/lib/libQt5Core.so.5 ()
3	QMetaType::registerNormalizedType(QByteArray const&, void (*)(void*), void* (*)(void*, void const*), int, QFlags<QMetaType::TypeFlag>, QMetaObject const*) ()
4	/home/osboxes/build_Gammaray/lib/libgammaray_core-qt5_15-x86_64.so.2.11.1 ()
5	GammaRay::AggregatedPropertyModel::rowCount(QModelIndex const&) const ()
6	/home/osboxes/build_Gammaray/lib/libgammaray_core-qt5_15-x86_64.so.2.11.1 ()
7	QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const ()
8	GammaRay::Endpoint::dispatchMessage(GammaRay::Message const&) ()
9	GammaRay::Endpoint::readyRead() ()
10	/home/osboxes/qt_path/lib/libQt5Core.so.5 ()
11	QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()
12	QIODevice::readyRead() ()
13	/home/osboxes/qt_path/lib/libQt5Network.so.5 ()
14	/home/osboxes/qt_path/lib/libQt5Network.so.5 ()
15	/home/osboxes/qt_path/lib/libQt5Network.so.5 ()
16	/home/osboxes/qt_path/lib/libQt5Network.so.5 ()
17	/home/osboxes/qt_path/lib/libQt5Network.so.5 ()
18	QCoreApplicationPrivate::notify_helper(QObject*, QEvent*) ()
19	/home/osboxes/qt_path/lib/libQt5Core.so.5 ()
20	QCoreApplication::notify(QObject*, QEvent*) ()
21	QGuiApplication::notify(QObject*, QEvent*) ()
22	QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
23	QCoreApplication::sendEvent(QObject*, QEvent*) ()
24	/home/osboxes/qt_path/lib/libQt5Core.so.5 ()
25	g_main_context_dispatch ()
26	/lib/x86_64-linux-gnu/libglib-2.0.so.0 ()
27	g_main_context_iteration ()
28	QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
29	/home/osboxes/qt_path/lib/libQt5XcbQpa.so.5 ()
30	QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
31	QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
32	QCoreApplication::exec() ()
33	QGuiApplication::exec() ()
34	/home/osboxes/qt_path/bin/appman ()
35	__libc_start_main ()
36	/home/osboxes/qt_path/bin/appman ()
37	[0xffffffffffffffff] ()
END BACKTRACE
[FATL | default] QMetaType::registerType: Binary compatibility break. 
Type flags for type 'const QObject*' [39] don't match. Previously registered TypeFlags(0xc), now registering TypeFlags(0x104).                               [qmetatype.cpp:1215]

*** process /home/osboxes/qt_path/bin/appman (8843) crashed *`

Thanks ,

**Comment by Waqar144** [comment]
This is not reproducible with few tries I made. Please reopen if it is still reproducible with latest master.
