### ISSUE TITLE
Nice virus there

### ISSUE THREAD

**Issue by megapro17** [KDAB/GammaRay#658]
![image](https://user-images.githubusercontent.com/16743370/141708423-3f437d61-d6cb-48e0-ac27-302041e5722c.png)
This windows build link leads to a zip with rat or remote desktop software https://www.virustotal.com/gui/file/5eaf9684a6f80fcd59aa00228cb5379ec3f026438b3ccdd8d26b25a6f4b53b97

**Comment by dantti** [comment]
@winterz seems like we should "Restrict editing to users in teams with push access only" on Wiki pages...

**Comment by megapro17** [comment]
and users can't even suggest to any edits to wiki, it's completely restricted. it's a bad choice
