### ISSUE TITLE
crash when inspected qml application's models 

### ISSUE THREAD

**Issue by nocanstillbb** [KDAB/GammaRay#659]
![image](https://user-images.githubusercontent.com/22405678/144742139-cf39b902-f035-4593-80e1-cc8ed72e2223.png)

actualy , my struct  has not role enum, i don't know it whether is a resaon

![image](https://user-images.githubusercontent.com/22405678/144742196-b3d6d0ff-abd2-4b11-9e63-46ab764e1a15.png)

my qt version is 5.15.2, 
my kits is msvc 2019 64bit
my gammaray  version is 2.99.50 
![image](https://user-images.githubusercontent.com/22405678/144742438-3cd749d1-7328-42e6-bfbb-09fcaff3816c.png)

**Comment by Waqar144** [comment]
Hi, thanks for reporting.

Maybe you have a backtrace of the crash or instructions to reproduce?
