### ISSUE TITLE
Injector lldb failed to pass its self-test: The debugger version can't be read (lldb version 13.0.0).

### ISSUE THREAD

**Issue by sbela** [KDAB/GammaRay#673]
On $ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
with gammaray 2.11.2-2ubuntu1
I have this error on Self Test tab : Injector lldb failed to pass its self-test: The debugger version can't be read (lldb version 13.0.0).
Which I think is kind of funny :)

**Comment by winterz** [comment]
can you be more specific?

**Comment by mattkdab** [comment]
@sbela This is the same issue as #616 which was fixed in version 2.11.3 with [this commit](https://github.com/KDAB/GammaRay/commit/2d0aad3e6aeb1c92ddea1d747d1d64e9e12a33b5). To resolve this, you'll need a newer version of GammaRay than the Ubuntu package gives you.
