### ISSUE TITLE
After quitting GammaRay client, red outline remains on an inspected widget

### ISSUE THREAD

**Issue by ratijas** [KDAB/GammaRay#681]
### Summary

GammaRay client does not clean up the red outline which represents the currently focused widget in the inspector.

### Steps to reproduce

1. Open GammaRay launcher.
2. Attach or launch an app, for example System Settings of Plasma.
3. Go to Widgets tab.
4. Select some widget in a window, e.g. left panel in Sidebar View.
5. Quit GammaRay client.

### Observed result

Red outline remains until widget is destroyed (either by quitting the app, or changing the view mode etc.)

![GammaRay inspector - red outline remains](https://user-images.githubusercontent.com/6737986/153748432-a5d0069d-2133-45a3-871f-3d425321928b.png)

### Expected result

GammaRay should delete the outline on exit.

**Comment by Waqar144** [comment]
https://github.com/KDAB/GammaRay/pull/692
