### ISSUE TITLE
Mark object as favorite, across views

### ISSUE THREAD

**Issue by AndreSomers** [KDAB/GammaRay#690]
Sometimes while debugging, you need to jump back and forth between some objects. Or, you need to view the signals of some objects in relation to each other. However, finding these objects in the forest of objects alive can be tricky sometimes, and getting them onto the same view in the signals view may even be impossible. 

I would suggest a feature where you can mark objects you want to monitor or need to come back to as a favorite (or "object-of-interest" or something like that), which would then show these objects in a separate section on the top of each view where these objects occur (so, places like Models, Objects, Qt Quick view...). I would envision this to be a separate view above the tree view with the same columns (synchronized in width with the main tree) that vertically scrolls independently from the tree. The favorites would still _also_ appear in the trees ofc, and selecting them from the list of favorites would also select (and ensure visible) in the main tree view so you can easily see the objects context. The separate favorites view does not need to appear when there are no favorites as to not take up more space than needed.

**Comment by Waqar144** [comment]
https://github.com/KDAB/GammaRay/pull/704
