### ISSUE TITLE
Signals view zooming with mouse

### ISSUE THREAD

**Issue by AndreSomers** [KDAB/GammaRay#691]
I find the zooming in the Signals view to be hard to use. Currently, if you see some cluster of signals you're interested in introspecting in more detail and you zoom in, probably the signals you're interested in scroll out of view and you have no idea where they wend. I would like to be able to zoom with the mouse wheel instead, in such a way that the view stays centered on the position you over while zooming. This would make it much easier to use than it currently is.

**Comment by Waqar144** [comment]
https://github.com/KDAB/GammaRay/pull/703
