### ISSUE TITLE
PVS-Studio issues

### ISSUE THREAD

**Issue by nmariusp** [KDAB/GammaRay#705]
I have Kubuntu 22.04. I have installed Qt5 using kdesrc-build. I have built https://github.com/KDAB/GammaRay using this Qt. Pseudocode:

Build https://github.com/KDAB/KDStateMachineEditor first, install into /home/n/kde/usr.
git clone https://github.com/KDAB/GammaRay
cd GammaRay && mkdir build && cd build

export CMAKE_PREFIX_PATH=/home/n/kde/qt5:/home/n/kde/usr
export XDG_DATA_DIRS=/home/n/kde/usr/share:/usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop
export PKG_CONFIG_PATH=/home/n/kde/usr/lib/pkgconfig:/home/n/kde/qt5/lib/pkgconfig
export PATH=/home/n/kde/usr/bin:/home/n/kde/qt5/bin:/home/n/kde/src/kdesrc-build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
export CMAKE_MODULE_PATH=/home/n/kde/qt5/lib/cmake:/home/n/kde/usr/lib64/cmake:/home/n/kde/usr/lib/cmake
export LD_LIBRARY_PATH=/home/n/kde/usr/lib:/home/n/kde/qt5/lib

cmake -B . -S .. -G Unix\ Makefiles -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS:STRING=-pipe -DCMAKE_INSTALL_PREFIX=/home/n/kde/usr -DCMAKE_PREFIX_PATH=/home/n/kde/qt5
pvs-studio-analyzer trace -- make # Instead of make -j `nproc`

pvs-studio-analyzer analyze -l /path/to/PVS-Studio.lic -o PVS-Studio.log

plog-converter -a GA:1,2 -d V1042,V1053,V1044 -t tasklist -o report.tasks PVS-Studio.log

The file report.tasks can be opened with Qt Creator. File > Open File or Project. It will be shown in the "Issues" Output Pane (Alt+1).

Below is the file report.tasks:

pvs-studio.com/en/docs/warnings/	1	err	Help: The documentation for all analyzer warnings is available here: https://pvs-studio.com/en/docs/warnings/.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionlexer.cpp	1307	warn	V1048 The '* yyg->yy_c_buf_p' variable was assigned the same value.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionlexer.cpp	1405	warn	V1004 The 'yyg->yy_buffer_stack' pointer was used unsafely after it was verified against nullptr. Check lines: 1394, 1405.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionlexer.cpp	1558	warn	V1004 The 'yyg->yy_buffer_stack' pointer was used unsafely after it was verified against nullptr. Check lines: 1547, 1558.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionlexer.cpp	1575	warn	V547 Expression 'yyg->yy_buffer_stack' is always true.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionlexer.cpp	1580	warn	V547 Expression 'yyg->yy_buffer_stack' is always true.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionlexer.cpp	2010	warn	V547 Expression 'yyg->yy_buffer_stack' is always true.
/home/n/kde/misc/GammaRay/3rdparty/kuserfeedback/common/surveytargetexpressionlexer.cpp	1	err	V011 Presence of #line directives may cause some diagnostic messages to have incorrect file name and line number.
/home/n/kde/misc/GammaRay/3rdparty/kuserfeedback/common/surveytargetexpressionparser_p.h	47	err	V011 Presence of #line directives may cause some diagnostic messages to have incorrect file name and line number.
/home/n/kde/misc/GammaRay/3rdparty/kuserfeedback/common/surveytargetexpressionparser.cpp	27	warn	V575 The potential null pointer is passed into 'memset' function. Inspect the first argument. Check lines: 27, 26.
/home/n/kde/misc/GammaRay/3rdparty/kuserfeedback/common/surveytargetexpressionparser.cpp	35	warn	V522 There might be dereferencing of a potential null pointer 'outIt'. Check lines: 35, 26.
/home/n/kde/misc/GammaRay/3rdparty/kuserfeedback/common/surveytargetexpressionscanner.h	5	err	V011 Presence of #line directives may cause some diagnostic messages to have incorrect file name and line number.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionparser.y	91	warn	V1037 Two or more case-branches perform the same actions. Check lines: 91, 91, 91
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionparser.y	90	warn	V1037 Two or more case-branches perform the same actions. Check lines: 90, 90
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionparser_p.cpp	1219	warn	V592 The expression was enclosed by parentheses twice: ((expression)). One pair of parentheses is unnecessary or misprint is present.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionparser_p.cpp	1289	warn	V1048 The 'yyn' variable was assigned the same value.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionparser_p.cpp	1492	warn	V557 Array underrun is possible. The value of 'yylhs' index could reach -21.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionparser_p.cpp	1495	warn	V557 Array underrun is possible. The value of 'yylhs' index could reach -21.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/surveytargetexpressionparser_p.cpp	1605	warn	V560 A part of conditional expression is always true: yyn <= 43.
/home/n/kde/misc/GammaRay/3rdparty/kuserfeedback/common/surveytargetexpressionparser_p.cpp	69	err	V011 Presence of #line directives may cause some diagnostic messages to have incorrect file name and line number.
/home/n/kde/misc/GammaRay/3rdparty/lz4/lz4.c	1145	err	V562 It's odd to compare 0 or 1 with a value of 0: (outputSize == 0) != 0.
/home/n/kde/misc/GammaRay/3rdparty/lz4/lz4.c	1146	err	V562 It's odd to compare 0 or 1 with a value of 0: (outputSize == 0) != 0.
/home/n/kde/misc/GammaRay/3rdparty/lz4/lz4.c	1478	warn	V522 Dereferencing of the null pointer 'lz4ds' might take place. The potential null pointer is passed into 'LZ4_init' function. Inspect the first argument. Check lines: 1478, 1492, 1491.
/home/n/kde/misc/GammaRay/3rdparty/qt/5.5/private/qpaintbuffer_p.h	314	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: d, painter.
/home/n/kde/misc/GammaRay/3rdparty/qt/5.5/private/qpaintbuffer.cpp	571	err	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: m_unused, m_created_state.
/home/n/kde/misc/GammaRay/build/3rdparty/kuserfeedback/gammaray_kuserfeedback_autogen/TAC5DWH4SE/moc_feedbackconfiguicontroller.cpp	172	warn	V1037 Two or more case-branches perform the same actions. Check lines: 172, 179, 186
/home/n/kde/misc/GammaRay/build/core/gammaray_core_autogen/EWIEGA46WW/moc_toolmanager.cpp	92	warn	V1037 Two or more case-branches perform the same actions. Check lines: 92, 99
/home/n/kde/misc/GammaRay/build/plugins/quickinspector/gammaray_quickinspector_autogen/H2ACTYRFZH/moc_qsgtexturegrabber.cpp	106	warn	V1037 Two or more case-branches perform the same actions. Check lines: 106, 113
/home/n/kde/misc/GammaRay/build/plugins/statemachineviewer/gammaray_statemachineviewer_plugin_autogen/EWIEGA46WW/moc_statemachineviewerinterface.cpp	190	warn	V1037 Two or more case-branches perform the same actions. Check lines: 190, 197
/home/n/kde/misc/GammaRay/build/plugins/statemachineviewer/gammaray_statemachineviewer_ui_plugin_autogen/EWIEGA46WW/moc_statemachineviewerinterface.cpp	190	warn	V1037 Two or more case-branches perform the same actions. Check lines: 190, 197
/home/n/kde/qt5/include/QtCore/qglobal.h	274	warn	V677 Custom declaration of a standard 'ushort' type. The declaration from system header files should be used instead.
/home/n/kde/qt5/include/QtCore/qglobal.h	275	warn	V677 Custom declaration of a standard 'uint' type. The declaration from system header files should be used instead.
/home/n/kde/qt5/include/QtCore/qglobal.h	276	warn	V677 Custom declaration of a standard 'ulong' type. The declaration from system header files should be used instead.
/home/n/kde/qt5/include/QtCore/qarraydata.h	133	warn	V690 The 'iterator' class implements a copy constructor, but lacks the copy assignment operator. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtCore/qarraydata.h	168	warn	V690 The 'const_iterator' class implements a copy constructor, but lacks the copy assignment operator. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtCore/qvector.h	609	err	V623 Consider inspecting the '?:' operator. A temporary object of the 'iterator' type is being created and subsequently destroyed. Check third operand.
/home/n/kde/qt5/include/QtCore/qregexp.h	58	warn	V690 The 'QRegExp' class implements the move assignment operator, but lacks a move constructor. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtCore/qstringlist.h	54	warn	V690 The 'QRegExp' class implements the move assignment operator, but lacks a move constructor. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtCore/qmetatype.h	2089	warn	V690 The 'QRegExp' class implements the move assignment operator, but lacks a move constructor. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtCore/qobject.h	76	warn	V690 The 'QRegExp' class implements the move assignment operator, but lacks a move constructor. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtCore/qmap.h	214	err	V717 It is suspicious to cast object of base class 'QMapNodeBase' to derived class 'QMapNode'.
/home/n/kde/qt5/include/QtCore/qmap.h	215	err	V717 It is suspicious to cast object of base class 'QMapNodeBase' to derived class 'QMapNode'.
/home/n/kde/qt5/include/QtCore/qvariant.h	86	warn	V690 The 'QRegExp' class implements the move assignment operator, but lacks a move constructor. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtCore/qsharedpointer_impl.h	133	err	V1062 The 'ExternalRefCountData' class defines a custom 'delete' operator. The 'new' operator must also be defined.
/home/n/kde/qt5/include/QtCore/qcontiguouscache.h	338	warn	V678 An object is used as an argument to its own method. Consider checking the first actual argument of the 'freeData' function.
/home/n/kde/qt5/include/QtCore/qdatetime.h	275	warn	V602 Consider inspecting the 'sizeof (ShortData) * 8 > 50' expression. '>' possibly should be replaced with '>>'.
/home/n/kde/qt5/include/QtCore/qdatetime.h	270	warn	V690 The 'Data' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtCore/qvariant.h	400	err	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: data.
/home/n/kde/qt5/include/QtCore/qsharedpointer_impl.h	146	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: destroyer.
/home/n/kde/qt5/include/QtCore/qmap.h	224	warn	V1071 Consider inspecting the 'createNode' function. The return value is not always used. Total calls: 13, discarded results: 1.
/home/n/kde/qt5/include/QtNetwork/qsslconfiguration.h	82	warn	V690 The 'QSslConfiguration' class implements the move assignment operator, but lacks a move constructor. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtNetwork/qnetworkreply.h	57	warn	V690 The 'QSslConfiguration' class implements the move assignment operator, but lacks a move constructor. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtGui/qkeysequence.h	71	warn	V690 The 'QKeySequence' class implements the move assignment operator, but lacks a move constructor. It is dangerous to use such a class.
/home/n/kde/qt5/include/QtQml/qqmlprivate.h	139	err	V1062 The 'QQmlElement' class defines a custom 'delete' operator. The 'new' operator must also be defined.
/home/n/kde/qt5/include/QtCore/qvarlengtharray.h	155	err	V1030 Instantiation of QVarLengthArray < char, 48 >: The 'copy' variable is used after it was moved.
/home/n/kde/qt5/include/QtGui/qmatrix.h	60	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: _m11, _m12, _m21, _m22, _dx, _dy.
/home/n/kde/qt5/include/QtGui/qtransform.h	68	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: m_13, m_23, m_33, m_type, m_dirty, d.
/home/n/kde/qt5/include/QtGui/qquaternion.h	60	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: wp, xp, yp, zp.
/home/n/kde/qt5/include/QtGui/qmatrix4x4.h	63	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: m.
/home/n/kde/qt5/include/QtQml/qqmlprivate.h	491	warn	V1071 Consider inspecting the 'qmlregister' function. The return value is not always used. Total calls: 22, discarded results: 2.
/home/n/kde/misc/GammaRay/client/clientconnectionmanager.cpp	153	warn	V773 The 'm_toolManager' pointer was not released in destructor. A memory leak is possible.
/home/n/kde/misc/GammaRay/common/endpoint.cpp	84	warn	V773 The 'm_propertySyncer' pointer was not released in destructor. A memory leak is possible.
/home/n/kde/misc/GammaRay/common/remoteviewframe.cpp	46	warn	V519 The 'pxRatio' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 45, 46.
/home/n/kde/misc/GammaRay/core/enumutil.cpp	113	warn	V1004 The 'mo' pointer was used unsafely after it was verified against nullptr. Check lines: 97, 113.
/home/n/kde/misc/GammaRay/core/metaproperty.h	113	err	V516 Consider inspecting an odd expression. Non-null function pointer is compared to null: 'm_setter == nullptr'.
/home/n/kde/misc/GammaRay/core/metaproperty.h	129	err	V516 Consider inspecting an odd expression. Non-null function pointer is compared to null: '(m_setter)'.
/home/n/kde/misc/GammaRay/core/objectinstance.cpp	139	warn	V779 Unreachable code detected. It is possible that an error is present.
/home/n/kde/misc/GammaRay/core/probe.cpp	500	err	V773 Visibility scope of the 'ms' pointer was exited without releasing the memory. A memory leak is possible.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	102	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	104	err	V607 Ownerless expression 'out << "" << endl'.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	105	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	106	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	107	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	108	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	109	err	V607 Ownerless expression 'out << "" << endl'.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	110	err	V607 Ownerless expression 'out << "Options:" << endl'.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	111	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	115	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	119	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	120	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	121	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	123	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	127	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	131	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	132	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	133	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	134	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	138	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	139	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	141	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	230	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	255	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	329	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	335	err	V607 Ownerless expression.
/home/n/kde/misc/GammaRay/launcher/cli/main.cpp	303	warn	V581 The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 296, 303.
/home/n/kde/misc/GammaRay/launcher/ui/attachdialog.cpp	173	warn	V522 There might be dereferencing of a potential null pointer 'watcher'.
/home/n/kde/misc/GammaRay/launcher/ui/launchpage.cpp	87	warn	V773 The 'm_abiModel' pointer was not released in destructor. A memory leak is possible.
/home/n/kde/misc/GammaRay/plugins/network/networkreplymodel.cpp	237	warn	V1048 The 'replyNode.duration' variable was assigned the same value.
/home/n/kde/misc/GammaRay/plugins/qt3dinspector/3dinspector.cpp	138	warn	V773 The 'm_entitryPropertyController' pointer was not released in destructor. A memory leak is possible.
/home/n/kde/misc/GammaRay/plugins/qt3dinspector/3dinspector.cpp	138	warn	V773 The 'm_frameGraphPropertyController' pointer was not released in destructor. A memory leak is possible.
/home/n/kde/misc/GammaRay/plugins/qt3dinspector/geometryextension/qt3dgeometrytab.cpp	283	err	V773 The function was exited without releasing the 'camController' pointer. A memory leak is possible.
/home/n/kde/misc/GammaRay/plugins/qt3dinspector/paintanalyzerextension/qt3dpaintedtextureanalyzerextension.cpp	68	warn	V773 The 'm_paintAnalyzer' pointer was not released in destructor. A memory leak is possible.
/home/n/kde/misc/GammaRay/plugins/quickinspector/quickitemmodel.cpp	294	err	V595 The 'item' pointer was utilized before it was verified against nullptr. Check lines: 294, 299.
/home/n/kde/misc/GammaRay/plugins/quickinspector/quickscenegraphmodel.cpp	428	err	V530 The return value of function 'find' is required to be utilized.
/home/n/kde/misc/GammaRay/plugins/quickinspector/quickscreengrabber.cpp	447	warn	V519 The 'm_renderInfo.dpr' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 445, 447.
/home/n/kde/misc/GammaRay/plugins/statemachineviewer/statemachineviewerwidget.cpp	242	err	V773 Visibility scope of the 'toolBar' pointer was exited without releasing the memory. A memory leak is possible.
/home/n/kde/misc/GammaRay/plugins/wlcompositorinspector/wlcompositorinspector.cpp	320	warn	V547 Expression 'parentResource' is always false.
/home/n/kde/misc/GammaRay/plugins/wlcompositorinspector/wlcompositorinspector.cpp	321	warn	V547 Expression 'parent' is always false.
/home/n/kde/misc/GammaRay/plugins/wlcompositorinspector/wlcompositorinspector.cpp	323	warn	V547 Expression 'parent' is always false.
/home/n/kde/misc/GammaRay/plugins/wlcompositorinspector/wlcompositorinspector.cpp	328	warn	V547 Expression 'parent' is always false.
/home/n/kde/misc/GammaRay/plugins/wlcompositorinspector/wlcompositorinspector.cpp	332	warn	V547 Expression 'parent' is always false.
/home/n/kde/misc/GammaRay/probe/hooks.cpp	63	warn	V618 It's dangerous to call the 'printf' function in such a manner, as the line being passed could contain format specification. The example of the safe code: printf("%s", str);
/home/n/kde/misc/GammaRay/tests/actiontest.cpp	58	err	V773 The function was exited without releasing the 'model' pointer. A memory leak is possible.
/home/n/kde/misc/GammaRay/tests/actiontest.cpp	51	warn	V799 The 'a2' variable is not used after memory has been allocated for it. Consider checking the use of this variable.
/home/n/kde/misc/GammaRay/tests/bindinginspectortest.cpp	967	warn	V688 The 'bindingModel' local variable possesses the same name as one of the class members, which can result in a confusion.
/home/n/kde/misc/GammaRay/tests/bindinginspectortest.cpp	969	warn	V688 The 'modelTest' local variable possesses the same name as one of the class members, which can result in a confusion.
/home/n/kde/misc/GammaRay/tests/probeabitest.cpp	215	warn	V678 An object is used as an argument to its own method. Consider checking the first actual argument of the 'isCompatible' function.
/home/n/kde/misc/GammaRay/tests/probeabitest.cpp	258	err	V501 There are identical sub-expressions to the left and to the right of the '<' operator: qt52 < qt52
/home/n/kde/misc/GammaRay/tests/propertybindertest.cpp	96	err	V773 The function was exited without releasing the 'obj1' pointer. A memory leak is possible.
/home/n/kde/misc/GammaRay/tests/propertybindertest.cpp	96	err	V773 The function was exited without releasing the 'obj2' pointer. A memory leak is possible.
/home/n/kde/misc/GammaRay/tests/timertoptest.cpp	66	warn	V799 The 't' variable is not used after memory has been allocated for it. Consider checking the use of this variable.
/home/n/kde/misc/GammaRay/ui/aboutwidget.cpp	128	warn	V519 The 'dpr' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 127, 128.
/home/n/kde/misc/GammaRay/ui/codeeditor/codeeditor.cpp	323	warn	V1051 Consider checking for misprints. It's possible that the 'endBlock' should be used inside 'isFolded' function.
/home/n/kde/misc/GammaRay/ui/deferredtreeview.cpp	63	warn	V556 The values of different enum types are compared. Types: State, State.
/home/n/kde/misc/GammaRay/ui/mainwindow.cpp	366	err	V773 Visibility scope of the 'popup' pointer was exited without releasing the memory. A memory leak is possible.
/home/n/kde/misc/GammaRay/ui/propertyeditor/palettedialog.cpp	61	warn	V773 The 'm_model' pointer was not released in destructor. A memory leak is possible.
/home/n/kde/misc/GammaRay/ui/propertyeditor/propertymatrixdialog.cpp	49	warn	V773 The 'm_model' pointer was not released in destructor. A memory leak is possible.
/home/n/kde/misc/GammaRay/ui/remoteviewwidget.cpp	550	warn	V1037 Two or more case-branches perform the same actions. Check lines: 550, 560
/home/n/kde/misc/GammaRay/ui/sidepane.cpp	106	warn	V519 The 'dpr' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 105, 106.

**Comment by Waqar144** [comment]
Thanks
