### ISSUE TITLE
How to inspect applications tab order?

### ISSUE THREAD

**Issue by vadi2** [KDAB/GammaRay#727]
How can I inspect my applications tab order, both for accessibility and keyboard efficiency use?

**Comment by Waqar144** [comment]
You mean "Tab" key presses? Not sure if there is a way to do it with gammaray atm.

**Comment by vadi2** [comment]
Those indeed.

**Comment by Cuperino** [comment]
@vadi2 In both Qt Quick and Widgets, you can go to Qt Quick Scene, click on the _root item of the tree view,_ on the _Properties_ tab, type `nextItemInFocusChain` in the search bar, and follow the chain of _nextItemInFocusChain_ properties. Right click on any property you wish to follow, and click on `Show in Quick Scenes tool` to go to it. It's a bit cumbersome, but those pointers are from where the order Tab presses follow comes from.
