### ISSUE TITLE
debug probe fatal message

### ISSUE THREAD

**Issue by AdamP-2** [KDAB/GammaRay#737]
I have built the Gammaray from source code, cloned by master at commit 0fbfb4ba. I am building for qt 6.3.1 on windows 11.

I built gammaRay with the following arguments from within the gammaRay directory:
- `mkdir build`
- `cd build`
- `cmake -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH=c:/Qt/6.3.1/msvc2019_64/bin -DGAMMARAY_QT6_BUILD=true -DCMAKE_BUILD_TYPE=RELEASE ..`
- `cmake --build . --config Release --target package
- `"C:\Qt\6.3.1\msvc2019_64\bin\windeployqt.exe" --force --pdb --no-compiler-runtime --no-translations "C:\Users\User\GammaRay\build\_CPack_Packages\win64\NSIS\GammaRay 2.99.50\Unspecified\bin"` - this was done to ensure proper .dll linkage

I could then create an installer of gammaRay. I also created a debug probe with the following steps
- `cmake -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH=c:/Qt/6.3.1/msvc2019_64/bin -DGAMMARAY_QT6_BUILD=true -DGAMMARAY_PROBE_ONLY_BUILD=true -DCMAKE_BUILD_TYPE=DEBUG ..`
- `cmake --build . --config Debug --target package`

and installed the debug probe as well

running GammaRay now I can find and attach to both debug and release versions of qt apps, however there are certain gammaRay tabs that don't work when attached to debug probes. If I try and use any of the following tabs Widgets/Timers/Models/Signals/System/Styles with a debug build, I get the following Q_ASSERT  `ASSERT: "addr != Protocol::InvalidObjectAddress"`

![image](https://user-images.githubusercontent.com/118246034/202076663-39458601-a0ec-4545-a937-db619cb6c804.png)

This happens with even QtCreator code examples (Qt Creator 8.0.1 - Qt Widgets - Application example) and because I can still use Messages/Meta Objects/Meta Types tabs, I am logging this as an issue. if you need the installers I have built please let me know

Below is the full backtrace:

handleMessage (C:/Users/User/gamma2/core/tools/messagehandler/messagehandler.cpp:71)
QFileInfo::filePath
QFileInfo::filePath
QFileInfo::filePath
QFileInfo::filePath
GammaRay::PropertySyncer::handleMessage (C:/Users/User/gamma2/common/propertysyncer.cpp:107)
GammaRay::PropertySyncer::qt_static_metacall (C:/Users/User/gamma2/build/Release/common/gammaray_common_autogen/include_Debug/EWIEGA46WW/moc_propertysyncer.cpp:88)
QFileInfo::filePath
QFileInfo::filePath
GammaRay::Endpoint::dispatchMessage (C:/Users/User/gamma2/common/endpoint.cpp:351)
GammaRay::Server::messageReceived (C:/Users/User/gamma2/core/remote/server.cpp:202)
GammaRay::Endpoint::readyRead (C:/Users/User/gamma2/common/endpoint.cpp:158)
QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl GammaRay::Endpoint::*)(void)>::call (C:/Qt/6.3.1/msvc2019_64/include/QtCore/qobjectdefs_impl.h:171)
QtPrivate::FunctionPointer<void (__cdecl GammaRay::Endpoint::*)(void)>::call<QtPrivate::List<>,void> (C:/Qt/6.3.1/msvc2019_64/include/QtCore/qobjectdefs_impl.h:209)
QtPrivate::QSlotObject<void (__cdecl GammaRay::Endpoint::*)(void),QtPrivate::List<>,void>::impl (C:/Qt/6.3.1/msvc2019_64/include/QtCore/qobjectdefs_impl.h:420)
QFileInfo::filePath
QFileInfo::filePath
QFileInfo::filePath
QFileInfo::filePath
QNetworkInterface::interfaceNameFromIndex
QNetworkInterface::interfaceNameFromIndex
QNetworkInterface::interfaceNameFromIndex
QNetworkInterface::interfaceNameFromIndex
QNetworkInterface::interfaceNameFromIndex
QLineEdit::`default constructor closure'
QLineEdit::`default constructor closure'
QFileInfo::filePath
QFileInfo::filePath
QFileInfo::filePath
CallWindowProcW
DispatchMessageW
QFileInfo::filePath
QTextCharFormat::setFontLetterSpacingType
QFileInfo::filePath
QFileInfo::filePath
QFileInfo::filePath
QTextCharFormat::setFontLetterSpacingType
QLineEdit::`default constructor closure'
main (C:/Qt/Examples/Qt-6.3.1/widgets/mainwindows/application/main.cpp:77)
WinMain (C:/Users/qt/work/qt/qtbase/src/entrypoint/qtentrypoint_win.cpp:97)
invoke_main (D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl:107)
__scrt_common_main_seh (D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl:288)
__scrt_common_main (D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl:331)
WinMainCRTStartup (D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_winmain.cpp:17)
BaseThreadInitThunk
RtlUserThreadStart

**Comment by mattkdab** [comment]
@AdamP-2 are you still having this issue on current master? if so please provide the installers and any relevant updated information. i ran into some issues with my windows environment trying to reproduce, so the installers will likely be helpful. doesn't appear to be reproducible on linux

**Comment by shzm-li** [comment]
I can't reproduce this on the current master on Windows with Qt6.6 probes.
