### ISSUE TITLE
CMake error on Ubuntu 22.04 with Qt 6.2.3

### ISSUE THREAD

**Issue by coderalpha** [KDAB/GammaRay#738]
Hi 

I get the following CMake error:
```
CMake Error at common/CMakeLists.txt:60 (add_library):
  Target "gammaray_common" links to target "XKB::XKB" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```
I looked in the CMakeLists in the **common** directory, but I don't even see any reference to XKB.

I have the following installed:
|||
|---|---|
|  CMake | 3.22.1 | 
| GCC | 11.3.0 |
| Qt | 6.2.3 |

**Comment by coderalpha** [comment]
I installed libxkbcommon-dev, which fixed the issue.

**Comment by quachdnguyen** [comment]
Thanks! This solves my problem as well.
