### ISSUE TITLE
Qt6 "Direct3D11 is not supported yet, please use OpenGL or software backend"

### ISSUE THREAD

**Issue by peize-li123** [KDAB/GammaRay#739]
Hi, I was trying GammaRay with Qt 6.4.1 & Qt 6.2.4. When I tried to use Quick Scene, I kept getting this message " Direct3D11 is not supported yet, please use OpenGL or software backend". Do you have any idea what steps I should follow to solve this issue?

I was using a Windows machine. A reproducible example can be the "Coffee Machine Example" in Qt 6.2.4 in Qt Creator. THanks.

**Comment by Waqar144** [comment]
see https://doc-snapshots.qt.io/qt6-dev/qquickwindow.html#setGraphicsApi and https://doc.qt.io/qt-6/qtquick-visualcanvas-scenegraph-renderer.html#rendering-via-the-qt-rendering-hardware-interface

**Comment by peize-li123** [comment]
This works. Thanks a lot!
