### ISSUE TITLE
MacOSX Install Location (and Bundle)

### ISSUE THREAD

**Issue by sebastient** [KDAB/GammaRay#74]
The Install.txt claims that on MacOSX GammaRay should be installed as /Applications/GammaRay.app but when I build the current git master this does not happen and I'm not seeing anything in the CMakeLists.txt to configure this.  I can run /usr/local/bin/gammaray fine but since this isn't a proper MacOSX bundle it's missing things such as the application icon and menubar entries.

**Comment by krf** [comment]
@sebastient: Still an issue for you? There were some efforts for fixing the OS X bundle last year.

Can you check again? Marking this as closed for now, please reopen when needed.
