### ISSUE TITLE
Latest update to ECM CMake tools is missing file?

### ISSUE THREAD

**Issue by ferdnyc** [KDAB/GammaRay#740]
[I mentioned in a commit comment](https://github.com/KDAB/GammaRay/commit/16804f98c3be76ce9221820a025c8db1a2970f2e#r91076713) that 16804f98c3be76ce9221820a025c8db1a2970f2e appears to be missing one of the files for the ECM Qt tooling:

```
CMake Error at cmake/ECM/modules/ECMQueryQt.cmake:38 (include):
  include could not find requested file:

    <srcdir>/cmake/ECM/modules/QtVersionOption.cmake
Call Stack (most recent call first):
  cmake/ECM/modules/ECMGeneratePriFile.cmake:102 (include)
  CMakeLists.txt:149 (include)


CMake Error at cmake/ECM/modules/ECMQueryQt.cmake:84 (message):
  No executable found.  Can't check QT_INSTALL_PREFIX as required
Call Stack (most recent call first):
  cmake/ECM/modules/ECMGeneratePriFile.cmake:103 (ecm_query_qt)
  CMakeLists.txt:149 (include)


-- Configuring incomplete, errors occurred!
```
Perhaps `QT_MAJOR_VERSION` is supposed to be set some other way? (Manually setting it on the `cmake` command line does allow it to continue generating the build system, although the missing include file still results in a delayed "Configuring incomplete, errors occurred!" failure at the end of the run. So, the missing file is an error regardless.)

**Comment by winterz** [comment]
fixed in 62cf883afc3b537c39c4ec205c230d2601159635
