### ISSUE TITLE
ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by MAxelZiemet** [KDAB/GammaRay#758]
Hello Together,
trying to build current gammaRay Release, gammaray-launcher under Windows, QtCreator 9.01, mingw-64Bit, all in current versions, results in: 

```
[594/601 2.3/sec] Building CXX object plugins/quickwidgetsupport/CMakeFiles/gammaray_quickwidgetsupport.dir/quickwidgetsupport.cpp.obj
[595/601 2.3/sec] Building CXX object plugins/qmlsupport/CMakeFiles/gammaray_qmlsupport.dir/qmlbindingprovider.cpp.obj
[596/601 2.3/sec] Building CXX object plugins/qmlsupport/CMakeFiles/gammaray_qmlsupport.dir/qmlsupport.cpp.obj
[597/601 2.3/sec] Linking CXX shared module C:\qt\build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release\plugins\gammaray\3.0\qt6_4-GNU-x86_64d\gammaray_quickwidgetsupportd.dll
[598/601 2.3/sec] Linking CXX shared module C:\qt\build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release\plugins\gammaray\3.0\qt6_4-GNU-x86_64d\gammaray_qmlsupportd.dll
[599/601 2.3/sec] Linking CXX shared module C:\qt\build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release\plugins\gammaray\3.0\qt6_4-GNU-x86_64d\gammaray_widgetinspector_plugind.dll
[600/601 2.3/sec] Linking CXX shared module C:qt\build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release\plugins\gammaray\3.0\qt6_4-GNU-x86_64d\gammaray_quickinspectord.dll
[601/601 2.1/sec] Linking CXX shared modul C:\qt\build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release\plugins\gammaray\3.0\qt6_4-GNU-x86_64d\gammaray_guisupportd.dll
**ninja: build stopped: subcommand failed.**
11:08:24: Der Prozess "C:\Qt\Tools\CMake_64\bin\cmake.exe" wurde mit dem Rückgabewert 1 beendet.
```

Played around with some setups, all still with same result!

Some ideas or hints welcome.

Greetings Axel

**Comment by krf** [comment]
It's not clear which subcommand failed.

Could you run `ninja -v` in the same build dir and post the output?

**Comment by MAxelZiemet** [comment]
sorry, but didn't find a way to add an ninja option.

Where / how to add it in QtCreator?

Am 03.02.2023 um 08:29 schrieb Kevin Funk:

**Comment by MAxelZiemet** [comment]
changed Cmake generator to "MinGW Makefile" results in:
:-1: Fehler: [docs\manual\CMakeFiles\gammaray-manual.qch.dir\build.make:220: docs/manual/codecontributions.qdoc] Error 1

**Comment by MAxelZiemet** [comment]
cmake CMAKE_MESSAGE_LOG_LEVEL shows
[CMakeError.log](https://github.com/KDAB/GammaRay/files/10695734/CMakeError.log)

**Comment by Waqar144** [comment]
Please post the full build output, not the last 5 lines, not just one failing line but the full output given by ninja/Cmake.  To add addition flags to e.g., ninja, see `Projects` page of QtCreator. Alternatively you can do it from the command line.

**Comment by MAxelZiemet** [comment]
CMakeErrorLog shows:
Performing C SOURCE FILE Test C_SUPPORTS_REORDER failed with the following output:
Change Dir: C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Qt/Tools/Ninja/ninja.exe cmTC_dd436 && [1/2] Building C object CMakeFiles/cmTC_dd436.dir/src.c.obj
FAILED: CMakeFiles/cmTC_dd436.dir/src.c.obj 
C:\Qt\Tools\mingw1120_64\bin\gcc.exe -DC_SUPPORTS_REORDER  -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess    -Werror -Wreorder -o CMakeFiles/cmTC_dd436.dir/src.c.obj -c C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/src.c
cc1.exe: error: command-line option '-Wreorder' is valid for C++/ObjC++ but not for C [-Werror]
cc1.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.


Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_SUPPORTS_FORMAT_SECURITY failed with the following output:
Change Dir: C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Qt/Tools/Ninja/ninja.exe cmTC_313c7 && [1/2] Building C object CMakeFiles/cmTC_313c7.dir/src.c.obj
FAILED: CMakeFiles/cmTC_313c7.dir/src.c.obj 
C:\Qt\Tools\mingw1120_64\bin\gcc.exe -DC_SUPPORTS_FORMAT_SECURITY  -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess    -Werror -Wformat-security -o CMakeFiles/cmTC_313c7.dir/src.c.obj -c C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/src.c
cc1.exe: error: '-Wformat-security' ignored without '-Wformat' [-Werror=format-security]
cc1.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.


Source file was:
int main(void) { return 0; }
Performing C++ SOURCE FILE Test CXX_SUPPORTS_FORMAT_SECURITY failed with the following output:
Change Dir: C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Qt/Tools/Ninja/ninja.exe cmTC_72078 && [1/2] Building CXX object CMakeFiles/cmTC_72078.dir/src.cxx.obj
FAILED: CMakeFiles/cmTC_72078.dir/src.cxx.obj 
C:\Qt\Tools\mingw1120_64\bin\g++.exe -DCXX_SUPPORTS_FORMAT_SECURITY  -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wreorder    -Werror -Wformat-security -std=gnu++11 -o CMakeFiles/cmTC_72078.dir/src.cxx.obj -c C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/src.cxx
cc1plus.exe: error: '-Wformat-security' ignored without '-Wformat' [-Werror=format-security]
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.


Source file was:
int main() { return 0; }
Performing C SOURCE FILE Test C_SUPPORTS_SUGGEST_OVERRIDE failed with the following output:
Change Dir: C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Qt/Tools/Ninja/ninja.exe cmTC_66c29 && [1/2] Building C object CMakeFiles/cmTC_66c29.dir/src.c.obj
FAILED: CMakeFiles/cmTC_66c29.dir/src.c.obj 
C:\Qt\Tools\mingw1120_64\bin\gcc.exe -DC_SUPPORTS_SUGGEST_OVERRIDE  -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess    -Werror -Wsuggest-override -o CMakeFiles/cmTC_66c29.dir/src.c.obj -c C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/src.c
cc1.exe: error: command-line option '-Wsuggest-override' is valid for C++/ObjC++ but not for C [-Werror]
cc1.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.


Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_SUPPORTS_ZERO_AS_NULL_POINTER_CONSTANT failed with the following output:
Change Dir: C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Qt/Tools/Ninja/ninja.exe cmTC_42197 && [1/2] Building C object CMakeFiles/cmTC_42197.dir/src.c.obj
FAILED: CMakeFiles/cmTC_42197.dir/src.c.obj 
C:\Qt\Tools\mingw1120_64\bin\gcc.exe -DC_SUPPORTS_ZERO_AS_NULL_POINTER_CONSTANT  -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess    -Werror -Wzero-as-null-pointer-constant -o CMakeFiles/cmTC_42197.dir/src.c.obj -c C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/src.c
cc1.exe: error: command-line option '-Wzero-as-null-pointer-constant' is valid for C++/ObjC++ but not for C [-Werror]
cc1.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.


Source file was:
int main(void) { return 0; }
Determining if the QT_NO_OPENGL exist failed with the following output:
Change Dir: C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Qt/Tools/Ninja/ninja.exe cmTC_6e02d && [1/2] Building CXX object CMakeFiles/cmTC_6e02d.dir/CheckSymbolExists.cxx.obj
FAILED: CMakeFiles/cmTC_6e02d.dir/CheckSymbolExists.cxx.obj 
C:\Qt\Tools\mingw1120_64\bin\g++.exe -DMINGW_HAS_SECURE_API=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 -isystem C:/Qt/6.4.2/mingw_64/include/QtGui -isystem C:/Qt/6.4.2/mingw_64/include -isystem C:/Qt/6.4.2/mingw_64/include/QtCore -isystem C:/Qt/6.4.2/mingw_64/mkspecs/win32-g++ -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wreorder -Wsuggest-override -Wall -Wextra -pedantic -Woverloaded-virtual -Winit-self -Wmissing-include-dirs -Wunused -Wundef -Wpointer-arith -Wmissing-noreturn -Werror=return-type -Wswitch -std=gnu++0x -fpermissive -fno-operator-names -Wa,-mbig-obj -Wzero-as-null-pointer-constant  -std=gnu++17 -o CMakeFiles/cmTC_6e02d.dir/CheckSymbolExists.cxx.obj -c C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In function 'int main(int, char**)':
C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: 'QT_NO_OPENGL' was not declared in this scope; did you mean 'QT_NO_EGL'?
    8 |   return ((int*)(&QT_NO_OPENGL))[argc];
      |                   ^~~~~~~~~~~~
      |                   QT_NO_EGL
ninja: build stopped: subcommand failed.


File C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QOpenGLContext>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef QT_NO_OPENGL
  return ((int*)(&QT_NO_OPENGL))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Determining if the backtrace exist failed with the following output:
Change Dir: C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Qt/Tools/Ninja/ninja.exe cmTC_74f89 && [1/2] Building C object CMakeFiles/cmTC_74f89.dir/CheckSymbolExists.c.obj
FAILED: CMakeFiles/cmTC_74f89.dir/CheckSymbolExists.c.obj 
C:\Qt\Tools\mingw1120_64\bin\gcc.exe   -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -o CMakeFiles/cmTC_74f89.dir/CheckSymbolExists.c.obj -c C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/CheckSymbolExists.c
C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/CheckSymbolExists.c:2:10: fatal error: execinfo.h: No such file or directory
    2 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.


File C:/Users/papas/qt/build-GammaRay-Desktop_Qt_6_4_2_MinGW_64_bit-Release/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <execinfo.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef backtrace
  return ((int*)(&backtrace))[argc];
#else
  (void)argc;
  return 0;
#endif
}
