### ISSUE TITLE
OpenGL linking error

### ISSUE THREAD

**Issue by thawfeekyahya** [KDAB/GammaRay#771]
I am trying to build Gammaray against a custom patched Qt 6 version . And I get this error

> GammaRay/plugins/quickinspector/geometryextension/sggeometrymodel.cpp:114:14: error: use of undeclared identifier 'GL_2_BYTES'
>         case GL_2_BYTES:
>              ^
> GammaRay/plugins/quickinspector/geometryextension/sggeometrymodel.cpp:116:14: error: use of undeclared identifier 'GL_3_BYTES'
>         case GL_3_BYTES:
>              ^
> GammaRay/plugins/quickinspector/geometryextension/sggeometrymodel.cpp:118:14: error: use of undeclared identifier 'GL_4_BYTES'
>         case GL_4_BYTES:
>              ^
> GammaRay/plugins/quickinspector/geometryextension/sgwireframewidget.cpp:73:65: error: use of undeclared identifier 'GL_QUAD_STRIP'
>         else if ((m_drawingMode == GL_QUADS || m_drawingMode == GL_QUAD_STRIP) && i % 4 == 3) {
>                                                                 ^
> GammaRay/plugins/quickinspector/geometryextension/sgwireframewidget.cpp:76:37: error: use of undeclared identifier 'GL_POLYGON'
>         } else if (m_drawingMode == GL_POLYGON && i == m_adjacencyList.size() - 1) {
>                                     ^
> GammaRay/plugins/quickinspector/geometryextension/sgwireframewidget.cpp:96:35: error: use of undeclared identifier 'GL_QUAD_STRIP'
>              || (m_drawingMode == GL_QUAD_STRIP && i % 2)
>                                   ^
> GammaRay/plugins/quickinspector/geometryextension/sgwireframewidget.cpp:97:34: error: use of undeclared identifier 'GL_POLYGON'
>              || m_drawingMode == GL_POLYGON
>                                  ^
> GammaRay/plugins/quickinspector/geometryextension/sgwireframewidget.cpp:108:34: error: use of undeclared identifier 'GL_QUAD_STRIP'
>              || m_drawingMode == GL_QUAD_STRIP
>                                  ^
> GammaRay/plugins/quickinspector/geometryextension/sgwireframewidget.cpp:126:34: error: use of undeclared identifier 'GL_POLYGON'
>             || (m_drawingMode == GL_POLYGON && i == m_adjacencyList.size() - 1)
>                                  ^
> GammaRay/plugins/quickinspector/geometryextension/sgwireframewidget.cpp:163:26: error: use of undeclared identifier 'GL_POLYGON'
>         m_drawingMode == GL_POLYGON      ? QStringLiteral("GL_POLYGON")
>                          ^
> GammaRay/plugins/quickinspector/geometryextension/sgwireframewidget.cpp:165:28: error: use of undeclared identifier 'GL_QUAD_STRIP'
>         : m_drawingMode == GL_QUAD_STRIP ? QStringLiteral("GL_QUAD_STRIP")
>                            ^
> 8 errors generated.
> 3 errors generated.
> make[2]: *** [plugins/quickinspector/CMakeFiles/gammaray_quickinspector_ui.dir/build.make:266: plugins/quickinspector/CMakeFiles/gammaray_quickinspector_ui.dir/geometryextension/sgwireframewidget.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:7592: plugins/quickinspector/CMakeFiles/gammaray_quickinspector_ui.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make[2]: *** [plugins/quickinspector/CMakeFiles/gammaray_quickinspector.dir/build.make:206: plugins/quickinspector/CMakeFiles/gammaray_quickinspector.dir/geometryextension/sggeometrymodel.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> GammaRay/plugins/quickinspector/textureextension/qsgtexturegrabber.cpp:193:60: error: unknown type name 'QOpenGLFunctions_2_0'; did you mean 'QOpenGLFunctions'?
>         auto glFuncs = QOpenGLVersionFunctionsFactory::get<QOpenGLFunctions_2_0>(context);
>                                                            ^~~~~~~~~~~~~~~~~~~~
>                                                            QOpenGLFunctions
> builds/build_ntgdeps/install/include/QtGui/qopenglfunctions.h:201:20: note: 'QOpenGLFunctions' declared here
> class Q_GUI_EXPORT QOpenGLFunctions
>                    ^
> 
> GammaRay/plugins/quickinspector/textureextension/qsgtexturegrabber.cpp:214:18: error: no member named 'glGetTexLevelParameteriv' in 'QOpenGLFunctions'
>         glFuncs->glGetTexLevelParameteriv(GL_TEXTURE_2D, 0, GL_TEXTURE_WIDTH, &w);
>         ~~~~~~~  ^
> GammaRay/plugins/quickinspector/textureextension/qsgtexturegrabber.cpp:215:18: error: no member named 'glGetTexLevelParameteriv' in 'QOpenGLFunctions'
>         glFuncs->glGetTexLevelParameteriv(GL_TEXTURE_2D, 0, GL_TEXTURE_HEIGHT, &h);
>         ~~~~~~~  ^
> GammaRay/plugins/quickinspector/textureextension/qsgtexturegrabber.cpp:223:18: error: no member named 'glGetTexImage' in 'QOpenGLFunctions'
>         glFuncs->glGetTexImage(GL_TEXTURE_2D, 0, GL_BGRA, GL_UNSIGNED_BYTE, img.bits());
>         ~~~~~~~  ^
> In file included from GammaRay/plugins/quickinspector/textureextension/qsgtexturegrabber.cpp:31:
> In file included from builds/build_ntgdeps/install/include/QtOpenGL/QOpenGLVersionFunctionsFactory:1:
> builds/build_ntgdeps/install/include/QtOpenGL/qopenglversionfunctionsfactory.h:32:41: error: no member named 'versionProfile' in 'QOpenGLFunctions'
>         QOpenGLVersionProfile v = TYPE::versionProfile();
>                                   ~~~~~~^
> GammaRay/plugins/quickinspector/textureextension/qsgtexturegrabber.cpp:193:56: note: in instantiation of function template specialization 'QOpenGLVersionFunctionsFactory::get<QOpenGLFunctions>' requested here
>         auto glFuncs = QOpenGLVersionFunctionsFactory::get<QOpenGLFunctions_2_0>(context);
> 

Seems like Gammaray picking up wrong class for OpenGL 

`install/include/QtGui/qopenglfunctions.h:201:20: note: 'QOpenGLFunctions' declared here
class Q_GUI_EXPORT QOpenGLFunction`

instead of correct one right here,
`install/include/QtOpenGL/qopenglfunctions_2_0.h`

**Comment by Waqar144** [comment]
> custom patched Qt 6 version 

Which?

What cmake command did you use?

**Comment by thawfeekyahya** [comment]
cmake -DCMAKE_PREFIX_PATH=~/Projects/builds/build/qt-latest/lib/cmake -DGAMMARAY_QT6_BUILD=true ..

**Comment by Waqar144** [comment]
Builds fine here with `Qt 6.4.2`. Seems like you don't have the required header with the Qt you built yourself. It could be because the Qt you built isn't configured incorrectly.

**Comment by thawfeekyahya** [comment]
Thanks for checking @Waqar144 , I will update if I have any luck with this .

**Comment by thawfeekyahya** [comment]
This is my qt configuation , 

> Qt configuration ... configure -nomake tests -nomake examples -platform linux-clang -no-feature-clangcpp -debug -prefix /home/thyahya/Projects/builds/build_ntgdeps/install -opengl es2 -egl -qt-libjpeg -qt-libpng -opensource -confirm-license

Is there anything I am missing here ?
