### ISSUE TITLE
Gammaray on Android (Qt6)

### ISSUE THREAD

**Issue by kornava** [KDAB/GammaRay#773]
Trying to build Gammaray on Android with no success, I used Qt6.5 android on Mac host, following those instructions:
Build on Android:
    mkdir android-build
    cd android-build
    export ANDROID_NDK=/path/to/android-ndk
    cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DCMAKE_FIND_ROOT_PATH=/android/qt5/install/path \
          -DCMAKE_INSTALL_PREFIX=/install/path ..
    make [-j CPU_NUMBER+2]
    make install
    
    
Here is my cmake command:
/Users/saif/Qt/6.5.0/android_arm64_v8a/bin/qt-cmake -DGAMMARAY_QT6_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DCMAKE_FIND_ROOT_PATH=/Users/saif/Qt/6.5.0/android_arm64_v8a/ -DCMAKE_INSTALL_PREFIX=/Users/saif/Documents/git/gamma ..

which Qt6 verison is compatible with Gammaray for android targets?

**Comment by Waqar144** [comment]
And what was the problem that happened?

**Comment by kornava** [comment]
CMake Error at CMakeLists.txt:429 (find_package):
  Could not find a configuration file for package "Qt" that is compatible
  with requested version "5.5".

  The following configuration files were considered but not accepted:

    /Users/saif/Qt/6.5.0/android_arm64_v8a/lib/cmake/Qt6/Qt6Config.cmake, version: 6.5.0 (64bit)

**Comment by Waqar144** [comment]
Can you open the `CMakeLists.txt` at the root of the project, goto line 431 and modify 5.5 to your version and see if it works?

**Comment by kornava** [comment]
CMake Error at CMakeLists.txt:429 (find_package):
  Could not find a configuration file for package "Qt" that is compatible
  with requested version "6.5".

  The following configuration files were considered but not accepted:

    /Users/saif/Qt/6.5.0/android_arm64_v8a/lib/cmake/Qt6/Qt6Config.cmake, version: 6.5.0 (64bit)

**Comment by mepatrick73** [comment]
I have the same issue as Kornava on windows using the MSVC compiler.

**Comment by Waqar144** [comment]
Can you try specifying `-DCMAKE_PREFIX_PATH=/Users/saif/Qt/6.5.0/android_arm64_v8a/lib/cmake/` when invoking cmake?

**Comment by kornava** [comment]
For information I tried with the DCMAKE_PREFIX_PATH and I keep getting the same Cmake error:

CMake Error at CMakeLists.txt:420 (find_package):
  Could not find a configuration file for package "Qt" that is compatible
  with requested version "6.5".

  The following configuration files were considered but not accepted:

    /Users/saif/Qt/6.5.0/android_arm64_v8a/lib/cmake/Qt6/Qt6Config.cmake, version: 6.5.0 (64bit)
