### ISSUE TITLE
Please release a new version.

### ISSUE THREAD

**Issue by shenlebantongying** [KDAB/GammaRay#775]
I requested my distro to enable Qt6 for GammaRay, but got rejected because no version with Qt6 support has been released.

Is there any plan/agenda?

In fact, all distros stuck to the version from 2 years ago.

https://repology.org/project/gammaray/versions

**Comment by Waqar144** [comment]
We plan to make a release soon, probably in a month or so. The road to Qt6 has been rocky so we have held back from releasing too early.

**Comment by shenlebantongying** [comment]
Thanks for the info :)
