### ISSUE TITLE
GammaRay hangs at splash screen with Qt 6.5.0

### ISSUE THREAD

**Issue by sandroandrade** [KDAB/GammaRay#777]
GammaRay master branch builds fine on Linux with Qt 6.5.0. However, it hangs on splash screen when started with a simple Qt Widgets application (Qt Creator 10's default Qt Widgets project). Its log shows the following information:
```
Detected ABI qt6_5-x86_64, using ABI qt6_5-x86_64.
GammaRay server listening on: tcp://127.0.0.1:11732
QMetaObject::invokeMethod: No such method GammaRay::ToolManager::requestAvailableTools(GammaRay::MethodArgument,GammaRay::MethodArgument,GammaRay::MethodArgument,GammaRay::MethodArgument,GammaRay::MethodArgument,GammaRay::MethodArgument,GammaRay::MethodArgument,GammaRay::MethodArgument,GammaRay::MethodArgument,GammaRay::MethodArgument)
Candidates are:
    requestAvailableTools()
```

**Comment by vimpostor** [comment]
It's a sideeffect of https://codereview.qt-project.org/c/qt/qtbase/+/422745 which breaks our usage of `QMetaObject::invokeMethod()` in `Endpoint::invokeObjectLocal()` as we can no longer just dump all 10 arguments with the variadic version and instead have to call `QMetaObject::invokeMethod()` with both the correct arity and correct types.

Also see: https://github.com/KDAB/GammaRay/issues/761#issuecomment-1506699500
