### ISSUE TITLE
Analyze static builded application using gammaray 

### ISSUE THREAD

**Issue by Th3Mand0** [KDAB/GammaRay#812]
Hello. I have statically compiled a simple login program using Qt5.15.5-static, now I want to analyze and debug it using Gammaray. But when I select it as an input file,The launch button is disabled.
I tried another way, first I run my program, then I run gammaray to do my work with attack tab. But my application name is not in the list.
By the way, I have compiled Gammaray with qt5.15.5-dynamic.

I tried to statically compile Gammaray, but I didn't know how to do it. I'm not even sure if doing this will solve my problem.

So what should I do now?
Please help. Thank you in advance

**Comment by Th3Mand0** [comment]
:(((

**Comment by Waqar144** [comment]
Hi, please check `Integrating the GammaRay Probe into an Application
` https://docs.kdab.com/gammaray-manual/latest/gammaray-advanced-usage.html
