### ISSUE TITLE
QQuickWidget content scene is displayed with a vertical offset

### ISSUE THREAD

**Issue by ratijas** [KDAB/GammaRay#815]
In KDE our System Settings application (and kcmshell SDK tool which practically is mostly the same) consists of embedded QQuickWidget and a QtWidgets based footer. There's also a QQuickWidget sidebar, but that doesn't matter for now.

Qt Widgets view:

![Screenshot_20230605_194746](https://github.com/KDAB/GammaRay/assets/6737986/f1e9367a-b57a-4a83-870e-9547f97b12fe)

so far so good…

Quick Scene view:

![Screenshot_20230605_194921](https://github.com/KDAB/GammaRay/assets/6737986/06376e9b-c88b-41af-9183-33708256aec8)

oops! Viewport is shifted to the bottom. It includes QtWidgets footer (with the Close button), but omits QtQuick header. Clicking on items selects them based on their position properly, but selection does not visually match where the item is rendered in GammaRay.

Qt version: 6.5.1
GammaRay: built from git master regularly
Operating system: Arch Linux
Graphical system: X11

**Comment by ratijas** [comment]
I managed to create a fairly minimal reproducible example with a QtQuick scene being embedded in a QQuickWidget.

[quickwidget-gammaray.zip](https://github.com/KDAB/GammaRay/files/11655088/quickwidget-gammaray.zip)

**Comment by olib14** [comment]
When the sidebar is visible in KDE's System Settings, the preview for the settings page scene includes the application's sidebar, which is a separate QtQuick scene.

![image](https://github.com/KDAB/GammaRay/assets/107320647/b0eeea35-85b4-46e6-a593-2dfa30b883c7)

If I had to guess, somewhere it falls back to positioning the preview at (0, 0). The size of the preview is correct, just the position is wrong.

This is for **Qt 6**: (Qt 6.5.1, GammaRay 2.99.50 e7593c398, Arch Linux, X11, KDE Plasma 5.27.5)

**Comment by Waqar144** [comment]
Should be fixed with latest master.

**Comment by ratijas** [comment]
Can confirm the fix. Thanks!

**Comment by Waqar144** [comment]
can you post a screenshot of the message? and can you check what backend graphics api is being used? The value is available in QQuickWindow's properties.

**Comment by ratijas** [comment]
I can click to select items, but can't see them.

`GraphicsInfo.api` is `OpenGL`

![image](https://github.com/KDAB/GammaRay/assets/6737986/a1de24b6-cc86-41b0-9842-c3c52b522e51)

**Comment by Waqar144** [comment]
Should be fixed now I believe.

**Comment by ratijas** [comment]
Seems to be working now, thanks!
