### ISSUE TITLE
start fail 

### ISSUE THREAD

**Issue by zj951555793** [KDAB/GammaRay#816]
-- The following OPTIONAL packages have not been found:

 * Qt5WaylandCompositor
 * Qt5IviCore (required version >= 1.1)
 * Qt5IviVehicleFunctions (required version >= 1.1)
 * Qt5IviMedia (required version >= 1.1)
 * Glslang, <https://github.com/KhronosGroup/glslang>
   Validate GL shader code.
 * KF5CoreAddons, KDE KCoreAddons Framework, <https://www.kde.org/>
   Required for the KJob tracker plug-in.
 * VTK, Visualization Toolkit, <https://www.vtk.org>
   Needed for the object visualizer plugin (required Qt5).

**Comment by zj951555793** [comment]
Thanks,  but some issue still happend i am trying to sove it still now.
can you give me some advice?

![图片](https://github.com/KDAB/GammaRay/assets/30136360/3e2b3a2f-837c-4b6b-8f33-cd8ec7717215)

**Comment by zj951555793** [comment]
can't attach any process\

**Comment by zj951555793** [comment]
I use cmake configure and visual studio 2019 build than cannt't found any probes,
but i  use qtcreator and msvc2019 than it perfect well
![图片](https://github.com/KDAB/GammaRay/assets/30136360/92a20484-bffa-43c7-9231-6627e65b298a)
 i don't know why.  Fortunately, it works well, I can explore it now!

**Comment by kelteseth** [comment]
Same problem here my build bat

```
mkdir Gammaray_Release
cd Gammaray_Release
cmake -G "Visual Studio 17 2022" -DCMAKE_PREFIX_PATH=C:\Qt\6.5.2\msvc2019_64 -DGAMMARAY_DISABLE_FEEDBACK=1 -DBUILD_TESTING=0 ./..
cmake --build . --config Release
cd bin
cd Release
C:\Qt\6.5.2\msvc2019_64\bin\windeployqt.exe --release gammaray.exe
pause
```
