### ISSUE TITLE
Update Wiki with Yocto recipe for qt6

### ISSUE THREAD

**Issue by Paiusco** [KDAB/GammaRay#818]
After issue #785 the [examples/yocto/gammaray_git_cmake6.bb](https://github.com/KDAB/GammaRay/commit/1c20bcc0f548e2cbc1e2a32a43d5fbd8349f955f) was created. However, if anyone tries to find the basic documentation of gammaray, the first results are always the wiki.

My request is to update the wiki to have the option for qt6 as well. 
**I was not able to find how to fork/open a PR for wiki tho :(** Otherwise I'd do it myself.

If possible I also think it's a good idea to update the hash/version for qt5 as it seems gammaray is working mostly at HEAD and not doing releases anymore.

**Comment by winterz** [comment]
done. 
see https://github.com/KDAB/GammaRay/wiki/Cross-compiling-GammaRay
