### ISSUE TITLE
protect application

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [KDAB/GammaRay#819]
How can I protect  application from debugging/introspection  with [GammaRay](https://github.com/KDAB/GammaRay)🫡🫡

it work with Release build 😶

**Comment by milianw** [comment]
You cannot really, short of obfuscating your app and adding invasive protection mechanisms that prevent a debugger from being attached to your application.

**Comment by Waqar144** [comment]
You can try to link Qt statically, that will prevent gammary from attaching to the app. For e.g., GammaRay can't attach to official telegram desktop app.
