### ISSUE TITLE
Using Qt6 but Qt5 GammaRay version is being built

### ISSUE THREAD

**Issue by 7ymekk** [KDAB/GammaRay#821]
OS: ArchLinux with Qt6 installed in /opt/Qt/6.5.2/gcc_64, Qt 5.15 installed from package manager as KDE and others require it.

I tried building GammaRay with Qt6.5.2 using QtCreator but also command line. It builds properly but when I run it, there's only 1 probe to select: Qt 5.15 (x86_64).

In a build dir I noticed build-GammaRay-Release/lib/gammaray/2.11/qt5_15-x86_64/

I also tried https://github.com/KDAB/GammaRay/blob/master/INSTALL.md#force-a-probe-only-build and it built 5.15 probe again.

Could you please advise if I'm missing something or there might be some bug? IMO when loading project to QtCreator and building GammaRay, it should by default build the probe for Qt I'm building with.

**Comment by Waqar144** [comment]
Have you tried running it from the command line? Perhaps launching it from Qt creator messes something. Also check the executable using ldd to make sure it really was built with Qt6

**Comment by 7ymekk** [comment]
yeah, bin/gammaray is linked to Qt5 from PATH in both cases: using QtCreator and command line:

```cmake -G Ninja -DCMAKE_PREFIX_PATH=/opt/Qt/6.5.2/gcc_64 -DGAMMARAY_BUILD_DOCS=OFF GAMMARAY_BUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=/opt/gammaray /home/kuba/workspace/GammaRay```

any suggestions?

I'm trying v2.11.3

**Comment by 7ymekk** [comment]
thanks for a quick reply, that was it. It would be great to have this info in INSTALL.md or README.md, as I usually use latest TAG and not the master.
