### ISSUE TITLE
Building gammay with custom qt build

### ISSUE THREAD

**Issue by Rhvarrier** [KDAB/GammaRay#822]
I'm using a locally build qt5.15 for my application and the configure options are as follows

```
-prefix ../qt \
 -debug \
 -opensource \
 -confirm-license \
 -static   \
 -make libs \
 -nomake examples \
 -nomake tests \
 -no-use-gold-linker \
 -no-gcc-sysroot \
 -no-compile-examples \
 -no-icu \
 -skip qtlocation \
 -skip qtscript \
 -skip qtvirtualkeyboard \
 -skip qtspeech \
 -skip qtremoteobjects \
 -skip qtquick3d \
 -skip qtpurchasing \
 -skip qtgamepad \
 -skip qtdatavis3d \
 -skip qt3d \
 -no-gbm
```

When I try to build gammaray with the above qt5 version I get the following error:

```
usr/bin/ld : CMakeFiles/gammaray_wlcompositorinspector.dir/../qt/lib/cmake/Qt5WaylandCompositor/Qt5WaylandCompositor_QWaylandEglStreamBufferIntegrationPlugin_Import.cpp.o : dans la fonction « StaticQWaylandEglStreamBufferIntegrationPluginPluginInstance::StaticQWaylandEglStreamBufferIntegrationPluginPluginInstance() » :
/qt/lib/cmake/Qt5WaylandCompositor/Qt5WaylandCompositor_QWaylandEglStreamBufferIntegrationPlugin_Import.cpp:2 : référence indéfinie vers « qt_static_plugin_QWaylandEglStreamBufferIntegrationPlugin() »
```

I tried building the qtwayland module that ships with the source and rebuilding gammaray, but I get the same error

**Comment by Waqar144** [comment]
Seems like your Qt build isn't correct. Perhaps you are missing some library that is needed by Qt to provide wayland support

**Comment by Rhvarrier** [comment]
The Qt build works fine and I'm able to use it with my Qt application. This seems to be a problem only when compiling gammray

**Comment by Waqar144** [comment]
@Rhvarrier 

We test and build gammaray with at least a dozen Qt versions on multiple OSes daily in our CI.

Most likely your app doesn't require as many Qt modules as gammaray does, so it works. 

The amount of info you shared (1 line of error) is too little to say whats going on or to help you in any way. And on top of that the error is in a language thats alien to me.

You can try disabling some gammaray plugins to see if it helps.
