### ISSUE TITLE
OS X 10.9.3 error when try to attach process [QSharedMemory::handle: system-imposed size restrictions]

### ISSUE THREAD

**Issue by irekzayniev** [KDAB/GammaRay#83]
I'm running $sudo ./gammaray -p 59302 --inprocess
and error is
void GammaRay::Launcher::sendProbeSettings() Failed to obtain shared memory for probe settings: "QSharedMemory::handle: system-imposed size restrictions" - error code (QSharedMemory::SharedMemoryError): 2

**Comment by krf** [comment]
Closing b/c of lack of feedback.
