### ISSUE TITLE
New qml_lint picks up Qt 5 version, fails the build

### ISSUE THREAD

**Issue by ratijas** [KDAB/GammaRay#894]
```
# kdesrc-build running: 'ninja' '-j' '6'
# from directory: /home/ratijas/kde/build6/gammaray
[1/24] Run qmlint on the specified files and create the associated timestamp semaphore
FAILED: examples/quick-batching/Slider.qml.qmllint /home/ratijas/kde/build6/gammaray/examples/quick-batching/Slider.qml.qmllint 
cd /home/ratijas/kde/build6/gammaray/examples/quick-batching && /usr/bin/qmllint /home/ratijas/kde/src6/gammaray/examples/quick-batching/Slider.qml && /usr/bin/cmake -E touch /home/ratijas/kde/build6/gammaray/examples/quick-batching/Slider.qml.qmllint
/home/ratijas/kde/src6/gammaray/examples/quick-batching/Slider.qml:16 : Expected token `;'
[2/24] Run qmlint on the specified files and create the associated timestamp semaphore
[3/24] Linking CXX shared module lib/gammaray/3.0/qt6_6-x86_64/gammaray_kjobtracker_plugin.so
[4/24] Building CXX object ui/CMakeFiles/gammaray_ui.dir/aboutdata.cpp.o
[5/24] Building CXX object translations/CMakeFiles/ljsonupdate.dir/ljsonupdate.cpp.o
[6/24] Building CXX object launcher/cli/CMakeFiles/gammaray.dir/main.cpp.o
ninja: build stopped: subcommand failed.
```

Clearly, /usr/bin/qmllint is coming from qt5-declarative package.

Besides, what the heck is this linter suggesting? It is really suggesting no whitespace between the => arrow function?

```js
            onClicked: (mouse)=> {
                updateCurrentIndex(mouse.x, mouse.y)
            }
```

**Comment by winterz** [comment]
pretty sure we fixed this in the master branch already

yes, I see this in the master branch file examples/quick-batching/CMakeLists.txt:
```
if(QT_VERSION_MAJOR GREATER_EQUAL 6)
    qml_lint(Slider.qml)
endif()
```

**Comment by ferdnyc** [comment]
@winterz 

> yes, I see this in the master branch file examples/quick-batching/CMakeLists.txt:
> 
> ```
> if(QT_VERSION_MAJOR GREATER_EQUAL 6)
>     qml_lint(Slider.qml)
> endif()
> ```

I don't... @ratijas _is_ building with Qt6, AFAICT (`Linking CXX shared module lib/gammaray/3.0/qt6_6-x86_64/gammaray_kjobtracker_plugin.so`), but getting a Qt5 qmllint from `/usr/bin/qmllint` instead of the expected Qt6 qmllint. That's how I interpreted this.

I don't understand why there would be a `cmake/FindQmlLint.cmake` that probes the _path_ for a `qmllint` executable, instead of just using the `Qt6::qmllint` target.
