### ISSUE TITLE
GammaRay sidebar greyed out

### ISSUE THREAD

**Issue by crioux** [KDAB/GammaRay#93]
I built the recent head of GammaRay for Qt5.2.1 on x64, Windows. When attaching to or launching a compatible app (release or debug), inprocess or out of process local, I always get this:

![gammaray](https://cloud.githubusercontent.com/assets/819652/4624782/508478b8-536b-11e4-952a-70b2414ecceb.png)

Note the left sidebar is completely greyed out, and the actions menu is empty, and nothing is available. Am I doing something wrong or is this a bug?

**Comment by krf** [comment]
See https://github.com/KDAB/GammaRay/issues/93#issuecomment-59003966. Fixed when using Qt 5.4.
