### ISSUE TITLE
Need Help in building GammaRay

### ISSUE THREAD

**Issue by Thrillseekr** [KDAB/GammaRay#942]
Hello @dantti @krf @hasselmm @iamsergio @sengels 

I'm learning Qt/QML and need to learn GammaRay for running VLC.exe

I tried a lot following the [Install.md](https://github.com/KDAB/GammaRay/blob/master/INSTALL.md) but not get up to it.
Please help me in building GammayRay.

**Comment by Waqar144** [comment]
Please share what you have tried, what failed, what platform you are running on, which Qt version you used?

**Comment by Thrillseekr** [comment]
Sure,
I used Qt creator with a Qt 6.4.3 and build GammaRay successfully.
Then I paste path of VLC.exe (developer version) in the executables but `launch` option is  not available

I also repeated this this with Qt 5.15, but nothing happen

Help me to resolve this ABI issue please.

Check this screenshot
![image](https://github.com/KDAB/GammaRay/assets/118781875/ca1f9fd6-8d71-4e97-9736-81cf8d17a8b3)

**Comment by Waqar144** [comment]
The Qt you use for building your target program must be exactly the same as the Qt used for building gammaray

In your case it seems like the target program is built in a way that gammaray can't detect its Qt version.

There's not much I can do to help you here. I would suggest building vlc yourself and making sure it links to Qt dynamically. Then use the same Qt to build gammaray.

**Comment by Thrillseekr** [comment]
Thanks @Waqar144
The information you provided is helpful, and I follow this and update you
