### ISSUE TITLE
Widget Inspector not updating in real time

### ISSUE THREAD

**Issue by brycegbrazen** [KDAB/GammaRay#953]
Hi all,

I noticed the Widgets tab of Gamma Ray (Widget Inspector) is not updating in real time.

I did a quick test of resizing the main window using the resizing handles and did not see the Width + Height properties update until I clicked on a different widget in the object hierarchy and then clicked back on the original widget.

Is this expected behavior? I didn't see it mentioned anywhere if the Widget Inspector is intended to be real time or not.

I was referencing [this link](https://docs.kdab.com/gammaray-manual/latest/gammaray-widget-inspector.html)

# Specs
- Windows 10
- Gamma Ray built with Qt 5.15.2 binaries
- Qt Creator 12.0.1

Here's a .zip of the C++ project I tested with as a sanity check.
[SimpleQtProject.zip](https://github.com/KDAB/GammaRay/files/14412298/SimpleQtProject.zip)

**Comment by mattkdab** [comment]
This is expected behavior. These properties lack signals to notify of value change.
