### ISSUE TITLE
Help Needed: Building GammaRay from Source on UBUNTU

### ISSUE THREAD

**Issue by Djain318** [KDAB/GammaRay#958]
Hello

**Comment by Waqar144** [comment]
Download Qt from the official website. Use the installer to install it. It will also install Qt Creator. Then use the installed Qtcreator to build Gammaray. QtCreator can open cmake files and will handle the rest for you.

You can also use the distro-qt, but with the amount of information you have provided it isn't possible to provide much help

**Comment by Waqar144** [comment]
I would suggest you to first learn to build and work with simple Qt programs and also get some experience with using CMake before trying to build GammaRay.

**Comment by Thrillseekr** [comment]
Hello @Waqar144,
I want to build Gammaray from source.

I've successfully ran this commad
`cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/path/where/to/install `../path/to/gammaray``

But getting a error while executing command `cmake --build .`

> root@Mitra:~/GammaRay/build# cmake --build .
[24/910] Building CXX object core/CMakeFiles/gammaray_core.dir/bindingaggregator.cpp.o
FAILED: core/CMakeFiles/gammaray_core.dir/bindingaggregator.cpp.o
/usr/bin/c++  -DBACKWARD_HAS_BACKTRACE=0 -DBACKWARD_HAS_BACKTRACE_SYMBOL=1 -DBACKWARD_HAS_BFD=0 -DBACKWARD_HAS_DW=0 -DBACKWARD_HAS_DWARF=0 -DBACKWARD_HAS_LIBUNWIND=0 -DBACKWARD_HAS_UNWIND=1 -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x050500 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_URL_CAST_FROM_STRING -DQT_STRICT_ITERATORS -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -Dgammaray_core_EXPORTS -Icore -I../core -Icore/gammaray_core_autogen/include -I../ -I../3rdparty -I. -I../3rdparty/qt/5.5 -Icommon -isystem ../3rdparty/backward-cpp -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.12.8/QtCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.12.8/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wreorder -Wformat-security -Wsuggest-override -Wall -Wextra -pedantic -Woverloaded-virtual -Winit-self -Wmissing-include-dirs -Wunused -Wundef -Wpointer-arith -Wmissing-noreturn -Werror=return-type -Wswitch -std=gnu++0x -fno-operator-names -Wzero-as-null-pointer-constant -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -MD -MT core/CMakeFiles/gammaray_core.dir/bindingaggregator.cpp.o -MF core/CMakeFiles/gammaray_core.dir/bindingaggregator.cpp.o.d -o core/CMakeFiles/gammaray_core.dir/bindingaggregator.cpp.o -c ../core/bindingaggregator.cpp
../core/bindingaggregator.cpp: In function ‘void GammaRay::BindingAggregator::scanForBindingLoops()’:
../core/bindingaggregator.cpp:95:42: error: no matching function for call to ‘QMutexLocker::QMutexLocker(QRecursiveMutex*)’
   95 |     QMutexLocker lock(Probe::objectLock());
      |                                          ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QMutexLocker:1,
                 from ../core/bindingaggregator.cpp:27:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:199:21: note: candidate: ‘QMutexLocker::QMutexLocker(QBasicMutex*)’
  199 |     inline explicit QMutexLocker(QBasicMutex *m) QT_MUTEX_LOCK_NOEXCEPT
      |                     ^~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:199:47: note:   no known conversion for argument 1 from ‘QRecursiveMutex*’ to ‘QBasicMutex*’
  199 |     inline explicit QMutexLocker(QBasicMutex *m) QT_MUTEX_LOCK_NOEXCEPT
      |                                  ~~~~~~~~~~~~~^
[33/910] Building CXX object core/CMakeFiles/gammaray_core.dir/metaobjectrepository.cpp.o
ninja: build stopped: subcommand failed.
root@Mitra:~/GammaRay/build#

> 

please help

**Comment by Waqar144** [comment]
Seems like you are using an unsupport Qt version (5.12.8). You can try to build the `3.0` branch if you want that Qt version. Otherwise use 5.15.X

**Comment by Thrillseekr** [comment]
Actually I'm using Ubuntu and used the command 
`sudo apt install qt5-qmake`

By this Qt 5.12.8 is installed

And GammaRay cmake command is using that only

Please guide me how can I can I change qt version on Ubuntu that gammaray cmake command can render

**Comment by Thrillseekr** [comment]
Thanks a lot sir, @Waqar144 
I have successfully build GammaRay with 3.0 branch inside a Build directory using these commands:

```
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/path/where/to/install ../path/to/gammaray
 cmake --build .
 cmake --build . --target install
```
After this how can I run the GammaRay executable.
Where should I get it??

Waiting for your reply.

Thanks

**Comment by Thrillseekr** [comment]
Thanks @Waqar144,
I'm getting this type of wierd interface.
How to improve it??

![Screenshot (120)](https://github.com/KDAB/GammaRay/assets/118781875/ba820b05-2158-4b60-8a8f-bb7417f0b269)

**Comment by Waqar144** [comment]
no idea, seems like a problem with your distro / setup.
