### ISSUE TITLE
Error while building GammaRay for Qt 6.6.2 on windows

### ISSUE THREAD

**Issue by thrilseekr** [KDAB/GammaRay#980]
Hello, @dantti @Waqar144 
Please help me in building GammaRay for Qt 6.6.2

While building an error occurs. 
Here are the logs:

> C:\Users\Toshiba\Desktop\GammaRay\build>cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:/Users/Toshiba/Desktop/GammaRay/build ..
> 
> -- The CXX compiler identification is GNU 6.3.0
> -- The C compiler identification is GNU 6.3.0
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Setting build type to Debug as none was specified.
> -- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
> -- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
> -- Could NOT find libdwarf (missing: LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR LIBELF_LIBRARY LIBELF_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
> -- Found Backward: C:/Users/Toshiba/Desktop/GammaRay/3rdparty/backward-cpp
> -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.43.0.windows.1")
> -- Building GammaRay 3.0.95 (revision: ab800c76c) in Debug mode
> -- Performing Test C_SUPPORTS_UNUSED_BUT_SET
> -- Performing Test C_SUPPORTS_UNUSED_BUT_SET - Success
> -- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET
> -- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET - Success
> -- Performing Test C_SUPPORTS_LOGICAL_OP
> -- Performing Test C_SUPPORTS_LOGICAL_OP - Success
> -- Performing Test CXX_SUPPORTS_LOGICAL_OP
> -- Performing Test CXX_SUPPORTS_LOGICAL_OP - Success
> -- Performing Test C_SUPPORTS_POINTER_MEMACCESS
> -- Performing Test C_SUPPORTS_POINTER_MEMACCESS - Success
> -- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS
> -- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS - Success
> -- Performing Test C_SUPPORTS_REORDER
> -- Performing Test C_SUPPORTS_REORDER - Failed
> -- Performing Test CXX_SUPPORTS_REORDER
> -- Performing Test CXX_SUPPORTS_REORDER - Success
> -- Performing Test C_SUPPORTS_FORMAT_SECURITY
> -- Performing Test C_SUPPORTS_FORMAT_SECURITY - Failed
> -- Performing Test CXX_SUPPORTS_FORMAT_SECURITY
> -- Performing Test CXX_SUPPORTS_FORMAT_SECURITY - Failed
> -- Performing Test C_SUPPORTS_SUGGEST_OVERRIDE
> -- Performing Test C_SUPPORTS_SUGGEST_OVERRIDE - Failed
> -- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE
> -- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE - Success
> -- Performing Test HAVE_GXX_GNUXX11
> -- Performing Test HAVE_GXX_GNUXX11 - Success
> -- Performing Test HAVE_GXX_CXX11
> -- Performing Test HAVE_GXX_CXX11 - Success
> CMake Error at CMakeLists.txt:441 (find_package):
>   Could not find a configuration file for package "QT" that is compatible
>   with requested version "5.15".
> 
>   The following configuration files were considered but not accepted:
> 
>   C:/Qt/6.6.2/mingw_64/lib/cmake/Qt6/Qt6Config.cmake, version: 6.6.2 (64bit)
>
> -- Configuring incomplete, errors occurred!
> 
> C:\Users\Toshiba\Desktop\GammaRay\build>

**Comment by Waqar144** [comment]
Cmake is not able to find Qt.

**Comment by thrilseekr** [comment]
@Waqar144 @dantti 
But if I run `qmake --version` it is giving the output `qmake version 3.24.0`
`Available Qt 6.6.2 at location..`

Which mean that Qt is added to path, so cmake should find it.

How to resolve the issue, please help its urgent

**Comment by Waqar144** [comment]
Try passing `-DQT_VERSION_MAJOR=6` argument to the cmake command.

**Comment by thrilseekr** [comment]
That's so nice of you helping me. Thanks
Another Error occurs.


Here are the logs, please look into and suggest changes

> C:\Users\Toshiba\Desktop\GammaRay\build>set CMAKE_PREFIX_PATH=C:\Qt\6.6.2\mingw_64
> 
> C:\Users\Toshiba\Desktop\GammaRay\build>echo %CMAKE_PREFIX_PATH%
> C:\Qt\6.6.2\mingw_64
> 
> C:\Users\Toshiba\Desktop\GammaRay\build>cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:/Users/Toshiba/Desktop/GammaRay/build -DQT_VERSION_MAJOR=6 ..
> -- The CXX compiler identification is GNU 6.3.0
> -- The C compiler identification is GNU 6.3.0
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Setting build type to Debug as none was specified.
> -- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
> -- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
> -- Could NOT find libdwarf (missing: LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR LIBELF_LIBRARY LIBELF_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
> -- Found Backward: C:/Users/Toshiba/Desktop/GammaRay/3rdparty/backward-cpp
> -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.43.0.windows.1")
> -- Building GammaRay 3.0.95 (revision: ab800c76c) in Debug mode
> -- Performing Test C_SUPPORTS_UNUSED_BUT_SET
> -- Performing Test C_SUPPORTS_UNUSED_BUT_SET - Success
> -- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET
> -- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET - Success
> -- Performing Test C_SUPPORTS_LOGICAL_OP
> -- Performing Test C_SUPPORTS_LOGICAL_OP - Success
> -- Performing Test CXX_SUPPORTS_LOGICAL_OP
> -- Performing Test CXX_SUPPORTS_LOGICAL_OP - Success
> -- Performing Test C_SUPPORTS_POINTER_MEMACCESS
> -- Performing Test C_SUPPORTS_POINTER_MEMACCESS - Success
> -- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS
> -- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS - Success
> -- Performing Test C_SUPPORTS_REORDER
> -- Performing Test C_SUPPORTS_REORDER - Failed
> -- Performing Test CXX_SUPPORTS_REORDER
> -- Performing Test CXX_SUPPORTS_REORDER - Success
> -- Performing Test C_SUPPORTS_FORMAT_SECURITY
> -- Performing Test C_SUPPORTS_FORMAT_SECURITY - Failed
> -- Performing Test CXX_SUPPORTS_FORMAT_SECURITY
> -- Performing Test CXX_SUPPORTS_FORMAT_SECURITY - Failed
> -- Performing Test C_SUPPORTS_SUGGEST_OVERRIDE
> -- Performing Test C_SUPPORTS_SUGGEST_OVERRIDE - Failed
> -- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE
> -- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE - Success
> -- Performing Test HAVE_GXX_GNUXX11
> -- Performing Test HAVE_GXX_GNUXX11 - Success
> -- Performing Test HAVE_GXX_CXX11
> -- Performing Test HAVE_GXX_CXX11 - Success
> CMake Error at CMakeLists.txt:454 (find_package):
>   Could not find a configuration file for package "Qt6" that is compatible
>   with requested version "".
> 
>   The following configuration files were considered but not accepted:
>     C:/Qt/6.6.2/mingw_64/lib/cmake/Qt6/Qt6Config.cmake, version: 6.6.2 (64bit)
>
> -- Configuring incomplete, errors occurred!
> 
> C:\Users\Toshiba\Desktop\GammaRay\build>

**Comment by thrilseekr** [comment]
Hello, @Waqar144  @dantti 
That's so nice of you helping me. Thanks
Another Error occurs related to cmakelist 😭

Here are the logs, please look into and suggest changes

> C:\Users\Toshiba\Desktop\GammaRay\build>set CMAKE_PREFIX_PATH=C:\Qt\6.6.2\mingw_64
> 
> C:\Users\Toshiba\Desktop\GammaRay\build>echo %CMAKE_PREFIX_PATH%
> C:\Qt\6.6.2\mingw_64
> 
> C:\Users\Toshiba\Desktop\GammaRay\build>cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:/Users/Toshiba/Desktop/GammaRay/build -DQT_VERSION_MAJOR=6 ..
> -- The CXX compiler identification is GNU 6.3.0
> -- The C compiler identification is GNU 6.3.0
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Setting build type to Debug as none was specified.
> -- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
> -- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
> -- Could NOT find libdwarf (missing: LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR LIBELF_LIBRARY LIBELF_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
> -- Found Backward: C:/Users/Toshiba/Desktop/GammaRay/3rdparty/backward-cpp
> -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.43.0.windows.1")
> -- Building GammaRay 3.0.95 (revision: ab800c76c) in Debug mode
> -- Performing Test C_SUPPORTS_UNUSED_BUT_SET
> -- Performing Test C_SUPPORTS_UNUSED_BUT_SET - Success
> -- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET
> -- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET - Success
> -- Performing Test C_SUPPORTS_LOGICAL_OP
> -- Performing Test C_SUPPORTS_LOGICAL_OP - Success
> -- Performing Test CXX_SUPPORTS_LOGICAL_OP
> -- Performing Test CXX_SUPPORTS_LOGICAL_OP - Success
> -- Performing Test C_SUPPORTS_POINTER_MEMACCESS
> -- Performing Test C_SUPPORTS_POINTER_MEMACCESS - Success
> -- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS
> -- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS - Success
> -- Performing Test C_SUPPORTS_REORDER
> -- Performing Test C_SUPPORTS_REORDER - Failed
> -- Performing Test CXX_SUPPORTS_REORDER
> -- Performing Test CXX_SUPPORTS_REORDER - Success
> -- Performing Test C_SUPPORTS_FORMAT_SECURITY
> -- Performing Test C_SUPPORTS_FORMAT_SECURITY - Failed
> -- Performing Test CXX_SUPPORTS_FORMAT_SECURITY
> -- Performing Test CXX_SUPPORTS_FORMAT_SECURITY - Failed
> -- Performing Test C_SUPPORTS_SUGGEST_OVERRIDE
> -- Performing Test C_SUPPORTS_SUGGEST_OVERRIDE - Failed
> -- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE
> -- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE - Success
> -- Performing Test HAVE_GXX_GNUXX11
> -- Performing Test HAVE_GXX_GNUXX11 - Success
> -- Performing Test HAVE_GXX_CXX11
> -- Performing Test HAVE_GXX_CXX11 - Success
> CMake Error at CMakeLists.txt:454 (find_package):
>   Could not find a configuration file for package "Qt6" that is compatible
>   with requested version "".
> 
>   The following configuration files were considered but not accepted:
>
>     C:/Qt/6.6.2/mingw_64/lib/cmake/Qt6/Qt6Config.cmake, version: 6.6.2 (64bit)
>
> -- Configuring incomplete, errors occurred!
> 
> C:\Users\Toshiba\Desktop\GammaRay\build>
