### ISSUE TITLE
QT 6.7 Target not responding

### ISSUE THREAD

**Issue by Snolandia** [KDAB/GammaRay#983]
All self tests passed. Any sort of gui just closes itself and doesnt do anything. Not sure where to go from here.

The examples that came with the code also did not work. 

gammaray.exe --pid 16160
Detected ABI qt6_7-GNU-x86_64, using ABI qt6_7-GNU-x86_64.
Target not responding - timeout. Try setting the env variable GAMMARAY_LAUNCHER_TIMEOUT to a bigger value (in seconds).
See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting

gammaray.exe --version
GammaRay version 3.0.95
┬⌐ Klaralvdalens Datakonsult AB, a KDAB Group company, info@kdab.com
Protocol version 38
Broadcast version 2

Launching with terminal and -i style  offers a different error that isnt seen elsewhere

Detected ABI qt6_7-GNU-x86_64, using ABI qt6_7-GNU-x86_64.
Loading probe DLL failed: "Cannot load library C:\\Program Files (x86)\\GammaRay\\plugins\\gammaray\\3.0\\qt6_7-GNU-x86_64\\gammaray_probe.dll: The specified module could not be found."
Target not responding - timeout. Try setting the env variable GAMMARAY_LAUNCHER_TIMEOUT to a bigger value (in seconds).
See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting

But gammaray_probe.dll is in that exact file and exact location.

Not really sure where to go from here.

**Comment by Waqar144** [comment]
> Loading probe DLL failed: "Cannot load library C:\Program Files (x86)\GammaRay\plugins\gammaray\3.0\qt6_7-GNU-x86_64\gammaray_probe.dll: The specified module could not be found."
> ..
> But gammaray_probe.dll is in that exact file and exact location.

But probably something it depends on wasn't found, so the dll load fails. You need to debug what's missing. The internet says you can use [sysinternals procmon](https://stackoverflow.com/questions/2066180/the-specified-module-could-not-be-found-0x8007007e) or [loader snaps](https://devblogs.microsoft.com/oldnewthing/20131127-00/?p=2553)

**Comment by Waqar144** [comment]
seems duplicate of #959
