### ISSUE TITLE
GammayRay exit on attach to process

### ISSUE THREAD

**Issue by aliks-os** [KDAB/GammaRay#984]
The application and GammaRay built with Mingw-32 Qt5.15.2, windows 11.

When I try attach to the process, 

GammaRay closing with message
D:\Projects\GammaRay\build\Desktop_Qt_5_15_2_MinGW_32_bit-Release\bin\gammaray-launcher.exe exited with code 0

In debug application I see
GammaRay: Failed to load: 
D:\Projects\GammaRay\build\Desktop_Qt_5_15_2_MinGW_32_bit-Release\plugins\gammaray\3.0\qt5_15-GNU-i686\gammaray_probe.dll
--------
When I try launch the application from GammaRay,
D:\Projects\GammaRay\build\Desktop_Qt_5_15_2_MinGW_32_bit-Release\bin\gammaray-launcher.exe exited with code 0

**Comment by aliks-os** [comment]
According https://github.com/KDAB/GammaRay/issues/959

The system environment variable PATH setting:

%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;D:\StrawberryPerl\c\bin;D:\StrawberryPerl\perl\site\bin;D:\StrawberryPerl\perl\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;D:\Qt\5.15.2\mingw81_32\bin;D:\Qt\Tools\CMake_64\bin;D:\Qt\Tools\Ninja;D:\Projects\GammaRay\build\Desktop_Qt_5_15_2_MinGW_32_bit-Debug\plugins\gammaray\3.0\qt5_15-GNU-i686d;D:\Projects\GammaRay\build\Desktop_Qt_5_15_2_MinGW_32_bit-Release\plugins\gammaray\3.0\qt5_15-GNU-i686;

**Comment by Waqar144** [comment]
Seems like there is a problem with mingw builds in general, not sure why. Can you try to debug using the suggestions mentioned in https://github.com/KDAB/GammaRay/issues/983 ?

Closing as its a dupe.
