### ISSUE TITLE
QuickScenes view is once again unusable with QQuickWidget apps

### ISSUE THREAD

**Issue by ratijas** [KDAB/GammaRay#990]
![image](https://github.com/KDAB/GammaRay/assets/6737986/03f0b1f8-e6c5-4def-8c84-d2a5708cfb9a)

It has happened before: https://github.com/KDAB/GammaRay/issues/815

### Versions

GammaRay: dcb6af6dc0c0250a67d0ceac4bb3a8a3f2cc2fdd
```
Operating System: Arch Linux 
KDE Plasma Version: 6.0.80
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.8.8-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 970M/PCIe/SSE2
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: G752VT
System Version: 1.0
```

**Comment by Waqar144** [comment]
Should be fixed in master, can you try again?

**Comment by ratijas** [comment]
Works for me, both on Qt 6.7.0-6 and on current Qt dev branch. Thanks!
