### ISSUE TITLE
error when i cloned gammaray from github

### ISSUE THREAD

**Issue by shabanreda** [KDAB/GammaRay#996]
please need help!
i am using qt6.7
when i clone Gammaray from github 
I open qt creator and start with New project > Git Clone
Location Repository:  https://github.com/KDAB/GammaRay.git
Directory:  GammaRay   CLK > Next  (clones into GammaRay)  > CLK > Finish (open dialog box with 
2 Project File: choices)

**My 2nd attempt I selected:** 
D:\Qt\GammaRay\gamma-qt-ci-only.pro (this file does exist in this directory)  CLK > OK (opens Configure Project screen with two(2) suitable kits available.
 Desktop_Qt_6_7_0_MSVC2019_64bit_release > CLK > Details (unchecked Debug and Profile per your video)

This opens a Qt Creator project but with errors:
it shows that error 

 "K:\embedded_deploma\qt_quick\qt_projects\GammaRay\qt-ci-wrapper\qt-ci-wrapper.pro:54: **error: Cannot find feature qt_docs "**

refere to 
` load(qt_docs) `
in qt-ci-wrapper\qt-ci-wrapper.pro

**Comment by winterz** [comment]
not sure what you're trying to do but qt-ci-wrapper.pro is intended for the Qt CI system only.

we use the cmake buildsystem
read the INSTALL.md file

**Comment by shabanreda** [comment]
> not sure what you're trying to do but qt-ci-wrapper.pro is intended for the Qt CI system only.
> 
> we use the cmake buildsystem read the INSTALL.md file

i  follow  steps that is explained in KDAB Gammaray tutorial
to setup gammaray in windows
[https://www.youtube.com/watch?v=GefC1-W6TO0](url)

**Comment by shabanreda** [comment]
When I choose the first option, this window appears for me to choose kits.
if i choose (select all Kits) , It shows me the following error :
  `The kit needs to define a CMake tool to parse this project.
![gammaray daialog2](https://github.com/KDAB/GammaRay/assets/90008918/0af42d0f-e30a-41de-ab7f-9d88e703a99d)
`

**Comment by Waqar144** [comment]
> The kit needs to define a CMake tool to parse this project

Seems like your Qt creator isn't configured properly. Check the settings, configure the kits and then try again.

This is out of scope for us so I am closing the issue.
